### PR TITLE
fix: Hide minimap in worlds

### LINKED ISSUE #850: New minimap mode for Worlds
The minimap is not usefull whenever you are in worlds.

The minimap should be collapsed and the button to uncollapse should be disabled. 

That space should be taken by the "Go to genesis city" button.

Image

Image

Figmas:
- https://www.figma.com/file/6EKamT36BbZT9dwTcho6ut/%F0%9F%97%BA%EF%B8%8F-Worlds-%7C-Explorer-Alpha-%7C-04%2F24?type=design&node-id=401-2985&mode=design&t=l5reQKzhs4GiAcsQ-0
- https://www.figma.com/file/6EKamT36BbZT9dwTcho6ut/%F0%9F%97%BA%EF%B8%8F-Worlds-%7C-Explorer-Alpha-%7C-04%2F24?type=design&node-id=401-2987&mode=design&t=6zGNwvW6dlqtdo3K-0

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #850 

### Minimap in Genesis City mode
image

### Minimap in World mode
image

### Warning message in the Navmap when we're in a world
image

## How to test the changes?
1. Launch the explorer.
2. Go to any world.
3. Check that the minimap is in "World" mode. A new [JUMP BACK TO GENESIS CITY] button will appear below the minimap. Check also that, if you open the navmap (with the [M] key), you will see a warning notification.
4. Go back to Genesis City using the button commented above.
5. Check that the minimap back to its normal mode and, if you open the navmap, you won't see the warning notification.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by anicalbano — COMMENTED** [review]
The functionality looks good! Just a question before the approval: 

- Is it ok that, if we close the warning message on the map, we don't see it again? 

- And according to the requirements written on the ticket, it says that the uncollapse button should be disabled, did that change?


https://github.com/decentraland/unity-explorer/assets/139157886/ecb39ed3-39c5-404a-bbcc-ed887c279a33


https://github.com/decentraland/unity-explorer/assets/139157886/38123777-2ffe-4f71-9778-2aacd91d73e7

**Comment by sandrade-dcl** [comment]
@anicalbano I answer your comments:

> * Is it ok that, if we close the warning message on the map, we don't see it again?

Yes, that's something that was already requested from Product 👍 

> * And accorsing to the requirements written on the ticket, it says that the uncollapse button should be disabled, did that change?

Yes, it changed. The ticket's description is a bit old and Romi requested some changes after it. So, effectively, it's ok that the collapse/uncollapse buttons also appears in "world" mode 👍

**Review by anicalbano — APPROVED** [review]

**Comment by sandrade-dcl** [comment]
> @sandrade-dcl aesthetic wise the UI is perfect, even the animation in the mini map. What is missing is replacing the coordinates by the world icon plus world name. Also, can we make the warning notification in the map disappear with a fade out?

Done!

File: Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs [hunk 1]
```diff
@@ -340,7 +341,7 @@ async UniTask InitializeContainersAsync(IPluginSettingsContainer settingsContain
                 ),
                 new ProfilePlugin(container.ProfileRepository, profileCache, staticContainer.CacheCleaner, new ProfileIntentionCache()),
                 new MapRendererPlugin(mapRendererContainer.MapRenderer),
-                new MinimapPlugin(staticContainer.AssetsProvisioner, container.MvcManager, mapRendererContainer, placesAPIService),
+                new MinimapPlugin(staticContainer.AssetsProvisioner, container.MvcManager, mapRendererContainer, placesAPIService, realmData, container.ChatMessagesBus),
```
Comment (pravusjif) [inline Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs:344]: With main's latest changes we need to update that `realmData` with `staticContainer.RealmData`

Comment (sandrade-dcl) [reply Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs]: Done!

**Review by pravusjif — APPROVED** [review]
