### PR TITLE
fix: participants collection modified while iterating

### LINKED ISSUE #3796: [QA] Section | Collection was modified; enumeration operation may not execute.
### 🛠️ **Build version:**

a58d85b8fda9ff64240bfe1ce80c6d144ede4362

### 📔 **Issue Description:**

When loading into the plaza: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### **STR:** 

  1. Click "jump into decentraland"

### ✔️ **Expected Result:**

Nothing.

### ❌ **Actual Result with evidence:**

[LIVEKIT]: ArchipelagoIslandRoom - CycleStepAsync failed: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.Dictionary`2+KeyCollection+Enumerator[TKey,TValue].MoveNext () [0x00013] in <356d430fdcb04bbf8dc54776e1d3627f>:0 
  at DCL.Multiplayer.Profiles.RemoveIntentions.ThreadSafeRemoveIntentions.OnConnectionUpdated (LiveKit.Rooms.IRoom room, LiveKit.Rooms.ConnectionUpdate connectionupdate, DCL.Multiplayer.Connections.Rooms.RoomSource roomSource) [0x00060] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Profiles\RemoveIntentions\ThreadSafeRemoveIntentions.cs:56 
  at DCL.Multiplayer.Profiles.RemoveIntentions.ThreadSafeRemoveIntentions.OnConnectionUpdateFromIsland (LiveKit.Rooms.IRoom room, LiveKit.Rooms.ConnectionUpdate connectionupdate) [0x00001] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Profiles\RemoveIntentions\ThreadSafeRemoveIntentions.cs:32 
  at DCL.Multiplayer.Connections.Rooms.InteriorRoom.RoomOnConnectionUpdated (LiveKit.Rooms.IRoom room, LiveKit.Rooms.ConnectionUpdate connectionupdate) [0x00001] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\InteriorRoom.cs:165 
  at DCL.Multiplayer.Connections.Rooms.InteriorRoom.RoomOnConnectionUpdated (LiveKit.Rooms.IRoom room, LiveKit.Rooms.ConnectionUpdate connectionupdate) [0x00001] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\InteriorRoom.cs:165 
  at DCL.Multiplayer.Connections.Rooms.InteriorRoom.SimulateConnectionStateChanged () [0x00042] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\InteriorRoom.cs:121 
  at DCL.Multiplayer.Connections.Rooms.InteriorRoom.SwapRoomsAsync (DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection roomSelection, LiveKit.Rooms.IRoom previous, LiveKit.Rooms.IRoom newRoom, UnityEngine.Pool.IObjectPool`1[T] roomsPool, System.Threading.CancellationToken ct) [0x00139] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\InteriorRoom.cs:93 
  at Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) [0x0001e] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTask.Factory.cs:211 
  at Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () [0x00015] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTask.cs:312 
  at DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom.ChangeRoomsAsync[T] (UnityEngine.Pool.IObjectPool`1[T] roomsPool, T credentials, System.Threading.CancellationToken ct) [0x00180] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\Connective\ConnectiveRoom.cs:251 
  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00067] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00002] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\CompilerServices\StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00025] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTask.cs:653 
  at DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom.TryConnectToRoomAsync (System.String connectionString, System.Threading.CancellationToken token) [0x0007a] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\Connective\ConnectiveRoom.cs:190 
  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00067] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00002] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\CompilerServices\StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00025] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTask.cs:653 
  at DCL.Multiplayer.Connections.Archipelago.Rooms.ArchipelagoIslandRoom.CycleStepAsync (System.Threading.CancellationToken token) [0x00090] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Archipelago\Rooms\ArchipelagoIslandRoom.cs:72 
  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00067] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) [0x00002] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\CompilerServices\StateMachineRunner.cs:218 
  at Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () [0x00015] in .\Library\PackageCache\com.cysharp.unitask@73d86259ce\Runtime\UniTask.cs:312 
  at DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom.ExecuteWithRecoveryAsync (System.Func`2[T,TResult] func, System.String funcName, DCL.Multiplayer.Connections.Rooms.Connective.IConnectiveRoom+ConnectionLoopHealth enterState, DCL.Multiplayer.Connections.Rooms.Connective.IConnectiveRoom+ConnectionLoopHealth stateOnException, System.Threading.CancellationToken ct) [0x0005c] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Multiplayer\Connections\Rooms\Connective\ConnectiveRoom.cs:151 
0x00007ff65ebb443d (Unity) StackWalker::GetCurrentCallstack
0x00007ff65ebb9519 (Unity) StackWalker::ShowCallstack
0x00007ff65fbaef41 (Unity) GetStacktrace
0x00007ff66026b82e (Unity) DebugStringToFile
0x00007ff65db0b098 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x00000253390d204a (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x00000253390d1ebb (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000002542698b2ce (Mono JIT Code) DCL.Diagnostics.DebugLogReportHandler:LogInternal (UnityEngine.LogType,DCL.Diagnostics.ReportData,UnityEngine.Object,object) (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:75)
0x00000253ffa22ec6 (Mono JIT Code) DCL.Diagnostics.ReportHandlerBase:Log (UnityEngine.LogType,DCL.Diagnostics.ReportData,UnityEngine.Object,object) (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/ReportHandlerBase.cs:28)
0x00000253390bfbd0 (Mono JIT Code) DCL.Diagnostics.ReportHubLogger:Log (UnityEngine.LogType,DCL.Diagnostics.ReportData,object,UnityEngine.Object,DCL.Diagnostics.ReportHandler) (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHubLogger.cs:73)
0x000002542b8657b3 (Mono JIT Code) DCL.Diagnostics.ReportHub:LogError (DCL.Diagnostics.ReportData,object,DCL.Diagnostics.ReportHandler) (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHub.cs:68)
0x0000025454f044cb (Mono JIT Code) DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<ExecuteWithRecoveryAsync>d__23:MoveNext () (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/ConnectiveRoom.cs:155)
0x00000253d89fc477 (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<TStateMachine_REF>:Run () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:189)
0x00000253d89fb183 (Mono JIT Code) Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
0x000002542b8692ac (Mono JIT Code) Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<Cysharp.Threading.Tasks.AsyncUnit>:TrySetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
0x000002542b868e7b (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<TStateMachine_REF>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:210)
0x000002542b868d59 (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:59)
0x00000254550b1c93 (Mono JIT Code) DCL.Multiplayer.Connections.Archipelago.Rooms.ArchipelagoIslandRoom/<CycleStepAsync>d__7:MoveNext () (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/ArchipelagoIslandRoom.cs:82)
0x00000253d89fc477 (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1<TStateMachine_REF>:Run () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:189)
0x00000253d89fb183 (Mono JIT Code) Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
0x000002545512a4ec (Mono JIT Code) Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>:TrySetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
0x000002545512a09b (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<TryConnectToRoomAsync>d__26, DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:334)
0x0000025455129f19 (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1<DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:186)
0x000002545501d56b (Mono JIT Code) DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<TryConnectToRoomAsync>d__26:MoveNext () (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/ConnectiveRoom.cs:214)
0x00000254550eab8b (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<TryConnectToRoomAsync>d__26, DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>:Run () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:313)
0x00000253d89fb183 (Mono JIT Code) Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
0x0000025455129cec (Mono JIT Code) Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<System.ValueTuple`2<bool, DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>>:TrySetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
0x000002545512989b (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<ChangeRoomsAsync>d__27`1<DCL.Multiplayer.Connections.Credentials.ConnectionStringCredentials>, System.ValueTuple`2<bool, DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:334)
0x0000025455129719 (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1<System.ValueTuple`2<bool, DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>>:SetException (System.Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:186)
0x000002545501f09b (Mono JIT Code) DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<ChangeRoomsAsync>d__27`1<DCL.Multiplayer.Connections.Credentials.ConnectionStringCredentials>:MoveNext () (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/ConnectiveRoom.cs:253)
0x00000254550e58eb (Mono JIT Code) Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<DCL.Multiplayer.Connections.Rooms.Connective.ConnectiveRoom/<ChangeRoomsAsync>d__27`1<DCL.Multiplayer.Connections.Credentials.ConnectionStringCredentials>, System.ValueTuple`2<bool, DCL.Multiplayer.Connections.Rooms.Connective.RoomSelection>>:Run () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:313)
0x0000025429e35180 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:InvokeAction (object)
0x0000025429e34db4 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:RunCallback (System.Threading.ContextCallback,object,System.Threading.Tasks.Task&)
0x0000025429e348fb (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run (System.Threading.Tasks.Task,bool)
0x00000252e5629868 (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x00000252e5626fb3 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x0000025454f562a3 (Mono JIT Code) System.Threading.Tasks.Task`1<bool>:TrySetResult (bool)
0x00000254550e555b (Mono JIT Code) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>:SetResult (bool)
0x000002545502c59b (Mono JIT Code) DCL.Multiplayer.Connections.Rooms.LogRoom/<ConnectAsync>d__70:MoveNext () (at D:/Decentraland/unity-explorer/Explorer/Assets/DCL/Multiplayer/Connections/Rooms/LogRoom.cs:201)
0x00000252ea3de89a (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x00000252e5604e1e (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000252e5603beb (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000252ea3dd24b (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x0000025429e35180 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:InvokeAction (object)
0x0000025429e34db4 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:RunCallback (System.Threading.ContextCallback,object,System.Threading.Tasks.Task&)
0x0000025429e348fb (Mono JIT Code) System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run (System.Threading.Tasks.Task,bool)
0x00000252e5629868 (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x00000252e5626fb3 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x0000025454f562a3 (Mono JIT Code) System.Threading.Tasks.Task`1<bool>:TrySetResult (bool)
0x00000254550e555b (Mono JIT Code) System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>:SetResult (bool)
0x0000025455048b2b (Mono JIT Code) LiveKit.AsyncInstruction/<AwaitWithSuccess>d__15:MoveNext () (at ./Library/PackageCache/com.decentraland.livekit-sdk@8c3fe36667/Runtime/Scripts/Internal/YieldInstruction.cs:36)
0x00000252ea3de89a (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
0x00000252e5604e1e (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000252e5603beb (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000252ea3dd24b (Mono JIT Code) System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
0x0000025429e35180 (Mono JIT Code) System.Threading.Tasks.AwaitTaskContinuation:Invok<message truncated>

### ➗ **Repro Index:**

1/1

### 🖥️ **Operative system and additional Notes:**

Windows Editor in play mode on Windows 11

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #3796 

The root of the problem seems to be the threading concurrency. The participant list gets modified by another thread while its being iterated, even tho we do have a mutex.
The changes introduces a thread lock on `root.Participants` during the iteration process. Does it fix the issue? Cant tell 100%, since i was not able to reproduce it. As an alternative solution i though about making a copy of the participant list, but we could also have the same issue while its being copied through every element.
Additionally a minor performance improvement has been made so the `RemoveIntention` can be properly compared in the `HashSet`.

## Test Instructions

Jump in world into crowded places. Check in the logs you don't have the exception. Check that players are disconnected properly.

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs [hunk 1]
```diff
@@ -16,5 +17,14 @@ public RemoveIntention(string walletId, RoomSource fromRoom)
 
         public override string ToString() =>
             $"(RemoveIntention: (WalletId: {WalletId}, From Room: {FromRoom}))";
+
+        public bool Equals(RemoveIntention other) =>
+            WalletId == other.WalletId && FromRoom == other.FromRoom;
```
Comment (lorux0) [inline Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs:22]: Should we consider the room? Or only the wallet?

Comment (AnsisMalins) [reply Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs:22]: Where is it used?

File: Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/ThreadSafeRemoveIntentions.cs [hunk 2]
```diff
@@ -53,10 +53,13 @@ private void OnConnectionUpdated(IRoom room, ConnectionUpdate connectionupdate,
             {
                 using var _ = multithreadSync.GetScope();
 
-                foreach (string identity in room.Participants.RemoteParticipantIdentities())
+                lock (room.Participants)
```
[the remark this answers is not in the document]
Comment (lorux0) [reply Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/ThreadSafeRemoveIntentions.cs:57]: As we discusses i finally added the rest of the cases on which the participant list is being used

File: Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs (hunk 1 above)
Comment (AnsisMalins) [reply Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs:22]: Why did it work before?

**Review by AnsisMalins — APPROVED** [review]
