### PR TITLE
Fix: chat input highlight elements

### LINKED ISSUE #5109: [QA] Chat | Mentions are not blue when writing down another user's name
### 🛠️ **Build version:**
Dev build for stress testing 

### 📔 **Issue Description:**
Mentions do not turn blue when writing down the name of another player on the chat box 

### 👣 **STR:** 

  1. Open the app
  2. Go to the chat 
  3. Tag someone 
  4. Check that name does not appear blue until the user presses enter in the chat box

### ✔️ **Expected Result:**
Mentions should appear in blue color when writing another player's name on the chat box 

### ❌ **Actual Result with evidence:**
Mentions do not turn blue when writing down the name of another player on the chat box 

##### 🔁 Always - (note)

Image

#### 🖥️ **Operative system and additional Notes:**
This issue happen on both platforms

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #5109 

## What does this PR change?

This PR adds the text formatter to the input field of the chat in order to modify the text color as it behaves in the chat message bubbles. It highlights
- mentions (validated names)
- coordinates (validated)
- urls
- world names

The regex matches are calculated every time the input changes, then on `Rebuild` the text is colored according to the matches.
It is achieved using the mesh data in order to avoid enabling and handling rich text.

### Test Steps
1. Verify that while you are typing a message, the content is highlighted as described above (valid mentions, valid coordinates, urls and world names)
2. The input should highlight the text exactly as in the chat message bubbles

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [x] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/UI/CustomInputField/CustomInputField.cs [hunk 1]
```diff
@@ -35,6 +42,47 @@ public override void OnPointerClick(PointerEventData eventData)
...
+                    Color32[] vertexColors = textComponent.textInfo.meshInfo[meshIndex].colors32;
+                    vertexColors[vertexIndex + 0] = mentionColor;
+                    vertexColors[vertexIndex + 1] = mentionColor;
+                    vertexColors[vertexIndex + 2] = mentionColor;
+                    vertexColors[vertexIndex + 3] = mentionColor;
+                }
+
+            if (inputMatchesInfo.Count > 0)
+                textComponent.UpdateVertexData(TMP_VertexDataUpdateFlags.Colors32);
+        }
```
Comment (Maurizio-dcl) [inline Explorer/Assets/DCL/UI/CustomInputField/CustomInputField.cs:84]: Minor thing here, why accessing the same property chain each time? maybe caching textComponent.textInfo outside the loop and *.characterInfo[i] inside the loop?

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms  following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- [ ✔️] Backpack and wearables in world
- [✔️ ] Emotes in world and in backpack
- [ ✔️] Teleport with map/coordinates/Jump In
- [✔️ ] Chat and multiplayer
- [ ✔️] Profile card
- [✔️ ] Skybox
- [✔️ ] Settings

All points of the PR have been checked ✅ 
- Coordinates 
-Names 
-Urls
-Worlds

**⚠️ As a prod decission only secure links we'll be highlighted so everything that starts with www for example won't only https:// will be suported ⚠️** 

Evidence:

https://github.com/user-attachments/assets/e457799c-991e-470b-aaed-83926d676ac2

image (8)
image (7)
image (6)
Screenshot 2025-09-24 at 10 05 53

[Macos evidence](https://decentralandteam.slack.com/files/U07KP678E1X/F09GQJ0B98T/screen_recording_2025-09-24_at_09.59.40.mov)
