### PR TITLE
fix: Accessing the passport on various players can freeze the UI

### LINKED ISSUE #1676: Accessing the passport on various players can freeze the UI
### **Explorer Alpha build versions:**
v0.19.0

### **Issue Description:**
During the playtest accessing random players passports caused a freeze of the whole UI.

[Clicking on Passport Throws Exceptions.log](https://github.com/user-attachments/files/16529193/Clicking.on.Passport.Throws.Exceptions.log)

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #1676 

During the playtest accessing random players passports caused a freeze of the whole UI.

It could be related to how we cancel the wearables requests when open the passport and then we quickly close it before the requests have finished, so I made all cancellation token sources to be always cancelled and disposed when the passport closes. In this way we ensure that no request is running while the passport is closed.

I also applied some other small fixes.

## How to test the changes?
1. Launch the explorer.
2. Go to a place with several avatars.
3. Click on each avatar to open his passport.
4. Try to do the step 3 changing to another avatars very quickly before the previous one has been loaded.
5. And the end you should check that the app is not freezed in any moment doing this.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by anicalbano — APPROVED** [review]
🟢 Unable to reproduce the issue on QA end. Approving the PR

File: Explorer/Assets/DCL/Passport/Modules/UserBasicInfo_PassportModuleController.cs [hunk 1]
```diff
@@ -69,11 +69,13 @@ public void Setup(Profile profile)
             //CheckForEditionAvailabilityAsync(checkEditionAvailabilityCts.Token).Forget();
         }
 
-        public void Clear() { }
+        public void Clear()
+        {
+            checkEditionAvailabilityCts.SafeCancelAndDispose();
+        }
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Passport/Modules/UserBasicInfo_PassportModuleController.cs:75]: In the clear you can probably put also 
```
view.CopyNameWarningNotification.Hide(true);
view.CopyWalletWarningNotification.Hide(true);
```
Because if you close the passport while they are on they might stay visible once you re open it

**Review by davidejensen — APPROVED** [review]
LGTM, left a small question

File: Explorer/Assets/DCL/Passport/Modules/UserBasicInfo_PassportModuleController.cs (hunk 1 above)
Comment (sandrade-dcl) [reply Explorer/Assets/DCL/Passport/Modules/UserBasicInfo_PassportModuleController.cs:77]: Totally true! Done here: https://github.com/decentraland/unity-explorer/pull/1684/commits/76bea0c17f7c90c9eb24146faca84458d13cd145

**Review by fcolarich — APPROVED** [review]
