### PR TITLE
fix: initial notification read after every successful login

### LINKED ISSUE #2159: [QA] Discord push notifications when switching to a metamask account
### **Explorer Alpha build versions:**
0.29.14

### **Issue Description:**
User is able to see push notifications that aren't from the correct account when logging in with another account. 
We sent push notifications to a discord account and then switched to a metamask account. We saw that the discord notifications appear on the metamask account after switching.  

### **STR:** 

  1. Open postman 
  2. Import the folder from DCL 
  3. Open the post- new reward received 
  4. Copy your discord account and put it on the wallet address to send some push notifications 
  5. Press Send 17 times 
  6. Open build 0.29.14 
  7. Verify that you received 17 push notifications 
  8. Close the build and open it again but now switch accounts to a metamask account one 
  9. Once you open the build again you will be able to see the 17 notifications of discord on a metamask account 

#### **Important comments:**
If you had notifications on the metamask account they will do the summatory between discord and metamask notifications when they should be treated individually 

### **Expected behavior:**
When switching accounts , the notifications should be treated as individual from each account 

### **Current behavior:**
User is able to see push notifications that aren't from the correct account when logging in with another account. 
We sent push notifications to a discord account and then switched to a metamask account. We saw that the discord notifications appear on the metamask account after switching.  

#### **Evidence:**

https://github.com/user-attachments/assets/53556e05-526b-4f80-b0f1-9acb5acb9c13

https://github.com/user-attachments/assets/163fb426-65d7-4d0d-a0ef-4397353db5b5

https://github.com/user-attachments/assets/824a1af1-132c-4f4a-abd7-2a82624c985b

#### **Additional Notes:**
This issue happens on Windows and Mac

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
## What does this PR change?

Fix #2159 

Fetch user notifications every time a new login is made in order to jump in game with the correct notifications loaded 

## How to test the changes?

1. Launch the explorer
2. Login with an account and enter the Explorer
3. Verify which notifications you have
4. Logout
5. Launch the explorer again
6. Login with a different account
7. Enter in game and verify that different notifications are loaded

You can verify the behavior with unread notifications as well.
Refer to [this](https://github.com/decentraland/unity-explorer/pull/2148) PR in order to push new notifications to an account.

1. Push some notifications to an account A
2. Push some notifications to an account B (a different amount than A)
3. Login with account A, enter the Explorer and verify that the number of unread notifications matches with the number of pushed ones
4. Logout
5. Login with account B, enter the Explorer and verify that the number of unread notifications matches with the number of pushed ones (different than A)

For a double check, at the login screen, you can also logout/login multiple times with different accounts and then enter the Explorer verifying that the notifications shown are coherent with the account you choose to enter in game.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs [hunk 1]
```diff
@@ -46,8 +46,8 @@ private static string RawUrl(DecentralandUrl decentralandUrl) =>
                 DecentralandUrl.Host => $"https://decentraland.{ENV}",
                 DecentralandUrl.PeerAbout => $"https://peer.decentraland.{ENV}/about",
                 DecentralandUrl.DAO => $"https://decentraland.{ENV}/dao/",
-                DecentralandUrl.Notification => $"https://notifications.decentraland.{ENV}/notifications",
-                DecentralandUrl.NotificationRead => $"https://notifications.decentraland.{ENV}/notifications/read",
+                DecentralandUrl.Notification => $"https://notifications.decentraland.zone/notifications",
+                DecentralandUrl.NotificationRead => $"https://notifications.decentraland.zone/notifications/read",
```
Comment (sandrade-dcl) [inline Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs:50]: I guess you're currently hardcoding `.zone` here for testing purposes, right? We should change it before going to `main`.
```suggestion
                DecentralandUrl.Notification => $"https://notifications.decentraland.{ENV}/notifications",
                DecentralandUrl.NotificationRead => $"https://notifications.decentraland.{ENV}/notifications/read",
```

File: Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs [hunk 2]
```diff
@@ -113,8 +123,29 @@ private void OnViewShown()
             }
         }
 
-        private async UniTaskVoid InitialNotificationRequestAsync(CancellationToken ct)
+        private async UniTaskVoid CheckIdentityChangeAsync(CancellationToken token)
         {
+            if (previousWeb3Identity != null)
+                await InitialNotificationRequestAsync(token);
+
+            while (token.IsCancellationRequested == false && panelWasOpenedOnce == false)
```
Comment (sandrade-dcl) [inline Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs:131]: Instead of using a while loop here, maybe it's more clear to use `UniTask.WaitUntil`:
```
await UniTask.WaitUntil(() => token.IsCancellationRequested || panelWasOpenedOnce);

if (token.IsCancellationRequested)
    return;
```

**Review by sandrade-dcl — CHANGES_REQUESTED** [review]

File: Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs (hunk 1 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs:50]: yes it's for QA to test and will be reverted as soon as they approve it, as it happened in [this](https://github.com/decentraland/unity-explorer/pull/2148) PR

File: Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs (hunk 2 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs:131]: maybe I'm missing something but here the purpose of the while loop is to cycle every `IDENTITY_CHANGE_POLLING_INTERVAL` (line 139) in order to check the identity change and trigger the logic accordingly.
I am not passively waiting for `panelWasOpenedOnce` (or the cancellation token) in order to proceed, which is how I translate the suggestion

Comment (sandrade-dcl) [reply Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs:131]: Oh sorry, I saw the `while` and I directly though it was a "waiting" loop 👍 Ok, forget my comment!

**Review by davidejensen — APPROVED** [review]

**Review by fcolarich — APPROVED** [review]
Looks good!
