### PR TITLE
fix: Support for multiple NFT chains

### LINKED ISSUE #1475: Goerli | Unclickable NFTs in NFT-Museum (85, -8) and Simple-NFT (82, -1)
### **Explorer Alpha build versions:**

- **v0.13.0**
- **v0.14.0**

### **Issue Description:**
In the Goerli, within the NFT-Museum scene at coordinates (85, -8) and the Simple-NFT scene at coordinates (82, -1), certain NFTs cannot be clicked or interacted with. 

### **STR:** 

1. Use the `/world goerli` command in the chat.
2. Navigate to coordinates (85, -8) in the Goerli NFT-Museum scene.
3. Attempt to click and interact with the NFTs on the second floor of the second level.
4. Navigate to coordinates (82, -1) in the Simple-NFT scene.
5. Attempt to click and interact with various NFTs.

### **Expected behavior:**
All NFTs should be clickable and interactable in both the Goerli NFT-Museum (85, -8) and Simple-NFT (82, -1) scenes.

https://github.com/user-attachments/assets/1c70a302-0fd3-4f74-bc7b-2780f2387fc5

### **Current behavior:**

https://github.com/user-attachments/assets/abe82357-3722-4103-b0c6-c426ed376903

https://github.com/user-attachments/assets/937dd4a6-62fe-47d8-aa97-bcf790438bd7

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #1475 

- This fix adds support for every chain (Ethereum, Matic, etc.) that [OpenSea supports](https://docs.opensea.io/reference/get_nft) to be able to show it in our NFT Dialogs.

image

image

## How to test the changes?
1. Launch the explorer
2. `/goto goerli`
3. Navigate to coordinates (85, -8) in the Goerli NFT-Museum scene.
4. Click on any NFT in the walls (in any floor) and check that they're opening correctly.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by anicalbano — APPROVED** [review]
🟢 Reviewed by QA

https://github.com/user-attachments/assets/ed51c699-962c-4f20-a52d-ee0093b646cd

**Opened links example;**

https://github.com/user-attachments/assets/0f1e7dda-8dde-4395-9996-bfe86bd27c06

File: Explorer/Assets/DCL/Utilities/NftUtils.cs [hunk 1]
```diff
@@ -23,27 +24,36 @@ public static bool TryParseUrn(URN urn, out string contractAddress, out string t
...
 
                 // 3: contract standard
                 var contractStandardSpan = urnSpan.Slice(0, urnSpan.IndexOf(SEPARATOR));
                 urnSpan = urnSpan.Slice(contractStandardSpan.Length + 1);
 
-                // 4: contract address
-                var contractAddressSpan = urnSpan.Slice(0, urnSpan.IndexOf(SEPARATOR));
-                urnSpan = urnSpan.Slice(contractAddressSpan.Length + 1);
+                // check if wearables is third-party
+                if (contractStandardSpan.ToString().Equals(COLLECTIONS_THIRDPARTY, StringComparison.Ordinal))
```
Comment (m3taphysics) [inline Explorer/Assets/DCL/Utilities/NftUtils.cs:36]: Is there a better way here of utilizing the span to not call ToString everywhere and allocate memory each time we parse a URN? It could be a hotpath.

**Review by m3taphysics — CHANGES_REQUESTED** [review]

File: Explorer/Assets/DCL/Utilities/NftUtils.cs (hunk 1 above)
Comment (sandrade-dcl) [reply Explorer/Assets/DCL/Utilities/NftUtils.cs]: You're completely right, there was a better way to do it without having to allocate new memory.
Changes done here: https://github.com/decentraland/unity-explorer/pull/1533/commits/70a2c6aa2bbe136c2a15b1c3c53487441f8c96c2

**Review by pravusjif — APPROVED** [review]
LGTM!

**Review by m3taphysics — APPROVED** [review]
Perfecto!
