### PR TITLE
[SHAPE-UP] Communities (Creation Wizard polishments)

### LINKED ISSUE #4561: Places dropdown improvements in Community creation/edition wizard

### LINKED ISSUE #4589: Show/hide the char counter when focus/unfocus the inputs in the Creation Wizard

### LINKED ISSUE #4591: Give 2 separated error messages when we select a wrong image file in the Creation Wizard

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# Pull Request Description

## What does this PR change?
- Fix #4591
- Fix #4589
- Fix #4561

#### FIX 1: "Give 2 separated error messages when we select a wrong image file"
1. Open the creation wizard.
2. Try to select an image with a size bigger that 512x512.
3. Observe you will receive an error message specific for this: "_Selected image exceeds 512x512 px size limit_"
4. Try to select an image with a weight bigger than 500KB.
5. Observe you will receive an error message specific for this: "_Selected image exceeds 500KB size limit_"
6. Try to select an image with a size bigger that 512x512 and a weight bigger than 500KB.
7. Observe you will receive an error message specific for this: "_Invalid image file selected. Please check file type and size._"

#### FIX 2: "Show/hide the char counter when focus/unfocus the inputs"
1. Open the creation wizard.
2. Observe the title input and the description input don't have any outline nor character counter visible.
3. Click and put the focus on each input.
4. Check that the corresponding outline and character counter appear.
5. Click out of the inputs.
6. Check that the corresponding outline and character counter hide.

#### FIX 3: "Places dropdown improvements"
1. Open the creation wizard.
2. Observe that the Places selector has a new design: We don't have the [ADD] button anymore, you only need to open the selector and click on any place or world to add it as a tag below.
3. Once you added tag of the place or world, check that this place or world dissapeared from the selector.
4. Remove one of the added tags and check that the this place or world appears again in the selector.

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs [hunk 1]
```diff
@@ -152,6 +146,20 @@ protected override UniTask WaitForCloseIntentAsync(CancellationToken ct) =>
                 viewInstance!.backgroundCloseButton.OnClickAsync(ct),
                 closeTaskCompletionSource.Task);
 
+        private async UniTask LoadPanelAsync(CancellationToken ct)
+        {
+            viewInstance!.SetCreationPanelAsLoading(true);
+            await LoadLandsAndWorldsAsync(ct) .SuppressToResultAsync(ReportCategory.COMMUNITIES);
```
Comment (lorenzo-ranciaffi) [inline Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs:152]: OCD triggering white space 😆

**Review by lorenzo-ranciaffi — APPROVED** [review]
LGTM

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:


- All points have been checked in both platforms ! ✅ 

Evidence:

https://github.com/user-attachments/assets/bfc47d07-43e7-4220-8c06-6ebf1a94ba3f

image
image (1)
