### PR TITLE
fix: prevent map zoom when floating panel is opened

### LINKED ISSUE #2284: [QA] Map | Having any modal that requires a zoom over the map makes the map zoom in and out
### **Explorer Alpha build versions:**
0.29.0

### **Issue Description:**
Scrolling with the map open but over a modal makes the map zoom in and out

### **STR:** 

  1. Open 0.29.0
  2. Open the map 
  3. Select a point 
  4. Scroll up or down 

### **Expected behavior:**
The map should not scroll when there's a point selected. The text of the point selected should be scrollable instead of the map

### **Current behavior:**
Scrolling with the map open but over a modal makes the map zoom in and out

#### **Evidence:**

https://github.com/user-attachments/assets/cad89a6c-0767-47a7-9014-ff7a2529b9c4

#### **Additional Notes:**
Windows 11 pro 
16 GB RAM

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
## What does this PR change?

Fix #2284 

Prevent the execution of the map zoom if the cursor is on top of the floating panel for the Jump In destination

## How to test the changes?

1. Launch the explorer
2. Open the map
3. Scroll and check that map zooms in/out
4. Click on any point of the map
5. Hover with the mouse on the panel to Jump In
6. Scroll the mouse wheel and check that the map doesn't zooms in/out and only the modal does
7. Hover with the mouse in the map
8. Scroll the mouse wheel and check that the map zooms in/out

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/Navmap/NavmapZoomController.cs [hunk 1]
```diff
@@ -55,6 +56,9 @@ public void Dispose()
             cts.SafeCancelAndDispose();
         }
 
+        public void SetBlockZoom(bool value) =>
```
Comment (m3taphysics) [inline Explorer/Assets/DCL/Navmap/NavmapZoomController.cs:59]: Any reason this is preferred over a simple getter?

**Review by m3taphysics — CHANGES_REQUESTED** [review]

File: Explorer/Assets/DCL/Navmap/NavmapZoomController.cs (hunk 1 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Navmap/NavmapZoomController.cs:59]: there's no need for a public/private getter since the `blockZoom` variable is only used internally. The only need is to set its value externally (from the `FloatingPanelController`)

**Review by DafGreco — APPROVED** [review]
Verified on Windows and MacOs ✅

**Review by anicalbano — APPROVED** [review]

File: Explorer/Assets/DCL/Navmap/FloatingPanelView.cs [hunk 2]
```diff
@@ -99,5 +100,14 @@ public class FloatingPanelView : MonoBehaviour
         [field: Header("Audio")]
         [field: SerializeField]
         public AudioClipConfig OnShowAudio { get; private set; }
+
+        internal UnityAction? onPointerEnterAction;
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Navmap/FloatingPanelView.cs:104]: I'd prefer the usage of generic C# system actions instead of the Unity re-inplementation

**Review by davidejensen — APPROVED** [review]
