### PR TITLE
fix: improve connection lost management on loading process 

### LINKED ISSUE #4705: Add a 'No Internet Connection' on startup message
### Description

There is no clear `No Internet Connection` message or `Connectivity Problems` for startup. 

After this [PR](https://github.com/decentraland/unity-explorer/pull/4662), the livekit one is gonna hold the initialization. But the message could be clearer, showing that real reason is the lack of internet or connection problems.

### Deliverables

- On startup ensure that the connection flow correctly displays an invalid connection dialog, with potential retryability.
- Ensure that a disconnected internet works
- Ensure that invalid/broken endpoint works i.e. failure in livekit and other critical endpoints.

### LINKED ISSUE #4935: [QA] Connectivity | User has multiple issues with the teleport when gaining and losing connection
### 🛠️ **Build version:**
0.82

### 📔 **Issue Description:**
User is unable to teleport anymore after losing and gaining connection multiple times and a message is received on the chat :

### 👣 **STR:** 

  1. Open DCL 0.82
  2. Check that you appear on genesis plaza 
  3. Disconnect from wifi 
  4. Attempt to teleport through a jump in button
  5. Re-connect wifi 
  6. Attempt step 3 and 4 two more times 
  7. Check that you will receive a message on the chat that the teleport action failed 
  8. Recover internet connection fully 
  9. Check that the user is unable to telepor anymore through command or jump in button

### ✔️ **Expected Result:**
User should receive a modal letting them know that they are having internet issues 

### ❌ **Actual Result with evidence:**
User is unable to teleport anymore after losing and gaining connection multiple times

Evidence:
**Logs**

[Player.log](https://github.com/user-attachments/files/21551386/Player.log)

VIDEO:

https://github.com/user-attachments/assets/0157d15d-0a1b-40a2-8158-6f049981c930

##### 🔁 Always - (note)
10/10 Following the STR above 

#### 🖥️ **Operative system and additional Notes:**
This issue happens on both platforms 

Message that appears on the chat of DCL :
Image

### LINKED ISSUE #5096: [QA] Login | User stuck at 73% due to network timeout
### 🛠️ **Build version:**
- **v0.84.0**

### 📔 **Issue Description:**
User is unable to log in, stuck at 73% during initial scene load. Logs suggest a **network timeout** rather than a shader/Metal-specific issue. This may cause the client to hang while waiting for assets to load.

📝 LOGS: [Player-Kim-Logs.log](https://github.com/user-attachments/files/21835215/Player-Kim-Logs.log)

### 👣 **STR:** 
1. Attempt to log in.  
2. Observe loading progress reaching 73%.  
3. Client remains stuck without completing login.

### ✔️ **Expected Result:**
User should be able to log in and load the scene successfully without being stuck.

### ❌ **Actual Result with evidence:**
User gets stuck at 73% during scene load due to a network timeout.  
Logs indicate waiting for assets but no progress is made.  

### ➗ **Reproduction:**
⚠️ Intermittent – issue reproduced after multiple login attempts, resolved after retrying 4 times.

#### 🖥️ **Operative system and additional Notes:**
- macOS M1 Pro  
- Reported by user Kim Currier  
- Network conditions may play a role (possible unstable WiFi connection).  
- Related to similar cases seen in Sentry for users in different regions.

### LINKED ISSUE #5329: [QA] Teleport loading screen | When internet connection is re-established and user teleports the app crashes
### 🛠️ **Build version:**
v0.88.0

### 📔 **Issue Description:**
Teleporting after the internet connection reestablishes causes the app to crash

### 👣 **STR:** 

  1. While on any scene, disconnect from the internet and wait 5-10 minutes.
  2. Re-establish the internet connection and teleport to any scene

### ✔️ **Expected Result:**
The loading screen to complete and user to teleport to the desired scene

### ❌ **Actual Result with evidence:**
The loading screen gets stuck at 0% and the app stops responding until it closes/crashes.

https://github.com/user-attachments/assets/b55c81c8-c972-4f61-a293-d288e9210c7e

Logs:

[log 1.zip](https://github.com/user-attachments/files/22242835/log.1.zip)
[log 2.zip](https://github.com/user-attachments/files/22242834/log.2.zip)

##### 🔁 Always - (note)
I was able to reproduce this issue twice, but I noticed that if the disconnection is for a very short time, this issue is not reproducible.

#### 🖥️ **Operative system and additional Notes:**

Windows 11 Home build 10.0.22631
This was also reproducible on Mac M1

### LINKED ISSUE #5574: [QA] Loading | Losing connection while teleporting does not show a timeout error
### 🛠️ **Build version:**
Dev and Prod

### 📔 **Issue Description:**

If you lose the internet connection while teleporting, since the target scene may have already been loaded, user is teleported anyway, but if they attempt to teleport to a different location it's not possible, and an error message shows in the nearby chat.

### 👣 **STR:** 

  1. Login
  2. Teleport to any scene
  3. While teleporting, disconnect from the internet
  4. The user will teleport but no user will be seen since user is offline
  5. Attempt to teleport to somewhere else

### ✔️ **Expected Result:**

- Get timeout error message
- Retry to login and when internet connection is reestablished. to be able to enter client

### ❌ **Actual Result with evidence:**

Image

https://github.com/user-attachments/assets/284beeee-633e-4870-8bbb-16f681346343

Chat log error:

[chat log error.txt](https://github.com/user-attachments/files/22543108/chat.log.error.txt)

`
🔴 Error: Unhandled exception on Teleporting to Parcel attempt 1/1: System.Exception: Exception occured on loading DCL.Ipfs.SceneDefinitions from ECS.SceneLifeCycle.SceneDefinition.GetSceneDefinitionList with url https://asset-bundle-registry.decentraland.org/entities/active.
No more sources left. ---> Cysharp.Threading.Tasks.UnityWebRequestException: Cannot resolve destination host
  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:859 
  at Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:312 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:36 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:218 
  at Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:312 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:74 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:127 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.WebRequests.DebugMetricsWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs:28 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.WebRequests.LogWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/LogWebRequestController.cs:29 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.DebugMetricsWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs:34 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.WebRequests.ArtificialDelayWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/ArtificialDelayWebRequestController.cs:31 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.LogWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/LogWebRequestController.cs:36 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.DebugMetricsWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs:34 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.WebRequests.BudgetedWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/BudgetedWebRequestController.cs:33 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.ArtificialDelayWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/ArtificialDelayWebRequestController.cs:31 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.LogWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/LogWebRequestController.cs:36 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.DebugMetricsWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs:34 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at ECS.SceneLifeCycle.SceneDefinition.LoadSceneDefinitionListSystem.FlowInternalAsync (ECS.SceneLifeCycle.SceneDefinition.GetSceneDefinitionList intention, ECS.StreamableLoading.Common.Components.StreamableLoadingState state, ECS.Prioritization.Components.IPartitionComponent partition, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionListSystem.cs:81 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.BudgetedWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/BudgetedWebRequestController.cs:33 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.ArtificialDelayWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/ArtificialDelayWebRequestController.cs:31 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.LogWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/LogWebRequestController.cs:36 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.DebugMetricsWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs:34 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at ECS.StreamableLoading.Common.Systems.AssetsLoadingUtility.RepeatLoopAsync[TIntention,TState,TAsset] (TIntention intention, TState state, ECS.Prioritization.Components.IPartitionComponent partition, ECS.StreamableLoading.Common.Systems.AssetsLoadingUtility+InternalFlowDelegate`3[TAsset,TState,TIntention] flow, DCL.Diagnostics.ReportData reportData, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/Systems/AssetsLoadingUtility.cs:39 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at ECS.SceneLifeCycle.SceneDefinition.LoadSceneDefinitionListSystem.FlowInternalAsync (ECS.SceneLifeCycle.SceneDefinition.GetSceneDefinitionList intention, ECS.StreamableLoading.Common.Components.StreamableLoadingState state, ECS.Prioritization.Components.IPartitionComponent partition, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionListSystem.cs:116 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.BudgetedWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/BudgetedWebRequestController.cs:33 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.ArtificialDelayWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/ArtificialDelayWebRequestController.cs:31 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.LogWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/LogWebRequestController.cs:36 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.DebugMetricsWebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs:34 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.WebRequestController.SendAsync[TWebRequest,TWebRequestArgs,TWebRequestOp,TResult] (DCL.WebRequests.RequestEnvelope`2[TWebRequest,TWebRequestArgs] envelope, TWebRequestOp op) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions.WithAnalyticsAsync[T] (T request, DCL.WebRequests.Analytics.IWebRequestsAnalyticsContainer analyticsContainer, Cysharp.Threading.Tasks.UniTask innerTask) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/Analytics/IWebRequestsAnalyticsContainer.cs:37 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:189 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UnityAsyncExtensions.cs:905 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:203 
   --- End of inner exception stack trace ---
  at ECS.StreamableLoading.Common.Systems.AssetsLoadingUtility.UnwrapAndRethrow[TAsset] (System.Nullable`1[ECS.StreamableLoading.Common.Components.StreamableLoadingResult`1[TAsset]]& loadingResult) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/Systems/AssetsLoadingUtility.cs:91 
  at DCL.RealmNavigation.RetrieveSceneFromVolatileWorld.ByParcelAsync (UnityEngine.Vector2Int parcel, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/RetrieveSceneFromVolatileWorld.cs:51 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:328 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1[T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:201 
  at ECS.StreamableLoading.Common.AssetPromiseAsyncExtensions.ToUniTaskAsync[TAsset,TLoadingIntention] (ECS.StreamableLoading.Common.AssetPromise`2[TAsset,TLoadingIntention] promise, Arch.Core.World world, Cysharp.Threading.Tasks.PlayerLoopTiming playerLoopTiming, System.Threading.CancellationToken cancellationToken) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/AssetPromiseAsyncExtensions.cs:25 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UniTask+YieldPromise.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.Delay.cs:251 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:175 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.RealmNavigation.TeleportController.TeleportAsync (UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct, System.Boolean nullifySceneDef) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/TeleportController.cs:79 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.RetrieveSceneFromVolatileWorld.ByParcelAsync (UnityEngine.Vector2Int parcel, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/RetrieveSceneFromVolatileWorld.cs:53 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:328 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1[T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:201 
  at ECS.StreamableLoading.Common.AssetPromiseAsyncExtensions.ToUniTaskAsync[TAsset,TLoadingIntention] (ECS.StreamableLoading.Common.AssetPromise`2[TAsset,TLoadingIntention] promise, Arch.Core.World world, Cysharp.Threading.Tasks.PlayerLoopTiming playerLoopTiming, System.Threading.CancellationToken cancellationToken) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/AssetPromiseAsyncExtensions.cs:25 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UniTask+YieldPromise.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.Delay.cs:251 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:175 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.RealmNavigation.TeleportControllerExtensions.TryTeleportToSceneSpawnPointAsync (DCL.RealmNavigation.ITeleportController teleportController, UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/ITeleportController.cs:23 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.TeleportController.TeleportAsync (UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct, System.Boolean nullifySceneDef) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/TeleportController.cs:99 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.RetrieveSceneFromVolatileWorld.ByParcelAsync (UnityEngine.Vector2Int parcel, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/RetrieveSceneFromVolatileWorld.cs:53 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:328 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1[T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:201 
  at ECS.StreamableLoading.Common.AssetPromiseAsyncExtensions.ToUniTaskAsync[TAsset,TLoadingIntention] (ECS.StreamableLoading.Common.AssetPromise`2[TAsset,TLoadingIntention] promise, Arch.Core.World world, Cysharp.Threading.Tasks.PlayerLoopTiming playerLoopTiming, System.Threading.CancellationToken cancellationToken) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/AssetPromiseAsyncExtensions.cs:25 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UniTask+YieldPromise.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.Delay.cs:251 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:175 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.RealmNavigation.TeleportOperations.MoveToParcelInSameRealmTeleportOperation.ExecuteAsync (DCL.RealmNavigation.TeleportOperations.TeleportParams args, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/TeleportOperations/MoveToParcelInSameRealmTeleportOperation.cs:23 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.TeleportControllerExtensions.TryTeleportToSceneSpawnPointAsync (DCL.RealmNavigation.ITeleportController teleportController, UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/ITeleportController.cs:24 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.TeleportController.TeleportAsync (UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct, System.Boolean nullifySceneDef) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/TeleportController.cs:99 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.RetrieveSceneFromVolatileWorld.ByParcelAsync (UnityEngine.Vector2Int parcel, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/RetrieveSceneFromVolatileWorld.cs:53 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:328 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1[T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:201 
  at ECS.StreamableLoading.Common.AssetPromiseAsyncExtensions.ToUniTaskAsync[TAsset,TLoadingIntention] (ECS.StreamableLoading.Common.AssetPromise`2[TAsset,TLoadingIntention] promise, Arch.Core.World world, Cysharp.Threading.Tasks.PlayerLoopTiming playerLoopTiming, System.Threading.CancellationToken cancellationToken) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/AssetPromiseAsyncExtensions.cs:25 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UniTask+YieldPromise.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.Delay.cs:251 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:175 
--- End of stack trace from previous location where exception was thrown ---

  at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTaskCompletionSource.cs:244 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:342 
  at Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.cs:653 
  at DCL.RealmNavigation.LoadingOperation.SequentialLoadingOperation`1[TParams].ExecuteAsync (System.String processName, System.Int32 attemptsCount, TParams args, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/LoadingOperation/SequentialLoadingOperation.cs:54 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.TeleportOperations.MoveToParcelInSameRealmTeleportOperation.ExecuteAsync (DCL.RealmNavigation.TeleportOperations.TeleportParams args, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/TeleportOperations/MoveToParcelInSameRealmTeleportOperation.cs:34 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.TeleportControllerExtensions.TryTeleportToSceneSpawnPointAsync (DCL.RealmNavigation.ITeleportController teleportController, UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/ITeleportController.cs:24 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.TeleportController.TeleportAsync (UnityEngine.Vector2Int parcel, DCL.Utilities.AsyncLoadProcessReport loadReport, System.Threading.CancellationToken ct, System.Boolean nullifySceneDef) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/TeleportController.cs:99 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at DCL.RealmNavigation.RetrieveSceneFromVolatileWorld.ByParcelAsync (UnityEngine.Vector2Int parcel, System.Threading.CancellationToken ct) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/RealmNavigation/RetrieveSceneFromVolatileWorld.cs:53 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:328 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1[T].SetResult (T result) [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:201 
  at ECS.StreamableLoading.Common.AssetPromiseAsyncExtensions.ToUniTaskAsync[TAsset,TLoadingIntention] (ECS.StreamableLoading.Common.AssetPromise`2[TAsset,TLoadingIntention] promise, Arch.Core.World world, Cysharp.Threading.Tasks.PlayerLoopTiming playerLoopTiming, System.Threading.CancellationToken cancellationToken) [0x00000] in C:/workspace/workspace/p/Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Common/AssetPromiseAsyncExtensions.cs:25 
  at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].Run () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/CompilerServices/StateMachineRunner.cs:313 
  at Unity.Mathematics.math.min (System.Int32 x, System.Int32 y) [0x00000] in ./Library/PackageCache/com.unity.mathematics@8017b507cc74/Unity.Mathematics/math.cs:855 
  at Cysharp.Threading.Tasks.UniTask+YieldPromise.MoveNext () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/UniTask.Delay.cs:251 
  at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore () [0x00000] in ./Library/PackageCache/com.cysharp.unitask@f026e068eaed/Runtime/Internal/PlayerLoopRunner.cs:175 
`

Logs:

[Player.log](https://github.com/user-attachments/files/22542755/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/22542754/Player-prev.log)

[more logs.zip](https://github.com/user-attachments/files/22543049/more.logs.zip)

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #4705 
Fixes #5329 
Fixes #5574 
Fixes #4935 
Fixes #5096 

Arranges a better handling of the timeout errors and displays the message accordingly. A new popup has been implemented to retry the operation. Additionally fixes some unhandled exceptions.
Losing internet connection makes the client very unstable. The scope is too large to fix them all, but this changes should improve the loading/teleport operations.

## Test Instructions

Disable internet connection during initial loading. Check that a new popup shows describing connection problems. Wait a while until the error is displayed (sometimes more than 1 minute).
Once you are in world, perform a teleport through /goto or the navmap and disable the internet. Check that an error in the chat is displayed about connection problems. The app should not crash in the process.

The client will still be unstable when you lose internet. You can expect things to be broken. Results can vary depending on the exact moment that you disable the internet.

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/UI/ErrorPopup/ErrorPopupWithRetryController.cs [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+            ERROR,
+            CONNECTION_LOST,
+        }
+
+        public class Input
+        {
+            /// <summary>
+            /// Out value
+            /// </summary>
+            public Result SelectedOption;
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/UI/ErrorPopup/ErrorPopupWithRetryController.cs]: I see why you need a class but writing output to Input is such a hack 😬 . Let's think how to do it properly

File: Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs [hunk 2]
```diff
@@ -301,6 +301,39 @@ await bootstrap.InitializeFeatureFlagsAsync(bootstrapContainer.IdentityCache!.Id
...
+
+            async UniTask LoadStartingRealmAsync(CancellationToken ct)
+            {
+                try { await bootstrap.LoadStartingRealmAsync(dynamicWorldContainer!, ct); }
+                catch (RealmChangeException)
+                {
+                    if (await ShowLoadErrorPopupAsync(ct) == ErrorPopupWithRetryController.Result.RESTART)
+                        await LoadStartingRealmAsync(ct);
+                    else
+                        throw;
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs]: Considering that you are aiming at making the flow "proper", throwing an exception is not an exit. Consider making the flow graceful - if the result is exit, then you should "exit" the app, not making it "dead"

File: Explorer/Assets/DCL/RealmNavigation/TeleportOperations/RemoveUnfinishedScenesTeleportOperation.cs [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+    public class RemoveUnfinishedScenesTeleportOperation : TeleportOperationBase
+    {
+        private readonly World world;
+
+        public RemoveUnfinishedScenesTeleportOperation(World world)
+        {
+            this.world = world;
+        }
+
+        protected override async UniTask InternalExecuteAsync(TeleportParams args, CancellationToken ct)
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/RealmNavigation/TeleportOperations/RemoveUnfinishedScenesTeleportOperation.cs]: `async` is redundant, the method is not async

File: Explorer/Assets/DCL/Social/WebSocketRpcTransport.cs [hunk 4]
```diff
@@ -89,7 +89,18 @@ async UniTaskVoid ListenAndProcessIncomingDataAsync(CancellationToken ct)
...
-                    catch (WebSocketException e) { OnErrorEvent?.Invoke(e); }
+                    catch (OperationCanceledException) { break; }
+                    catch (WebSocketException e)
+                    {
+                        OnErrorEvent?.Invoke(e);
+                        break;
+                    }
+                    catch (Exception e)
+                    {
+                        ReportHub.LogException(e, ReportCategory.FRIENDS);
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/Social/WebSocketRpcTransport.cs]: It should not be `FRIENDS` category the transport relates to the general social features. If there is no suitable category you can pass one to the constructor of the transport from the consumer

File: Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs (hunk 2 above)
Comment (lorux0) [reply Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs]: Done here: https://github.com/decentraland/unity-explorer/pull/5683/commits/311eda86f84149ea3fcd7d6a40632ae336e94961
