### PR TITLE
fix: scene ui parenting crash

### LINKED ISSUE #1089: goerli: clicking on an asset more than once makes the client crash
### **Explorer Alpha build version:**
**0.3.402-g7a23dc7e-main**

### **Issue Description:**

`/goto 72,-1` and start clicking the boxes. When reaching the last one labelled "complex example", click it multiple times, more and more coins will appear until the app crashes.

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/e02c816e-98f5-4ec3-893f-54117b0f721c

#### **Additional Notes:**

[Player.log](https://github.com/decentraland/unity-explorer/files/15298743/Player.log)

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #1089 

The UI system was performing parenting operations on entities that didnt have any `UITransformComponent`. The scene UI gets broken tho, but we avoid the client crash.

## How to test the changes?

1. Follow issue steps
2. Check that the UI on other scenes keeps working

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UITransform/UITransformParentingSystem.cs [hunk 1]
```diff
@@ -43,7 +43,14 @@ private void OrphanChildrenOfDeletedEntity(ref UITransformComponent uiTransformC
 
             foreach (EntityReference childEntity in children)
             {
-                ref var uiTransform = ref World.Get<UITransformComponent>(childEntity.Entity);
+                ref UITransformComponent uiTransform = ref World.TryGetRef<UITransformComponent>(childEntity.Entity, out bool exists);
+
+                if (!exists)
+                {
+                    ReportHub.LogError(GetReportCategory(), $"Trying to remove an ${nameof(UITransformComponent)}'s child but no component has been found on entity {childEntity.Entity}");
```
Comment (sandrade-dcl) [inline Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UITransform/UITransformParentingSystem.cs:50]: I would change the error description to something like: "Trying to unparent an ${nameof(UITransformComponent)}'s child but no component has been found on entity {childEntity.Entity}"

**Review by sandrade-dcl — APPROVED** [review]

**Review by anicalbano — APPROVED** [review]
🟢 Reviewed by QA

https://github.com/decentraland/unity-explorer/assets/139157886/0176beb6-fd7a-492f-940f-d762c905b4d0
