### PR TITLE
fix: profile persistence after login with new account

### LINKED ISSUE #6930: [QA] Email OTP | Desync between accounts logged in and out
### 🛠️ **Build version:**
[https://github.com/decentraland/unity-explorer/pull/6738](https://github.com/decentraland/unity-explorer/pull/6738)

### 📔 **Issue Description:**
When logging in with an old account created by OTP and create a new one to log in , the app logs the previous account instead of the new one created 

### 👣 **STR:** 

  1. Log in with an old email (account A)
  2. Log out from the log out button
  3. Log in with a brand new email (account B)
  4. Make your avatar 
  5. Check that once you enter the app the previous account (account A) is logged instead of account B 

### ✔️ **Expected Result:**
The logged account should be the one appearing in game 

### ❌ **Actual Result with evidence:**
Desync between accounts logged in and out 

##### ⚠️ Intermittent - 5/10

https://github.com/user-attachments/assets/89407012-ed1e-45d7-86d6-4e895a746081

#### 🖥️ **Operative system and additional Notes:**
This happened in both platforms

### LINKED ISSUE #7748: [QA] Login | Avatar of previous session persists instead of the avatar of the new user
### 🛠️ **Build version:**
v0.134.0

### 📔 **Issue Description:**

When you log out an existing account and then login with a new account, the user profile and avatar are populated with the previously logged user and not with the new user.
this is not reproduced if you log out an existing user and then login with another existing user. Only is reproduced so far with a new user.

### 👣 **STR:** 

  1. login with an existing user
  2. log out
  3. log in as a new user. I tested with email + OTP

### ✔️ **Expected Result:**

When logging in with a new user, the new user's name and avatar should display

### ❌ **Actual Result with evidence:**

https://github.com/user-attachments/assets/fa976009-92f5-47e3-9971-99b95b7273a2

[Player-prev.log](https://github.com/user-attachments/files/26192678/Player-prev.log)
[Player.log](https://github.com/user-attachments/files/26192677/Player.log)

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #7748 
Fixes #6930 

## What does this PR change?

This PR makes sure that everything profile-related to the previous session is updated with the newly created account after login.
- `isDirty` flag reset so that the in-world avatar is the new one rather than the previous session's one
- profile update propagated after the new profile creation so that other UIs can react (e.g. sidebar profile widget and panel)

### Test Steps
1. Login with an existing account
2. Enter in world and logout
3. Login with a brand new account (very fast with email+otp using the `+` trick -> test@mail.com becomes test+123@mail.com and is treated as a new account but the otp is sent to the original)
4. Verify that the shown avatar is the new one and not the previous session's

### Additional Testing Notes
- Check the repro steps in the 2 linked issues if I have missed any other test cases

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Branch & PR Standards](../docs/branch-and-pr-standards.md) before submitting. It explains the automated review flow, QA/DEV approval requirements, and what each label does — especially useful for first-time contributors.

### CODE REVIEW

**Review by Ludmilafantaniella — APPROVED** [review]
Verified on Windows and Mac. Logged in with an existing account, entered the world, logged out, then logged in with a brand new account using the + trick. The new account's avatar and profile display correctly — no persistence of the previous session's avatar or profile data. Also confirmed the sidebar profile widget and panel update correctly with the new account. ✅

https://github.com/user-attachments/assets/a26a9b46-e6c5-4595-9b48-a49932efd66a

✅ Sanity check performed:
- ✔️ Backpack and wearables in world
- ✔️ Emotes in world and in backpack
- ✔️ Teleport with map/coordinates/Jump In
- ✔️ Chat and multiplayer
- ✔️ Profile card
- ✔️ Camera
- ✔️ Skybox

File: Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs [hunk 1]
```diff
@@ -352,21 +343,6 @@ private async UniTaskVoid CheckForCommunitiesFeatureAsync(CancellationToken ct)
             viewInstance?.communitiesButton.gameObject.SetActive(includeCommunities);
         }
 
-        private async UniTaskVoid FillLiveEventsAsync(CancellationToken ct)
```
Comment (davidejensen) [inline Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs:355]: Why did you remove this? I se it was not called, but is the events counter handled somewhere else? could it be that the call to this was lost in some conflict resolve?

**Review by davidejensen — CHANGES_REQUESTED** [review]

**Review by davidejensen — APPROVED** [review]

File: Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs (hunk 1 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs:355]: the method call was wrongly removed in the shared space manager PR. I have restored the method and the call: the counter should work again now
