### PR TITLE
Fix: add mouse sensitivity settings in menu

### LINKED ISSUE #2196: Add mouse sensitivity sliders
Different input devices like mouse, trackpads or ball mouse have different DPIs, that may also be affected by the operative system (windows / mac). As we cant default it to each one, lets throw a couple of sliders for people to customize it:

In settings, under a new "Controls" section, add 2 sliders:
- Vertical mouse sensitivity
- Horizontal mouse sensitivity

This values will range from 0.1 to 2, being defaulted on 1. 

This is an additive value on top of the default sensitivity value.

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
## What does this PR change?

Fix #2196 

Adds two sliders in the "Control" portion of the settings menu in order to calibrate the horizontal/vertical mouse sensitivity

## How to test the changes?

1. Launch the explorer
2. Open the explore panel
3. Go to Settings-> Controls and modify the slider values
4. Check whether it affects the camera movements sensitivity
5. Logout
6. Re-launch the explorer
7. Check whether the mouse sensitivity values are loaded according to the previous run and they are applied to the camera movement

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by sandrade-dcl — APPROVED** [review]
LGTM!

**Review by anicalbano — APPROVED** [review]
🟢 Verified also on Windows, the sensitivity works as expected, even changing the values separatedly. By logging out and in, the values don't change. 
Also, the smoke test on Windows was the same as on Mac:

✔️ Backpack
✔️ Emotes
✔️ Nav bar
✔️ Badges
✔️ Map navigation
✔️ Scenes

No issues were introduced on this PR

File: Explorer/Assets/DCL/Settings/ModuleControllers/MouseHorizontalSensitivitySettingsController.cs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+        private void SetHorizontalMouseSensitivity(float sensitivity)
+        {
+            controlsSettingsAsset.HorizontalMouseSensitivity = sensitivity;
+            settingsDataStore.SetSliderValue(HORIZONTAL_MOUSE_SENSITIVITY_DATA_STORE_KEY, sensitivity, save: true);
+        }
+
+        public override void Dispose()
+        {
+            view.SliderView.Slider.onValueChanged.RemoveListener(SetHorizontalMouseSensitivity);
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Settings/ModuleControllers/MouseHorizontalSensitivitySettingsController.cs:33]: Generally you can add one single remove in the dispose with RemoveAllListeners, so in case you add more listeners in the future you are sure that they are all removed properly here without adding new code

File: Explorer/Assets/DCL/Settings/ModuleControllers/MouseVerticalSensitivitySettingsController.cs [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+        private void SetVerticalMouseSensitivity(float sensitivity)
+        {
+            controlsSettingsAsset.VerticalMouseSensitivity = sensitivity;
+            settingsDataStore.SetSliderValue(VERTICAL_MOUSE_SENSITIVITY_DATA_STORE_KEY, sensitivity, save: true);
+        }
+
+        public override void Dispose()
+        {
+            view.SliderView.Slider.onValueChanged.RemoveListener(SetVerticalMouseSensitivity);
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Settings/ModuleControllers/MouseVerticalSensitivitySettingsController.cs:33]: same as before

**Review by davidejensen — APPROVED** [review]
Approved with minor suggestion
