### PR TITLE
fix: scene account switch

### LINKED ISSUE #1187: [QA] Metadynelabs: Avatar Stuck After Account Switch
### **Explorer Alpha build version:**

- **0.3.463-gf5b67b0c-main**
- **v0.11.0**

### **Issue Description:**
an issue was encountered when switching accounts to access level 02 due to the levels carousel not functioning. Upon logging in with a different account, the avatar became stuck, displaying only the head. This problem occurs specifically after switching accounts, but it can be resolved by traveling to another location and then returning.

### **Steps to reproduce:**

1. /goto metadynelabs
2. Log out of the current account.
3. Log in with a different account.
4. Observe the avatar upon logging in.

### **Expected behavior:**
The avatar should be fully visible and functional after switching accounts.

### **Current behavior:**

https://github.com/decentraland/unity-explorer/assets/146741383/fda85779-4b7b-4d5d-b570-876d79d7f7e5

### **Platforms / OS:**
- [❌] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #1187 

The fix consists on destroy all the current scenes and also restart the realm, so the next time the world is loaded, all the scenes can be created from scratch.
Also, a refactor has been made over the realm classes to reduce coupling and cyclic dependencies limitations.

## How to test the changes?

1. Follow issue steps
2. After re-authenticating the scene should load normally
3. Check that the /reload command still works

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/ExplorePanel/SystemMenuController.cs [hunk 1]
```diff
@@ -111,9 +115,13 @@ private void Logout()
             async UniTaskVoid LogoutAsync(CancellationToken ct)
             {
                 Web3Address address = web3IdentityCache.Identity!.Address;
+
                 await web3Authenticator.LogoutAsync(ct);
+
                 profileCache.Remove(address);
-                await userInAppInitializationFlow.ExecuteAsync(true, true, world, playerEntity, ct);
+
+                await unloadAllScenes.ExecuteAsync(ct);
```
Comment (lorux0) [inline Explorer/Assets/DCL/ExplorePanel/SystemMenuController.cs:123]: Should i move this call inside `userInAppInitializationFlow.ExecuteAsync(...)` by passing a new argument? Something like `bool destroyAllScenes`

**Review by anicalbano — DISMISSED** [review]
🟢 Reviewed by QA


https://github.com/user-attachments/assets/9a7e4dba-5778-43b2-a6cf-48077808c549

File: Explorer/Assets/Scripts/ECS/SceneLifeCycle/ECSUnloadAllScenes.cs [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+using ECS.SceneLifeCycle.Components;
+using ECS.SceneLifeCycle.SceneDefinition;
+using ECS.StreamableLoading.Common;
+using SceneRunner.Scene;
+using System.Linq;
+using System.Threading;
+
+namespace ECS.SceneLifeCycle
+{
+    public partial class ECSUnloadAllScenes : IUnloadAllScenes
```
Comment (dalkia) [inline Explorer/Assets/Scripts/ECS/SceneLifeCycle/ECSUnloadAllScenes.cs:14]: Maybe we can remove this class since we don't use it anymore?

File: Explorer/Assets/Scripts/Global/Dynamic/DynamicGlobalRealmNavigator.cs [hunk 3]
```diff
@@ -32,13 +31,13 @@
 
 namespace Global.Dynamic
 {
-    public class RealmNavigator : IRealmNavigator
+    public class DynamicGlobalRealmNavigator : IRealmNavigator
```
Comment (dalkia) [inline Explorer/Assets/Scripts/Global/Dynamic/DynamicGlobalRealmNavigator.cs:34]: Why the name change? It may be a little confusing, since we don't have static neither a non global realm.

File: Explorer/Assets/Scripts/Global/Dynamic/DynamicGlobalRealmNavigator.cs [hunk 4]
```diff
@@ -32,13 +31,13 @@
...
     {
         private readonly URLDomain genesisDomain = URLDomain.FromString(IRealmNavigator.GENESIS_URL);
 
         private readonly ILoadingScreen loadingScreen;
         private readonly IMapRenderer mapRenderer;
-        private readonly IRealmController realmController;
+        private readonly IGlobalRealmController realmController;
```
Comment (dalkia) [inline Explorer/Assets/Scripts/Global/Dynamic/DynamicGlobalRealmNavigator.cs:40]: Same here, we dont have a non global one. Why the name change?

**Review by dalkia — APPROVED** [review]
Nice!
Just leaving some comments to clarify minor stuff

File: Explorer/Assets/Scripts/Global/Dynamic/DynamicGlobalRealmNavigator.cs (hunk 4 above)
Comment (lorux0) [reply Explorer/Assets/Scripts/Global/Dynamic/DynamicGlobalRealmNavigator.cs:40]: Because it contains a `GlobalWorld`, something that is only required in this assembly (DCL.Plugins), so we keep it separated from `IRealmController` thus can make a proper dependency management.
