### PR TITLE
fix: MediaPlayer pool doesn't release correctly

### LINKED ISSUE #1654: [QA] Background music persists after scene transitions in multiple locations
### **Explorer Alpha build versions:**

- **v0.16.0**

### **Issue Description:**
Background music persists after transitioning between scenes in various locations. This issue occurs when moving from scenes like 'Casa Roustan', 'Doll House' (-102, -97), and 'Mataha Gallery' (68, 70) to any other scene (e.g., another world or Genesis Plaza). The background music from the previous scene continues playing, overlapping with the audio of the new scene. The music should stop when teleporting to a new location.

### **STR:** 

1. Launch the explorer
2. Go to one of the affected scenes (e.g., 'Casa Roustan', 'Doll House', or 'Mataha Gallery').
3. Teleport to another scene (e.g., another world or Genesis Plaza).
4. Observe if the background music from the previous scene continues playing.

### **Expected behavior:**
The background music from 'Casa Roustan' should stop when the player transitions to a new scene.

### **Current behavior:**

https://github.com/user-attachments/assets/986558f1-d152-4c2a-ba70-bcc79bc2bc9a

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #1654 

When we entered into a scene that uses some `MediaPlayer`, it was getting from the corresponding pool correctly but, after jump into another scene and make the previous one to unload, the `MediaPlayer` was not being released back to the pool, so it provoked that we continued listening to it in the background even in the new scene.

## How to test the changes?
1. Launch the explorer
2. Go to one of the affected scenes (e.g.: 'Mataha Gallery' `68,70`, 'Casa Roustan' `37,-114` or 'Doll House' `-102,-97`).
3. Wait for watching or hearing the corresponding media of the scene.
4. Teleport to another scene.
5. Check that the previous media have been switched off.
6. Repet the process from the step 2 and observe that it works correctly.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs [hunk 1]
```diff
@@ -75,6 +75,8 @@ public void InjectToWorld(ref ArchSystemsWorldBuilder<World> builder, ISceneData
             CleanUpMediaPlayerSystem.InjectToWorld(ref builder, mediaPlayerPool, videoTexturePool);
 
             VideoEventsSystem.InjectToWorld(ref builder, ecsToCrdtWriter, sceneStateProvider, componentPoolsRegistry.GetReferenceTypePool<PBVideoEvent>(), frameTimeBudget);
+
+            finalizeWorldSystems.RegisterReleasePoolableComponentSystem<MediaPlayer, MediaPlayerComponent>(ref builder, componentPoolsRegistry);
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs:79]: I think it's not enough as Video textures can leak in the similar fashion, I propose you to make `CleanUpMediaPlayerSystem` implement `IFinalizeWorldSystem` and handle everything there in one place as there is already the code for both MediaPlayer and VideoTextures

**Review by mikhail-dcl — CHANGES_REQUESTED** [review]

**Review by mikhail-dcl — APPROVED** [review]
