### PR TITLE
fix: added listening status in community browser when already connected to a cvc

### LINKED ISSUE #5448: [QA] Community Browser - Community Cards - Missing Listening Text when joined voice chat of community.
Listening Text should appear on Joined stream on Community Cards on Community Browser

Image

### PR DESCRIPTION
**Pull request by davidejensen**
# Pull Request Description

## What does this PR change?
Fix #5448
This PR introduces the listening label in community cards in the communities browser when you are already connected to a stream and check that panel, like in the following screenshot:
Screenshot 2025-09-30 at 17 52 38

### Prerequisites
- [ ] Own or be a mod of a community to start a voice chat 

### Test Steps
1. Open the client with --debug and --voice-chat
2. Start a community voice chat
3. Go to the community panel
4. Verify that, like in the screenshot above, the card of the community you are currently talking in has the listening icon or listening text

### CODE REVIEW

File: Explorer/Assets/DCL/Communities/CommunitiesBrowser/StreamingCommunityResultCardView.cs [hunk 1]
```diff
@@ -67,9 +68,17 @@ public void SetCommunityId(string id) =>
...
+        {
+            listenersCountView.gameObject.SetActive(false);
+            listeningTooltip.SetActive(true);
+        }
+
         public void ConfigureListenersCount(bool isActive, int listenersCount)
         {
             listenersCountView.gameObject.SetActive(isActive);
+            listeningTooltip.SetActive(false);
+
```
Comment (fcolarich) [inline Explorer/Assets/DCL/Communities/CommunitiesBrowser/StreamingCommunityResultCardView.cs:81]: if `isActive ` is false, should we return directly after disabling both gameObjects instead of configuring the stringbuilder and all that?

Comment (davidejensen) [reply Explorer/Assets/DCL/Communities/CommunitiesBrowser/StreamingCommunityResultCardView.cs:81]: you are absolutely right, done!
