### PR TITLE
Fix: community images aspect ratio

### LINKED ISSUE #4588: Make the communities thumbnails fits the container

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description

Fixes #4588 

## What does this PR change?

This PR allows ImageViews to fit the image to the center keeping the original aspect ratio, avoiding weird stretches. Effectively visually cropping the excess.

### Prerequisites
- In order to test community images, you need to launch the explorer to the zone environment with the arg `--dclenv zone`

### Test Steps
1. For communities:
   1. Check that all community images now fit the cards even if the original image is not a square
3. Check that images across all UIs work as normal (effectively a global smoke test)

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/UI/ImageView.cs [hunk 1]
```diff
@@ -6,6 +6,7 @@
 
 namespace DCL.UI
 {
+    [RequireComponent(typeof(Image), typeof(AspectRatioFitter))]
```
Comment (QThund) [inline Explorer/Assets/DCL/UI/ImageView.cs:9]: If the AspectRationFitter is optional, it should not be required here.

**Review by QThund — APPROVED** [review]
Great. Please take a look to the comment.

**Review by sandrade-dcl — APPROVED** [review]
Great!
