### PR TITLE
fix: update audio for streams with no volume set

### LINKED ISSUE #2588: Audio settings do not affect audio streams on mac when the property hasVolume is false
### **Issue Description:**
Audio settings do not affect audio streams on mac when the property hasVolume is false

### **STR:** 

  1. Go to 0,83
  2. Change volumes of master and world
  3. Verify that the stream audio is not affected

### **Expected behaviour:**
Audio settings should affect the stream volume

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #2588
This is an integration of the fix of https://github.com/decentraland/unity-explorer/issues/2294 to tackle a specific case 

...

## How to test the changes?

1. Launch the explorer
2. Go to 0,83
3. Verify that master volume and world volume correctly modify the stream audio volume

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by anicalbano — APPROVED** [review]
🟢 Checked on Windows and working as expected. Tested also with other coordinates that contain music by default and the Master / World volume is changing as it should.
Waiting for Mac to full approval

https://github.com/user-attachments/assets/dc6ec8ca-762a-496e-84de-a73af91c6af7

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs [hunk 1]
```diff
@@ -86,7 +86,7 @@ private void UpdateAudioStream(ref MediaPlayerComponent component, PBAudioStream
 
             if (component.State != VideoState.VsError)
             {
-                float actualVolume = sdkComponent.Volume * worldVolumePercentage * masterVolumePercentage;
+                float actualVolume = sdkComponent.HasVolume ? sdkComponent.Volume : MediaPlayerComponent.DEFAULT_VOLUME * worldVolumePercentage * masterVolumePercentage;
```
Comment (fcolarich) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:89]: Shouldnt both kind of volumes be multiplied by the percentages?

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs [hunk 2]
```diff
@@ -101,7 +101,7 @@ private void UpdateVideoStream(ref MediaPlayerComponent component, PBVideoPlayer
...
```
Comment (fcolarich) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:104]: idem here?

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs (hunk 1 above)
Comment (davidejensen) [reply Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:89]: what do you mean?

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs (hunk 2 above)
Comment (davidejensen) [reply Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:104]: what do you mean? x 2

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs (hunk 1 above)
Comment (davidejensen) [reply Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:89]: ah sorry, the name might not be the best, the value is a 0->1 float

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs (hunk 2 above)
Comment (davidejensen) [reply Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:104]: ah sorry, the name might not be the best, the value is a 0->1 float

**Review by dalkia — APPROVED** [review]
Hopefully its the latest Mac lingering workaround 🤞

**Review by fcolarich — APPROVED** [review]
tasty!
