### PR TITLE
fix: login flow properly shows invalid email

### LINKED ISSUE #6971: [QA] Email+ OTP | Connection modal is appearing when adding an invalid email
### 🛠️ **Build version:**
[https://github.com/decentraland/unity-explorer/pull/6738](https://github.com/decentraland/unity-explorer/pull/6738)

### 📔 **Issue Description:**
Connection modal is appearing when adding an invalid email

### 👣 **STR:** 

  1. Open app in zone
  2. Add an invalid email
  3. Check that the OTP rejects your email with a connectivity modal

### ✔️ **Expected Result:**
An invalid email should be present on the recommended section

### ❌ **Actual Result with evidence:**
Connection modal is appearing when adding an invalid email

##### 🔁 Always - 10/10

https://github.com/user-attachments/assets/42eed98b-611c-44d9-b77d-467f6c021548

#### 🖥️ **Operative system and additional Notes:**
This happens in both platforms

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #6971

[Figma](https://www.figma.com/design/uR79cBxguBYCV6iHLmg2Os/%F0%9F%97%BA%EF%B8%8F-Email---OTP-Sign-In-%7C-Explorer-2.0-%7C-01-26?node-id=582-24614&t=9uBAkABHVKddLuPU-0)

## What does this PR change?

Adds the management of the otp code send so that the UI can properly react to failures caused by invalid emails.

The main idea is to handle the invalid email exception + have an event fired after a successful otp send so that the UI can react to that and proceed with the OTP validation

### Test Steps
1. Verify that at login, invalid emails are properly recognized and shown as described in the attached Figma doc
2. Only the login flow should be affected (credits menu shouldn't)

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/AuthenticationScreenFlow/States/IdentityVerificationOTPAuthState.cs [hunk 1]
```diff
@@ -124,11 +121,27 @@ private async UniTaskVoid AuthenticateAsync(string email, CancellationToken ct)
...
                 loginException = e;
-                machine.Enter<LoginSelectionAuthState, PopupType>(PopupType.CONNECTION_ERROR);
+                machine.Enter<LoginSelectionAuthState, ErrorType>(ErrorType.CONNECTION_ERROR);
             }
+            finally{ compositeWeb3Provider.OTPSendSuccess -= OnOTPSendSuccess; }
+        }
+
+        private void OnOTPSendSuccess(string emailAddress)
+        {
+            view.Show(emailAddress);
```
Comment (popuz) [inline Explorer/Assets/DCL/AuthenticationScreenFlow/States/IdentityVerificationOTPAuthState.cs]: I expect 
```
// Hide non-interactable Login Screen
viewInstance.LoginSelectionAuthView.Hide();

```
to be also here, so we see all switching logic in one place and understand how transition happens
