### PR TITLE
fix: Avoid badge and avatar overlap on passport

### LINKED ISSUE #3082: [QA] Profile | UI overlap between Passport badge and avatar when switching tabs
### 🛠️ **Build version:**

- **v0.50.0**

### 📔 **Issue Description:**
When navigating to **Profile** → **My Profile**, clicking on **Badges**, and then switching to **Photos**, the Passport badge and its details overlap with the avatar. The UI elements from the **Badges** tab should not persist or overlap when switching to another tab in the user's profile.

### **STR:** 

1. Click on **Profile** → **My Profile**.  
2. ⚠ Immediately click on the **Badges** tab, then quickly click on the **Photos** tab.  
3. Observe the overlapping UI elements (Passport badge and details over the avatar).

### ✔️ **Expected Result:**
The UI elements from the **Badges** tab should not persist or overlap when switching to the **Photos** tab. Each tab's content should display independently, without interference from other tabs.

https://github.com/user-attachments/assets/3fefce4f-4b8a-48bc-92fb-6e369efb2a85

### ❌ **Actual Result with evidence:**
The Passport badge and its details from the **Badges** tab overlap with the avatar after switching to the **Photos** tab.

### ➗ **Repro Index:**
8/10 attempts 

### 🖥️ **Operative system and additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5
Technical Details of My Mac:
	•	Model: MacBook Pro
	•	Chip: Apple M1 Pro
	•	Memory: 16GB
	•	Display: 16-inch (3456 × 2234)
	•	Storage: 335.12 GB available of 494.38 GB

### PR DESCRIPTION
**Pull request by Maurizio-dcl**
# Pull Request Description

## What does this PR change?
Fix #3082 
Removed asynchronous code that was handling badge preview GameObject visibility causing the overlap of badges on top of avatar.
Cleaned up code in PassportView.cs that was handling passport sections visibility to prevent configuration problems.

## Test Instructions
Open passport and quickly switch between Badges tab and other tabs.
You should not see any overlapping betweeen the badge preview and avatar preview.

### Test Steps
1. Open any passport
2. Switch to badges section and immediately switch to either overview or photos section
3. Verify that the badge preview and avatar preview do not appear together.

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

**Review by davidejensen — APPROVED** [review]
LGTM, thanks for the additional code cleanup

File: Explorer/Assets/DCL/Passport/PassportView.cs [hunk 1]
```diff
@@ -151,47 +151,35 @@ private void Awake()
...
-
-            OverviewSectionPanel.SetActive(false);
-            PhotosSectionPanel.SetActive(true);
-            BadgesSectionPanel.SetActive(false);
-            BadgeInfoModuleView.gameObject.SetActive(false);
-            ViewportSoftMask.enabled = false;
-            MainScroll.content = PhotosSectionPanel.transform as RectTransform;
-            MainScroll.verticalNormalizedPosition = 1;
-        }
+            OverviewSectionButton.SetSelected(passportSection == PassportSection.OVERVIEW);
```
Comment (NickKhalow) [inline Explorer/Assets/DCL/Passport/PassportView.cs:156]: Could you iterate sections rather than calling each manually?

**Review by NickKhalow — CHANGES_REQUESTED** [review]
Great work! Please address one comment

**Review by NickKhalow — APPROVED** [review]
