### PR TITLE
fix: clickable chat blocked input state

### LINKED ISSUE #4164: [QA] Chat | "DM settings" in mask appears clickable but isn't
### 🛠️ **Build version:**

- **v0.68.0**
- **v0.82.0**
- **v0.84.0**

### 📔 **Issue Description:**
When users attempt to send a DM but their settings prevent it, a UI mask appears with messages like:

- *"Add this user as a friend to chat, or update your DM settings to connect with everyone."*

The text **"DM settings"** is **underlined**, suggesting it's a hyperlink or clickable action — but it’s just plain text, with no interactive behavior. This creates confusion for the user.

### **STR:** 
1. Log in with an account with restricted DM settings.
2. Attempt to DM a user who is not a friend.
3. Observe the mask shown in the chat window.
4. Notice that "DM settings" is underlined, but not clickable.

### ✔️ **Expected Result:**
"DM settings" should either open the settings panel directly, or

### ❌ **Actual Result with evidence:**
The underlined text behaves like plain text when should act as a button that redirects user to the Settings.

https://github.com/user-attachments/assets/d6349d1f-83fb-4859-aa56-4ffb05937563

### ➗ **Repro Index:**
10/10 attempts 

### 🖥️ **Operative system and additional Notes:**
Windows and Mac

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #4164 

## What does this PR change?

This PR adds the opening of the explore panel (in the chat settings tab) when clicking the chat input blocker panel when trying to DM a user you are not friends with and your chat settings are set to `Friends only`.

### Test Steps
1. Open a conversation with a user you are not friends with
2. Verify that the input blocker message instructs you to check your personal settings (assuming you have set `Friends only`)
3. Check that by clicking that message, the explore panel opens in the chat settings tab
4. Verify that if the user is offline, clicking the input blocker does not opens the explore panel
5. Verify that the same happens if your settings are `all`

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Chat/_Refactor/ChatInput/States/BlockedChatInputState.cs [hunk 1]
```diff
@@ -64,6 +69,9 @@ protected override void OnInputUnblocked()
             ChangeState<TypingEnabledChatInputState>();
         }
 
+        private void BlockedInputClicked() =>
+            context.ChatEventBus.Publish(new ChatEvents.ClickableBlockedInputClickedEvent());
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/Chat/_Refactor/ChatInput/States/BlockedChatInputState.cs]: I don't see much value from introducing an event here: there is only one subscriber, so you could invoke `SharedSpaceManager` directly?

Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Chat/_Refactor/ChatInput/States/BlockedChatInputState.cs]: Initially I wanted to do something like that but the main problem was the circular dependency that gets created if I reference the explore panel (for the show command) into the chat.
Separating them using an event seemed a "clean" way to achieve it without polluting the asmdef

**Review by mikhail-dcl — APPROVED** [review]
