### PR TITLE
fix: logout flow

### LINKED ISSUE #2530: System.InvalidOperationException: Identity is not found in the cache
Sentry Issue: [UNITY-EXPLORER-4C2](https://decentraland.sentry.io/issues/5916039195/?referrer=github_integration)

```
System.InvalidOperationException: Identity is not found in the cache
  Module "DCL.Web3.Identities.Web3IdentityCacheExtensions", in EnsuredIdentity
  Module "DCL.WebRequests.RequestEnvelope`2", in SignRequest
  Module "DCL.WebRequests.RequestEnvelope`2", in InitializedWebRequest
  Module "DCL.WebRequests.WebRequestController+<SendAsync>d__4`4", in MoveNext
  Module "Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder", in Start
...
(106 additional frame(s) were not displayed)
```

### LINKED ISSUE #2990: [QA] Explorer kicks out a player to the main screen after logging in and out with different accounts
### **Build version:**
0.47.0

### **Issue Description:**
When a player logs in with a metamask account ,then logs out and logs in with a discord account (for example) the app whenever you are inside Genesis Plaza seems to kick you out of the session. The only way to fix this is to close the explorer and re-open it again.

### **STR:** 

  1. Open 0.47.0
  2. Log in with a metamask account
  3. Check that you will be able to see the genesis plaza 
  4. Log out 
  5. Log in **IN THE SAME SESSION** with a discord account 
  6. Once you tap the ''Jump to DCL '' button you will arrive to Genesis plaza 
  7. Check that the user , after a certain point is kicked out to the main screen 

### ❌ **Actual Result:**
When a player logs in with a metamask account ,then logs out and logs in with a discord account (for example) the app whenever you are inside Genesis Plaza seems to kick you out of the session. The only way to fix this is to close the explorer and re-open it again.

### ✔️ **Expected Result:**
Users should not be kicked out of the session after logging in and out with different types of accounts. 

### **Repro Index:**
5/5

### **Evidence:**

https://github.com/user-attachments/assets/45bc9c26-1094-417a-b5f5-c40ebfd8b669

#### **Additional Notes:**
This issue happens on Windows and Macos

### PR DESCRIPTION
**Pull request by dalkia**
## What does this PR change?

Fixes #2530 
Fixes #2990 

- Refactors the logout flow to have the same state before first login
- Deletes the `RestartRealmStartupOperation` since it didn't seem necessary
- Standarizes where to fetch remote locations to set objects while teleport and load operations are occuring

## How to test the changes?

1. Launch the explorer
2. Try to do logout and login
3. Also, test the issues enumerated in the fixes

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by fcolarich — APPROVED** [review]
Amazing work!!!!!!! 💪

File: Explorer/Assets/DCL/PluginSystem/Utils/MordorConstants.cs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+using System.Collections;
+using System.Collections.Generic;
+using UnityEngine;
+
+public static class MordorConstants
```
Comment (NickKhalow) [inline Explorer/Assets/DCL/PluginSystem/Utils/MordorConstants.cs:5]: We have MORDOR in `public partial class AvatarAttachHandlerSystem`, could you unify them?

**Review by NickKhalow — APPROVED** [review]
LGTM, just one comment
