### PR TITLE
Fix: scene radius limit

### LINKED ISSUE #731: Partitioning breaks after some time
```
IndexOutOfRangeException: Index 90000 is out of range of '90000' Length.
Unity.Collections.NativeArray`1[T].FailOutOfRangeError (System.Int32 index) (at <c5ed782439084ef1bc2ad85eec89e9fe>:0)
Unity.Collections.NativeArray`1[T].CheckElementReadAccess (System.Int32 index) (at <c5ed782439084ef1bc2ad85eec89e9fe>:0)
Unity.Collections.NativeArray`1[T].get_Item (System.Int32 index) (at <c5ed782439084ef1bc2ad85eec89e9fe>:0)
ECS.SceneLifeCycle.Systems.PartitionSceneEntitiesSystem.PartitionNewEntity (Arch.Core.Entity& entity, ECS.SceneLifeCycle.SceneDefinition.SceneDefinitionComponent& definition) (at Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs:127)
ECS.SceneLifeCycle.Systems.PartitionSceneEntitiesSystem.PartitionNewEntityQuery (Arch.Core.World world) (at Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/PartitionSceneEntitiesSystem.PartitionNewEntity(in Entity, ref SceneDefinitionComponent).g.cs:35)
ECS.SceneLifeCycle.Systems.PartitionSceneEntitiesSystem.Update (System.Single t) (at Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs:99)
ECS.Abstract.BaseUnityLoopSystem.Update (System.Single& t) (at Assets/Scripts/ECS/Abstract/BaseUnityLoopSystem.cs:29)
Rethrow as EcsSystemException: [SCENE_LOADING]: [PartitionSceneEntitiesSystem]
ECS.Abstract.BaseUnityLoopSystem.Update (System.Single& t) (at Assets/Scripts/ECS/Abstract/BaseUnityLoopSystem.cs:35)
Arch.SystemGroups.ExecutionNode`1[T].Update (T& t, System.Boolean throttle) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/ExecutionNode.cs:78)
Arch.SystemGroups.CustomGroupBase`1[T].UpdateInternal (T& t, System.Boolean throttle) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/Groups/CustomGroupBase.cs:119)
Arch.SystemGroups.DefaultGroup`1[T].Update (T& t, System.Boolean throttle) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/Groups/DefaultGroup.cs:46)
Arch.SystemGroups.ExecutionNode`1[T].Update (T& t, System.Boolean throttle) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/ExecutionNode.cs:74)
Arch.SystemGroups.SystemGroup.Update (Arch.SystemGroups.UnityBridge.TimeProvider+Info& timeInfo) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/SystemGroup.cs:118)
Arch.SystemGroups.DefaultSystemGroups.SimulationSystemGroup.Update () (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/DefaultSystemGroups/SimulationSystemGroup.cs:22)
Arch.SystemGroups.SystemGroupAggregate.TriggerUpdate () (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/PlayerLoopHelper/Aggregation/SystemGroupAggregate.cs:36)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
DCL.Diagnostics.DebugLogReportHandler:LogExceptionInternal(EcsSystemException) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:86)
DCL.Diagnostics.DebugLogReportHandler:LogExceptionInternal(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:97)
DCL.Diagnostics.ReportHandlerBase:LogException(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/ReportHandlerBase.cs:49)
DCL.Diagnostics.ReportHubLogger:UnityEngine.ILogHandler.LogException(Exception, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHubLogger.cs:38)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

```

`currentPartitionIndex` can't go beyond the total number of the scenes: it looks there is a hole somewhere

### PR DESCRIPTION
**Pull request by mikhail-dcl**
Fixes #731 

- Introduced the hard limit for partitioning radius as `150` leads to the significant performance deterioration
- Don't partition empty scenes as their number can grow indefinitely and will eventually lead to the exception
- Cleaned up from the empty scenes logic as the terrain system has completely replaced them

@Kinerius requiring your review as I don't know how terrain system relies on the partition of the empty scene (if ever)

### CODE REVIEW

File: Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs [hunk 1]
```diff
@@ -27,10 +27,14 @@ namespace ECS.SceneLifeCycle.Systems
     [UpdateBefore(typeof(ResolveStaticPointersSystem))]
     public partial class PartitionSceneEntitiesSystem : BaseUnityLoopSystem
     {
+        private const int DEPLOYED_SCENES_LIMIT = 90000; // 300x300 scenes (without empty)
```
Comment (Kinerius) [inline Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs:30]: In theory, we can have more than 90k since we already have some scenes outside the -150x150 boundaries. But for now this number shall suffice

**Review by Kinerius — APPROVED** [review]
LGTM, this wont affect the terrain system at all 👌

File: Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs (hunk 1 above)
Comment (mikhail-dcl) [reply Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/PartitionSceneEntitiesSystem.cs:30]: Yeah, it's a theory only. The main problem was connected to empty scenes

**Review by m3taphysics — CHANGES_REQUESTED** [review]
I seem to get a "pink screen" immediately on the build, I will verify main

image

**Comment by m3taphysics** [comment]
main is OK

I have aligned this branch to see if it is isolated to this

**Review by m3taphysics — APPROVED** [review]

**Comment by m3taphysics** [comment]
It works!
