### PR TITLE
fix: Add hash to GLTFComponent

### LINKED ISSUE #401: Incorrect texture displayed using Asset Bundles sharing the same model
## Description
We are experiencing an issue where multiple scenes deployed to the Art Week Plaza are not loading models or textures correctly. 
The same issues existing in current renderer.
The problem occurs when we have the same model and texture names (`cube_display.glb`) but with different texture content. After deploying all three scenes, they are displaying the same texture instead of their respective unique textures.

## Affected Scenes
- M1: https://github.com/decentraland-scenes/dcl_art_week_2024_m1 (coordinates: 60,68)
- M9: https://github.com/decentraland-scenes/dcl_art_week_2024_m9 (coordinates: 59,64)
- M14: https://github.com/decentraland-scenes/dcl_art_week_2024_m14 (coordinates: 65,63)

## Steps to Reproduce in unity-renderer
1. Visit the Art Week Plaza in Decentraland on web
2. Navigate to the coordinates of the affected scenes (M1, M9, and M14).
3. Observe that the `cube_display.glb` model in each scene is displaying the same texture instead of their respective unique textures.

## Expected Behavior
Each scene (M1, M9, and M14) should display the `cube_display.glb` model with its respective unique texture content.

The issue root cause comes from caching ABs based on the hash, which is the same for those models.
We could investigate how to introduce extra information for the id used in caching, i.e combining scene id to differentiate the assets

### LINKED ISSUE #1367: [QA] Game Expo: Booth Assets Mixed Up
### **Explorer Alpha build version:**
**v0.10.0**

### **Issue Description:**
In the Expo Game event, the booth assets are mixed up. Most of the booths display the labels 'BGA' or 'Euforika', and sometimes the interior assets are also mixed up with those from other booths.

### **Steps to reproduce:**

1. Launch the explorer.
2. Navigate to the Game Expo.
3. Observe the booths and their labels.
4. Inspect the interior assets of the booths.

### **Expected behavior:**

- Each booth should display the correct label corresponding to its content.
- Interior assets should be specific to each booth and not mixed with those from other booths.
AnyMagic-PROD
Aura-Prod
Avegochi-PROD

### **Current behavior:**
AnyMagic-EA
Aura-EA
Avegochi-EA

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

### PR DESCRIPTION
**Pull request by dalkia**
## What does this PR change?

Fixes #401 
Fixes #1367 

- Adds the Hash to the `GLTFComponent`. This allows the asset to be cached by hash rather than name, therefore if two scenes have an asset with the same name they won't hit false positive when hitting the cache.
- Removes the AssetBundle by name logic. We will always have the hash available, so no need to continue looking for it at `PrepareAssetBundleLoadingParametersSystem`. 
- The logic that checked if an asset is in the scene content is now in `LoadGltfContainerSystem`. If an asset is tried to be loaded without it being in the scene content, it will fail right away.

## How to test the changes?

1. Launch the explorer
2. Go to the Game Expo and the Art Week referred in the links. Check that the assets are correct 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs [hunk 1]
```diff
@@ -22,5 +25,22 @@ public GltfContainerComponent(ColliderLayer visibleMeshesCollisionMask, Collider
...
+            GltfContainerComponent component = new GltfContainerComponent();
+            component.SetFaulty(name);
+            return component;
+        }
+            
+
+        public void SetFaulty(string name)
+        {
+            State = LoadingState.FinishedWithError;
+            Promise = AssetPromise<GltfContainerAsset, GetGltfContainerAssetIntention>.CreateFinalized(
```
Comment (mikhail-dcl) [inline Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs:40]: I believe it should set an exception instead unless FAULTY_HASH is somehow used. Especially considering you already create this exception. Thus, you replicate the previous behavior.

File: Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs [hunk 2]
```diff
@@ -39,11 +44,22 @@ protected override void Update(float t)
         [None(typeof(GltfContainerComponent))]
         private void StartLoading(in Entity entity, ref PBGltfContainer sdkComponent, ref PartitionComponent partitionComponent)
         {
-            // It's not the best idea to pass Transform directly but we rely on cancellation source to cancel if the entity dies
-            var promise = Promise.Create(World, new GetGltfContainerAssetIntention(sdkComponent.Src, new CancellationTokenSource()), partitionComponent);
-            var component = new GltfContainerComponent(sdkComponent.GetVisibleMeshesCollisionMask(), sdkComponent.GetInvisibleMeshesCollisionMask(), promise);
-            component.State = LoadingState.Loading;
-            World.Add(entity, component);
+            GltfContainerComponent component;
+            if (!sceneData.TryGetHash(sdkComponent.Src, out string hash))
```
Comment (mikhail-dcl) [inline Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs:48]: I believe you could move these 3 lines into a single Utils method to avoid duplication

File: Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs [hunk 3]
```diff
@@ -39,11 +44,22 @@ protected override void Update(float t)
...
+            {
+                component = GltfContainerComponent.CreateFaulty(sdkComponent.Src);
+                var exception = new ArgumentException($"Asset Bundle {sdkComponent.Src} not found in the content");
+                World.Add(entity, component, new StreamableLoadingResult<GltfContainerAsset>(CreateException(exception)));
```
Comment (mikhail-dcl) [inline Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs:52]: Can you check with `DEBUG_ARCH` if it's not a repetitive adding of ` StreamableLoadingResult`? I have a bit of doubts

**Review by mikhail-dcl — CHANGES_REQUESTED** [review]

**Review by anicalbano — APPROVED** [review]
🟢 On QA side, working as expected

https://github.com/decentraland/unity-explorer/assets/139157886/a1ce6f21-a028-42a6-a315-3dd852cb34f5

File: Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs (hunk 2 above)
Comment (dalkia) [reply Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs:48]: Done!

File: Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs (hunk 3 above)
Comment (dalkia) [reply Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs:52]: I ran it, no apparent problem. The componet will be added only if the query of `[None(typeof(GltfContainerComponent))]` is not fullfilled. So, if we have that faulty component added, no repetition should be possible

**Review by mikhail-dcl — APPROVED** [review]
