### PR TITLE
fix: ab registry manifest fallback case sensitivity + lsd manifest fallback

### LINKED ISSUE #7608: System.Exception: AssetBundleManifestFallbackHelper: AB Manifest Fallback requested
Sentry Issue: [UNITY-EXPLORER-K02](https://decentraland.sentry.io/issues/7137529098/?referrer=github_integration)

```
System.Exception: AssetBundleManifestFallbackHelper: AB Manifest Fallback requested
```

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #7608 

## What does this PR change?

This PR makes sure that AB registry version result is case insensitive: many offchain wearables have capital letters that before weren't matching. E.g.:
```
urn:decentraland:off-chain:base-avatars:BaseFemale
urn:decentraland:off-chain:base-avatars:BaseMale
urn:decentraland:off-chain:base-avatars:distressed_black_Jeans
urn:decentraland:off-chain:base-avatars:Espadrilles
urn:decentraland:off-chain:base-avatars:Mustache_Short_Beard
urn:decentraland:off-chain:base-avatars:Red_topcoat
urn:decentraland:off-chain:base-avatars:SchoolShoes
urn:decentraland:off-chain:base-avatars:Thunder_earring
```

Where ever an Emote or Wearable is requested, the AB Registry is used (LSD included) so that the manifest is always present.

On top of that I noticed that when the inventory page had only base emotes, a request to the registry was made with an empty `pointers` array, causing a 400 log. With an early exit, this is now prevented.

### Test Steps
1. Login normally, scroll the whole wearable and emote inventory waiting for all pages to load-> verify no `AssetBundleManifestFallbackHelper: AB Manifest Fallback requested` message is spotted in the log
2. Start a scene locally and repeat step 1 -> same result of no error logs
3. Try to both load/kill portable experiences and check the logs -> no error should appear

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundlesVersions.cs [hunk 1]
```diff
@@ -6,14 +7,12 @@ public struct AssetBundlesVersions
...
-            return new AssetBundlesVersions (true);
-        }
+        public static AssetBundlesVersions Create() =>
+            new (true);
 
-        private AssetBundlesVersions(bool paramLess)
+        private AssetBundlesVersions(bool _)
         {
-            versions = new Dictionary<string, PlatformVersionInfo>();
+            versions = new Dictionary<string, PlatformVersionInfo>(StringComparer.InvariantCultureIgnoreCase);
```
Comment (mihakrajnc) [inline Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundlesVersions.cs]: Very cool, did not know this was a thing 👌

File: Explorer/Assets/DCL/NetworkDefinitions/Browser/DecentralandUrlsSource.cs [hunk 2]
```diff
@@ -228,6 +229,8 @@ protected virtual UrlData RawUrl(DecentralandUrl decentralandUrl) =>
                 DecentralandUrl.EntitiesActive => UrlData.RealmDependent(FeatureFlagsConfiguration.Instance.IsEnabled(FeatureFlagsStrings.ASSET_BUNDLE_FALLBACK) && launchMode.CurrentMode != LaunchMode.LocalSceneDevelopment ? $"{Url(DecentralandUrl.AssetBundleRegistry)}/entities/active" :
                     realmData.Configured ? realmData.Ipfs.EntitiesActiveEndpoint.Value : null),
 
+                DecentralandUrl.EntitiesActiveElements => $"{Url(DecentralandUrl.AssetBundleRegistry)}/entities/active",
```
Comment (mihakrajnc) [inline Explorer/Assets/DCL/NetworkDefinitions/Browser/DecentralandUrlsSource.cs:233]: What's the difference between EntitiesActive and EntitiesActiveElements?

Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/NetworkDefinitions/Browser/DecentralandUrlsSource.cs:233]: EntitiesActive is meant for whatever is not a Wearable or an Emote (those are always solved by the registry), e.g. scenes

Comment (dalkia) [inline Explorer/Assets/DCL/NetworkDefinitions/Browser/DecentralandUrlsSource.cs]: Lets add a comment why elements exist, and when to use it

**Comment by AnsisMalins** [comment]
## [PR 7956](https://github.com/decentraland/performance-testing/actions/runs/23794944333)
PR number: [7956](https://github.com/decentraland/unity-explorer/pull/7956)
[Windows change build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20459-63a62b2/Decentraland_windows64.zip)
[Windows baseline build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.136.0-alpha/Decentraland_windows64.zip)
[macOS change build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20459-63a62b2/Decentraland_macos.zip)
[macOS baseline build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.136.0-alpha/Decentraland_macos.zip)

### Intel Core i3

Change samples: 2670
Baseline samples: 2675

| Metric | Change | Baseline | Delta | Improvement | |
| --- | ---: | ---: | ---: | ---: | :---: |
| CPU average | 33.7 ms | 33.6 ms | 0.1 ms | -0.2% | ⚪ |
| CPU 1% worst | 59.5 ms | 53.6 ms | 5.9 ms | -11.0% | 🔴 |
| CPU 0.1% worst | 127.6 ms | 138.1 ms | -10.5 ms | 7.6% | 🟢 |
| GPU average | 15.3 ms | 16.1 ms | -0.8 ms | 5.3% | 🟢 |
| GPU 1% worst | 21.9 ms | 21.9 ms | -0.0 ms | 0.1% | ⚪ |
| GPU 0.1% worst | 27.3 ms | 25.5 ms | 1.9 ms | -7.3% | 🔴 |

**Comment by AnsisMalins** [comment]
## [PR 7956](https://github.com/decentraland/performance-testing/actions/runs/23801949317)
PR number: [7956](https://github.com/decentraland/unity-explorer/pull/7956)
[Windows change build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20470-220affe/Decentraland_windows64.zip)
[Windows baseline build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.136.0-alpha/Decentraland_windows64.zip)
[macOS change build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20470-220affe/Decentraland_macos.zip)
[macOS baseline build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.136.0-alpha/Decentraland_macos.zip)

### Intel Core i3

Change samples: 2672
Baseline samples: 2671

| Metric | Change | Baseline | Delta | Improvement | |
| --- | ---: | ---: | ---: | ---: | :---: |
| CPU average | 33.6 ms | 33.7 ms | -0.0 ms | 0.1% | ⚪ |
| CPU 1% worst | 54.8 ms | 59.9 ms | -5.1 ms | 8.6% | 🟢 |
| CPU 0.1% worst | 120.1 ms | 147.1 ms | -27.0 ms | 18.3% | 🟢 |
| GPU average | 15.7 ms | 15.7 ms | 0.0 ms | -0.2% | ⚪ |
| GPU 1% worst | 20.8 ms | 21.6 ms | -0.9 ms | 4.0% | 🟢 |
| GPU 0.1% worst | 22.6 ms | 28.6 ms | -6.0 ms | 21.1% | 🟢 |

**Comment by AnsisMalins** [comment]
## [PR 7956](https://github.com/decentraland/performance-testing/actions/runs/23847005360)
PR number: [7956](https://github.com/decentraland/unity-explorer/pull/7956)
[Windows change build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20524-5b89997/Decentraland_windows64.zip)
[Windows baseline build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.137.0-alpha/Decentraland_windows64.zip)
[macOS change build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20524-5b89997/Decentraland_macos.zip)
[macOS baseline build](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.137.0-alpha/Decentraland_macos.zip)

### Intel Core i3

Change samples: 2668
Baseline samples: 2672

| Metric | Change | Baseline | Delta | Improvement | |
| --- | ---: | ---: | ---: | ---: | :---: |
| CPU average | 33.7 ms | 33.6 ms | 0.0 ms | -0.1% | ⚪ |
| CPU 1% worst | 55.2 ms | 54.4 ms | 0.8 ms | -1.4% | ⚪ |
| CPU 0.1% worst | 130.0 ms | 119.7 ms | 10.3 ms | -8.6% | 🔴 |
| GPU average | 15.4 ms | 15.8 ms | -0.5 ms | 3.1% | 🟢 |
| GPU 1% worst | 22.5 ms | 20.9 ms | 1.5 ms | -7.3% | 🔴 |
| GPU 0.1% worst | 24.4 ms | 22.7 ms | 1.7 ms | -7.7% | 🔴 |

**Comment by AnsisMalins** [comment]
PR [#7956](https://github.com/decentraland/unity-explorer/pull/7956), run [#23907720450](https://github.com/decentraland/performance-testing/actions/runs/23907720450)

Builds: [Windows change](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20604-813a551/Decentraland_windows64.zip), [Windows baseline](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.137.0-alpha/Decentraland_windows64.zip), [macOS change](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/branch/fix/7608-ab-registry-fallback/pr-20604-813a551/Decentraland_macos.zip), [macOS baseline](https://explorer-artifacts.decentraland.org/@dcl/unity-explorer/releases/v0.137.0-alpha/Decentraland_macos.zip)

### Intel Core i3

| Metric | Change | Baseline | Delta | Improvement | |
| --- | ---: | ---: | ---: | ---: | :---: |
| Samples | 2655 | 2672 | | | |
| CPU average | 33.8 ms | 33.6 ms | 0.2 ms | -0.6% | ⚪ |
| CPU 1% worst | 68.1 ms | 55.8 ms | 12.3 ms | -22.0% | 🔴 |
| CPU 0.1% worst | 251.4 ms | 132.1 ms | 119.3 ms | -90.3% | 🔴 |
| GPU average | 16.2 ms | 15.4 ms | 0.8 ms | -5.2% | 🔴 |
| GPU 1% worst | 23.6 ms | 21.0 ms | 2.5 ms | -12.1% | 🔴 |
| GPU 0.1% worst | 28.6 ms | 23.2 ms | 5.4 ms | -23.5% | 🔴 |
