### PR TITLE
fix: added support for friend jump in in world

### LINKED ISSUE #3685: [QA] Friends | Jump in button does not teleport to a friend's place IN WORLDS
### 🛠️ **Build version:**
0.60.0

### 📔 **Issue Description:**
Jump in button does not teleport to a friend's place

### **STR:** 

  1. Open 0.60.0
  2. Go to a friend's place by teleporting with the jump in button
  3. Check that the jump in button does not work

### ✔️ **Expected Result:**
Jump in button should teleport to a friend's place

### ❌ **Actual Result with evidence:**
Jump in button does not teleport to a friend's place

Evidence:

[Player (1).log](https://github.com/user-attachments/files/19426848/Player.1.log)

### ➗ **Repro Index:**
10/10

### 🖥️ **Operative system and additional Notes:**
This issue happens on both platforms

### PR DESCRIPTION
**Pull request by davidejensen**
# Pull Request Description

## What does this PR change?
Fix #3685
This PR introduces support for jumping in to friends that are in a world and not in genesis city (previously jump in was supported only for genesis city connected users)

### Prerequisites
- [ ] Have 2 separate account connected in 2 separate places

### Test Steps
1. Jump in via friends panel when User A is in genesis city and User B is somewhere else in genesis city
2. Jump in via friends panel when User A is in genesis city and User B is in a world
3. Jump in via friends panel when User A is in a world and User B is in genesis city
4. Jump in via friends panel when User A is in a world and User B is in another world

Verify teleporting around works as before

### CODE REVIEW

File: Explorer/Assets/DCL/Multiplayer/Connectivity/ArchipelagoHttpOnlineUsersProvider.cs [hunk 1]
```diff
@@ -36,8 +40,19 @@ public async UniTask<IReadOnlyCollection<OnlineUserData>> GetAsync(IEnumerable<s
             foreach (string userId in userIds)
                 urlBuilder.AppendParameter(new URLParameter("id", userId));
 
-            return await webRequestController.GetAsync(urlBuilder.Build(), ct, ReportCategory.MULTIPLAYER)
-                                             .CreateFromNewtonsoftJsonAsync<List<OnlineUserData>>(serializerSettings: SERIALIZER_SETTINGS);
+            List<OnlineUserData> onlineUsers = await webRequestController.GetAsync(urlBuilder.Build(), ct, ReportCategory.MULTIPLAYER)
+                                                                                     .CreateFromNewtonsoftJsonAsync<List<OnlineUserData>>(serializerSettings: SERIALIZER_SETTINGS);
+
+            foreach (string userId in userIds)
```
Comment (lorenzo-ranciaffi) [inline Explorer/Assets/DCL/Multiplayer/Connectivity/ArchipelagoHttpOnlineUsersProvider.cs:46]: does the endpoint only supports a single wallet per request? :(

**Review by lorenzo-ranciaffi — CHANGES_REQUESTED** [review]
LGTM! Just one concern about the `OnlineUserData` endpoint called once per wallet

File: Explorer/Assets/DCL/Multiplayer/Connectivity/ArchipelagoHttpOnlineUsersProvider.cs (hunk 1 above)
Comment (davidejensen) [reply Explorer/Assets/DCL/Multiplayer/Connectivity/ArchipelagoHttpOnlineUsersProvider.cs:46]: yup

File: Explorer/Assets/DCL/Multiplayer/Connectivity/OnlinePlayerInWorldJsonDtoConverter.cs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+            var dataObject = JObject.Load(reader).ToObject<DataObject>();
+
+            //Returning null as if the user is not connected to a world the endpoint returns a different data structure
+            if (dataObject == null)
+                return null;
+
+            existingValue = new OnlineUserData
+            {
+                worldName = dataObject.world.Replace(SCENE_ROOM_PREFIX, ""),
```
Comment (lorux0) [inline Explorer/Assets/DCL/Multiplayer/Connectivity/OnlinePlayerInWorldJsonDtoConverter.cs:33]: Minor thing, but feels odd to me, since archipelago doesn't return any `worldName`. I guess it will be empty in this case, although it doesn't feel clean.
Use string.Empty instead of `""`

**Review by lorux0 — DISMISSED** [review]

File: Explorer/Assets/DCL/Multiplayer/Connectivity/ArchipelagoHttpOnlineUsersProvider.cs (hunk 1 above)
Comment (lorux0) [reply Explorer/Assets/DCL/Multiplayer/Connectivity/ArchipelagoHttpOnlineUsersProvider.cs:46]: Agree. In the meantime is good enough since we are only requesting one user

File: Explorer/Assets/DCL/Multiplayer/Connectivity/OnlinePlayerInWorldJsonDtoConverter.cs (hunk 2 above)
Comment (davidejensen) [reply Explorer/Assets/DCL/Multiplayer/Connectivity/OnlinePlayerInWorldJsonDtoConverter.cs:33]: well, this is the converter used only for the world case, so it won't be used for the archipelago peers as in that case the other converter will be used
Fixed the `string.Empty`!

File: Explorer/Assets/DCL/Multiplayer/Connectivity/OnlineUserData.cs [hunk 3]
```diff
@@ -6,7 +6,9 @@ namespace DCL.Multiplayer.Connectivity
     [Serializable]
     public struct OnlineUserData
     {
+        public bool IsInWorld => !string.IsNullOrEmpty(worldName);
         public Vector3 position;
+        public string worldName;
```
[the remark this answers is not in the document]
Comment (davidejensen) [reply Explorer/Assets/DCL/Multiplayer/Connectivity/OnlineUserData.cs]: true, done!

File: Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendListSectionUtilities.cs [hunk 4]
```diff
@@ -42,9 +44,17 @@ async UniTaskVoid JumpToFriendLocationAsync(CancellationToken ct = default)
                     return;
 
                 OnlineUserData userData = onlineData.First();
-                Vector2Int parcel = userData.position.ToParcel();
-                realmNavigator.TeleportToParcelAsync(parcel, ct, false).Forget();
-                parcelCalculatedCallback?.Invoke(parcel);
+
+                if (userData.IsInWorld)
+                {
+                    realmNavigator.TryChangeRealmAsync(URLDomain.FromString(string.Concat(WORLDS_BASE_URL, userData.worldName)), ct).Forget();
```
[the remark this answers is not in the document]
Comment (davidejensen) [reply Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendListSectionUtilities.cs]: done

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- ✔️  Backpack and wearables in world
- ✔️ Emotes in world and in backpack
- ✔️ Teleport with map/coordinates/Jump In
- ✔️ Chat and multiplayer
- ✔️ Profile card
- ✔️ Camera
- ✔️ Skybox

**Review by m3taphysics — APPROVED** [review]
