### PR TITLE
fix: show currently unread notifications badge

### LINKED ISSUE #1983: Add the missing counter to the notifications button
The counter exposing unread notifications on top of the bell icon is missing. This feature is important to let users know about unread important events.
Screenshot 2024-09-05 at 15 50 56

Behaviour:
- The counter shows the amount of unread notifications.
- The counter increments too after receiving in-world synchronic notifications.
- The counter disappears as soon as the notification panel gets opened.

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
## What does this PR change?

Fix #1983 

Changes how the initially fetched notifications are managed and introduces the unread notification badge on the notification button of the sidebar
...

## How to test the changes?

1. Modify [DecentralandUrlsSource](https://github.com/decentraland/unity-explorer/blob/main/Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs) replacing {ENV} with "zone" at DecentralandUrl.Notification and DecentralandUrl.NotificationRead strings
2. Push some notifications (check next session for a "how to")
3. Launch the Explorer
4. Check that the badge is visibile on top of the Notification icon and the number corresponds to the amount of pushed notifications
5. Open the Notification panel, scroll down through the notifications and check that the counter changes accordingly
6. Notifications pushed while in-game should not modify the badge

## How to push notifications
In order to push new notifications you have to make requests via Postman using [this](https://github.com/user-attachments/files/17114459/DCL.Notifications.postman_collection.json) Postman collection.
1. Import the collection
2. Select the "New reward received" request
3. Go to "Body" section and paste your wallet ID as the value of the "address" key
23E53E91-2536-4117-BD1B-FECD974DA9B7_1_201_a

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by DafGreco — COMMENTED** [review]
Windows verified 🟢 waiting for mac testing !

File: Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs [hunk 1]
```diff
@@ -95,6 +115,28 @@ private async UniTaskVoid InitialNotificationRequestAsync(CancellationToken ct)
...
+            foreach (var notification in requestNotifications)
+                if (notification.Read == false)
+                    unreadNotifications++;
+
+            UpdateUnreadNotificationRender();
+        }
+
+        private void UpdateUnreadNotificationRender()
+        {
+            view.unreadNotificationCounterText.text = unreadNotifications.ToString();
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs:128]: To String allocates a new string, you can improve it with the SetText provided by text mesh pro IIRC
```
 view.unreadNotificationCounterText.SetText("{0}", unreadNotifications);
```

**Review by davidejensen — CHANGES_REQUESTED** [review]
Looks good, left 2 comments

**Review by davidejensen — APPROVED** [review]
