### PR TITLE
fix: Make top & down arrows in the events calendar clickable

### LINKED ISSUE #7346: [QA] Discover | Events - The arrow at the bottom of the event list should be clickable
### 🛠️ **Build version:**
v0.130.0

### 📔 **Issue Description:**

The arrow at the bottom of the list of events per day should be clickable. 
There should also be an arrow on top so the user can click it to scroll up.

### 👣 **STR:** 

  1. Go to the Events menu
  2. hover over the bottom of the list of any day
  3. When the arrow appears, click it

### ✔️ **Expected Result:**

The arrow should be clickable and should scroll down the list

### ❌ **Actual Result with evidence:**

The arrow is not clickable, if there is an event card it opens instead of scrolling down

https://github.com/user-attachments/assets/8a53ceef-d2d7-4d49-b9f9-ceb77b26dfdf

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# Pull Request Description
Fix #7346

## What does this PR change?
It makes the arrow at the bottom of the list of events per day clickable in order to be able to move the scroll with it.
It also adds a new arrow in the top side of each column with the same purpose.

### Test Steps
1. Go to the Events menu.
2. Hover over the list of any day.
4. When the arrows appear, click on them and check that the scroll os moving automatically.
5. Also, check that each arrow will appears or disappears depending on if we are on the top (or on the bottom) side of the scrolling.

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Events/EventsCalendarView.cs [hunk 1]
```diff
@@ -271,8 +286,32 @@ private void FillWithEmptyCards(IReadOnlyList<EventDTO> events, int eventsListIn
...
+            float scrollableHeight = contentHeight - viewportHeight;
+
+            if (scrollableHeight <= 0f)
+                return;
+
+            float normalizedStep = pixelStep / scrollableHeight;
+            float targetPos = Mathf.Clamp01(scrollRect.verticalNormalizedPosition + normalizedStep);
+
+            if (activeScrollTweens.TryGetValue(eventsListIndex, out Tweener existingTween))
+                existingTween?.Kill();
```
Comment (pravusjif) [inline Explorer/Assets/DCL/Events/EventsCalendarView.cs]:
```suggestion
                existingTween.Kill();
```

**Review by pravusjif — APPROVED** [review]
LGTM
