### PR TITLE
fix: [Marketplace Credits] Last minute security measures

### LINKED ISSUE #4157: [Marketplace Credits] Last minute security measures
New scenarios to add:

- New UI screen for when all the credits have been emitted for the current week so the user will have to wait fornext one.
- For the cases when, for any reason, we decide to pause the rewards program... instead of directly hidding the feature through the feature flag, we haev to show a new UI screen indicating the user that it is paused.
- For the cases when the user has tried to solve the claiming credits captcha too many times, we need to show a message indicating that the captcha has been blocked so the user will need to wait 24h for trying again.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# Pull Request Description
Fix #4157 

### New scenarios added
- New UI screen for when all the credits have been emitted for the current week so the user will have to wait forn ext one.

image

- For the cases when, for any reason, we decide to pause the rewards program... instead of directly hiding the feature through the feature flag, we show a new UI screen indicating the user that it is paused.

image

- For the cases when the user has tried to solve the claiming credits captcha too many times, we will show a message indicating that the captcha is blocked so the user will need to wait 24h for trying again.

image

### Fixes
- Fix anchors in the Credits Rewards UI.
- Fix the alpha transparency of the rays in the Credits Rewards UI.

image

**NOTE**: The idea is to add these changes in the next release after **Marketplace Credits** feature has been put into production.

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs [hunk 1]
```diff
@@ -343,16 +344,17 @@ private void SetSidebarButtonAnimationAsPaused(bool isOn) =>
...
             {
                 SetSidebarButtonAnimationAsAlert(false);
                 SetSidebarButtonAsClaimIndicator(false);
                 return;
             }
 
             bool thereIsSomethingToClaim = creditsProgramProgressResponse.SomethingToClaim();
-            SetSidebarButtonAnimationAsAlert(!creditsProgramProgressResponse.HasUserStartedProgram() || !creditsProgramProgressResponse.IsUserEmailVerified() || thereIsSomethingToClaim);
-            SetSidebarButtonAsClaimIndicator(creditsProgramProgressResponse.HasUserStartedProgram() && creditsProgramProgressResponse.IsUserEmailVerified() && thereIsSomethingToClaim);
+            SetSidebarButtonAnimationAsAlert(!creditsProgramProgressResponse.HasUserStartedProgram() || !creditsProgramProgressResponse.IsUserEmailVerified() || (thereIsSomethingToClaim && !creditsProgramProgressResponse.credits.isBlockedForClaiming));
```
Comment (dalkia) [inline Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs:356]: I understand this is a complicated condition. But for readability, WDYT of something like

```
bool hasNotStarted = !creditsProgramProgressResponse.HasUserStartedProgram();
bool isNotVerified = !creditsProgramProgressResponse.IsUserEmailVerified();
bool canClaim = thereIsSomethingToClaim && !creditsProgramProgressResponse.credits.isBlockedForClaiming;

SetSidebarButtonAnimationAsAlert(hasNotStarted || isNotVerified || canClaim);
```

**Review by dalkia — APPROVED** [review]
Im approving because Im not sure of the urgency, but leaving some comments for your consideration

File: Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs [hunk 2]
```diff
@@ -343,16 +344,17 @@ private void SetSidebarButtonAnimationAsPaused(bool isOn) =>
...
+            SetSidebarButtonAsClaimIndicator(creditsProgramProgressResponse.HasUserStartedProgram() && creditsProgramProgressResponse.IsUserEmailVerified() && thereIsSomethingToClaim && !creditsProgramProgressResponse.credits.isBlockedForClaiming);
```
Comment (dalkia) [inline Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs:357]: You can even use the bools created above

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on [ Platform ] following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- [✔️ ] Backpack and wearables in world
- [ ✔️] Emotes in world and in backpack
- [ ✔️] Teleport with map/coordinates/Jump In
- [ ✔️] Chat and multiplayer
- [ ✔️] Profile card


All cases have been checked and working like a charm!
