### PR TITLE
fix: emote wheel shortcut opens wheel instead of triggering emote

### LINKED ISSUE #6765: [QA] Emotes | Emote wheel shortcut opens wheel instead of triggering emote
### 🛠️ **Build version:**
- `v0.118.0-alpha-feat/social-emotes-rebirth-fixes-66d9bb1`

### 📔 **Issue Description:**
In this build, emote shortcuts using the emote wheel do not work as expected.

When holding **B** and pressing a number key (1–0), the emote should be immediately triggered without opening the emote wheel UI. While **B** is held, the user should be able to switch between different emotes by pressing different numbers.

Currently, no emote is triggered while holding **B**, and once **B** is released, the emote wheel UI opens instead.  
This behavior is incorrect and differs from **Prod**, where shortcuts work properly and the emote wheel never opens when using **B + number**.

### 👣 **STR:** 
1. Open the app
2. Press and hold **B**
3. While holding **B**, press any number key (1–0)
4. Optionally press different numbers while still holding **B**
5. Release **B**

### ✔️ **Expected Result:**
- Pressing **B + number** triggers the corresponding emote immediately
- While **B** is held, different numbers can be pressed to select different emotes
- The emote wheel UI should **never open** when using shortcuts

### ❌ **Actual Result with evidence:**
- No emote is triggered while holding **B** and selecting a NUM
- When **B** is released, the emote wheel UI opens
- Shortcut behavior is completely ignored

### ➗ **Reproduction:**
🔁 Always  

#### 🖥️ **Operative system and additional Notes:**
- Windows and Mac
- Reproduces consistently in this branch
- Works correctly in **Prod**
- Affects emote triggering via shortcuts only

### PR DESCRIPTION
**Pull request by Maurizio-dcl**
# Pull Request Description
Fix #6765 

## What does this PR change?
Preventing opening the emote wheel on the next B key release when playing an emote through the B+[0-9] shortcut.

### Test Steps

1. Open the app
2. Press and hold B
3. While holding B, press any number key (1–0)
4. Optionally press different numbers while still holding B
5. Wait an arbitrary amount of time
6. Release B
7. Verify that the emotes wheel is not shown
8. Press and release B
9. Verify that the emotes wheel is shown as usual

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/UpdateEmoteInputSystem.cs [hunk 1]
```diff
@@ -55,6 +55,8 @@ private void OnSlotPerformed(InputAction.CallbackContext obj)
             triggeredEmote = emoteIndex;
             isWheelBlocked = true;
             emotesBus.OnQuickActionEmotePlayed();
```
Comment (daniele-dcl) [inline Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/UpdateEmoteInputSystem.cs]: I would think maybe instead of 2 different events we could add an enum param to the 1st one to specify how the emote was triggered?

File: Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/EmotesBus.cs
Comment (biotech77) [inline Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/EmotesBus.cs]: @Maurizio-dcl we have generic event bus IEventBus that you can use to not introduce new EmotesBus?

**Review by fcolarich — APPROVED** [review]
Looks good! great work! 💪
