### PR TITLE
Fix/UI sorting

### LINKED ISSUE #931: metadyne: unable to close UI
### **Explorer Alpha build version:**
**0.3.335-g8f637032-main**

### **Issue Description:**

When entering Metadyne Labs, if we open the UI (for example, the Ranking) and move through it, it's not possible to close the screen later. In order to fix the problem, we need to go to other place and back to Metadyne.

### **Steps to reproduce:**

  1. Go to Metadyne, open the ranking and navigate through the pages
  2. Attempt to close it

### **Expected behaviour:**
We can close the modal and keep going around the world

### **Current behaviour:**
It's not possible to close it

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/45e254ce-16c2-4376-845f-791b82cbaf17

### LINKED ISSUE #1175: [QA] AnyMagik scene (-59, 8) doesn't load, it crashed once after not loading and if after this the user goes back to position 0,0 , Genesis Plaza may not load properly
### **Explorer Alpha build version:**

[0.3.402-g7a23dc7e

AnyMagik scene (-59, 8)  doesn't load (it only crashed once after not loading) and if after this the user goes back to position 0,0 , Genesis Plaza may not load properly .

These are the logs of the crash that took place only once: 
[crash smoke testing.log](https://github.com/decentraland/unity-explorer/files/15379557/crash.smoke.testing.log)

And these are the screenshots which show genesis plaza doesn't load properly after coming back from AnyMagik: 

smoke any magic loading

smoke any magik to genesis not fully loaded

### **Steps to reproduce:**

  1. Go to AnyMagik (-59, 8)
  2. Stay there for 10 seconds 
  3. Go back to 0, 0 again

### **Expected behaviour:**

No crash should take place, AnyMagik should load well and Genesis Plaza should load properly when going back there

### **Current behaviour:**

AnyMagik scren doesn't load, a crash might take place after this screen not loading,  and genesis plaza might not load well once going back there from AnyMagik

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [ ] Medium
- [x ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [x ] High
- [ ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

### PR DESCRIPTION
**Pull request by mikhail-dcl**
- Ignore re-parenting of the root UI transform (it looks like an SDK bug/vulnerability)
- Fix re-parenting to the root upon a component change: converted the root to the fully-fledged `UITransformComponent` with children, sorting, etc.
- Work-around very strange unsorted UI Elements: some `UITransform` may have default `0` `rightOf`, looks like an SDK bug.
- Changed sorting to the node-based scheme:
   - Linear-based one worked as expected due to the coincidence: entities are created in the sorted order at first place
   - It would not work if `rightOf` is changed dynamically
- Relax media hosts check, see https://github.com/decentraland/unity-renderer/pull/5844 
- Fix repetitive teleport adding

----
How to QA:
- Try Goerli-plaza: `(80,-3)` should work as expected: with proper layout and order, all textures should be loaded in the dialogs
- Genesis City: Fix #1175 
- MetadyneLabs: Fix #931 
- If you have other UI-rich scenes in mind try them

### CODE REVIEW

File: Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UITransformComponent.cs [hunk 1]
```diff
@@ -15,12 +17,26 @@ public class UITransformComponent
         public bool IsHidden;
         public PointerEventType? PointerEventTriggered;
 
-        public UITransformRelationData RelationData;
+        // public UITransformRelationData RelationData;
```
Comment (sandrade-dcl) [inline Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UITransformComponent.cs:20]: I guess we can remove the commented lines like this one

**Review by sandrade-dcl — APPROVED** [review]

**Review by anicalbano — APPROVED** [review]
🟢 Reviewed by QA
