### PR TITLE
fix: LSD remote ABs

### LINKED ISSUE #8411: [PERF] High memory consumption in genesis plaza local scene development
### 📊 **Version & Environment**
It has been spotted since loads of version before, more than 1 month and an half, not sure if it's something related to a specific commit

### 📊 **Impact Level:**
High

### 📋 **Affected metrics:**
- [ ] Average FPS
- [ ] Frame time spikes
- [x] Memory usage
- [x] Load time

### 📝 **Description:**
When testing genesis plaza in local scne development it has been noticed an excessive amount of memory usage, reaching the cap and causing assets to not load or general instability in the scene.
The problem is also that when doing /reload the situation worsens by loading less and less assets each time, pointing to possible leaks in the /reload flow

On my Mac M1 in prod when in regular deployed genesis plaza I'm at around 5GB of memory consumption, in Local Scene development with the central plaza I'm at 12GB on the first enter.

#### Affected Users/Scenarios:
content team is greatly affected by this as it worsen their flow of developing genesis plaza

### 👣 **Reproduction Steps:**
1. Clone the genesis plaza repo
2. Launch the central plaza scene
3. Connect via build with local scene development (or via editor but via editor memory consumption is even worse) with open Decentraland.app --args --realm http://127.0.0.1:8000/ --position 0,0 --local-scene true --debug --skip-version-check true
4. Open the /debug panel and check the memory usage
5. Reload and see some assets not loading like benches/umbrellas/chairs/plants/...

### 📋 **Investigation Checklist:**
- [ ] Performance metrics confirmed with monitoring tools
- [ ] Root cause identified through profiling
- [ ] Optimization approach determined
- [ ] Performance targets feasible and agreed upon

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes https://github.com/decentraland/unity-explorer/issues/8411

Fixes the possibility to use remote asset bundles on local scene development mode. This is necessary for some dense scenes to run and perform hot reloads. Running these scenes through the raw asset files takes consumes too much memory making it impossible to load.

Adds a new program args: `--lsd-use-remote-ab --lsd-remote-ab-world <worldName> --lsd-remote-ab-server <Genesis/Goerli/World>`.

Problems found:
- The remote scene entity id was not correctly overwritten on Hybrid load mode (LSD+remote ABs).
- The asset bundle manifest version was not resolved and so all of the AB load attempts were failing.
- There was a race condition in between asset hashing and scene entity definition processing. Assets were requested before the scene entity definition was fully complete, keeping an inconsistent state.
- Missing cancellation token management on the load process.

Additionally detects which content files are missing on the remote ABs. Then load them locally to allow creators to use a mix of both: remote asset bundles and local files for performance & workflow improvements.

**One edge case in consideration**: if the creator modifies a model of an existing file, it will not be able to see the updated version when running the scene, because the AB already exists in the CDN. Two solutions for this case:
- Publish the latest changes of the scene and regenerate asset bundles
- Rename the file to a new one

## Test Instructions

Go through different scenes and worlds. Check they load normally.
Try to run any local scene, check that loads normally.

If you have access download this repo: https://github.com/decentraland-scenes/Genesis-Plaza-2025/tree/main/central-plaza
Run the `central-plaza` scene with args:
```
--realm http://127.0.0.1:8000/ --position 0,0 --local-scene true --debug --skip-version-check true --lsd-use-remote-ab --lsd-remote-ab-world dclexperience.dcl.eth
```

Check that the scene loads. Try a `/reload` too.

Add a new model in the `centra-plaza` project. For example:
```
const boardEntity = engine.addEntity();
Transform.create(boardEntity, {parent: plazaCenterEntity, position: Vector3.create(0, 2, 0)})
GltfContainer.create(boardEntity, {
  src: 'assets/board.glb',
});
```

(You can duplicate any glb in the project and copy into `assets/board.glb`).

Run the scene and check that loads normally and you can also see the new model you added at the firepit.

### Additional Testing Notes

How to run local scenes: https://github.com/decentraland/unity-explorer/blob/dev/docs/how-to-connect-to-a-local-scene.md

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Branch & PR Standards](../docs/branch-and-pr-standards.md) before submitting. It explains the automated review flow, QA/DEV approval requirements, and what each label does — especially useful for first-time contributors.

### CODE REVIEW

**Review by Ludmilafantaniella — APPROVED** [review]
✅ Approved — Tested on Windows and Mac.

- Local scene (`central-plaza`) loaded correctly with remote AB args, new model visible at the firepit.
- `/reload` worked as expected.

Regression — scenes visited:
Genesis Plaza, Metagamimall, DCL Game Expo, DCL MF25, Antrom, Demos.dcl.eth, Metadynelabs.dcl.eth, Tophub.dcl.eth, chri.dcl.eth — all loaded normally.

LGTM! 🚀

https://github.com/user-attachments/assets/e45cfa63-7a6f-4601-b91a-279d5fc72f43

https://github.com/user-attachments/assets/78feee0c-0e8a-4d80-a763-4f670527be42

✅Smoke test:
- ✔️ Backpack and wearables in world
- ✔️ Emotes in world and in backpack
- ✔️ Teleport with map/coordinates/Jump In
- ✔️ Chat and multiplayer
- ✔️ Profile card
- ✔️ Community places

File: Explorer/Assets/DCL/Infrastructure/SceneRunner/Scene/HibridScene/HybridSceneHashedContent.cs [hunk 1]
```diff
@@ -74,43 +74,63 @@ public bool TryGetContentUrl(string contentPath, out URLAddress result)
...
+            }
+            catch (OperationCanceledException) { throw; }
+            catch (Exception) { ReportHub.LogError(reportCategory, $"Trying to load hybrid scene with id {remoteSceneID} failed. You wont get the asset bundles"); }
         }
 
-        private bool IsTexture(string contentDefinitionFile)
+        /// <summary>
+        ///     Files that are not converted to asset bundles and should be fetched from the local content server.
+        /// </summary>
+        private static bool IsNonConvertedAsset(string file)
```
Comment (pravusjif) [inline Explorer/Assets/DCL/Infrastructure/SceneRunner/Scene/HibridScene/HybridSceneHashedContent.cs]: the function name could be better, right now it looks like it points at stuff that doesn't get converted in the AB converter, and textures do get converted up there.

**Review by pravusjif — APPROVED** [review]
LGTM, nice job, I still think in the future we may reduce the App params to just `--lsd-remote-ab-server` and if something is provided in there, internally we check if it's an ENS world or not.

However we can make that change in the future if we see we need it!

File: Explorer/Assets/DCL/Infrastructure/SceneRunner/Scene/HibridScene/HybridSceneHashedContent.cs (hunk 1 above)
Comment (lorux0) [reply Explorer/Assets/DCL/Infrastructure/SceneRunner/Scene/HibridScene/HybridSceneHashedContent.cs]: Fixed! https://github.com/decentraland/unity-explorer/commit/bd2e026027f41a51f66b4d2bac223fa1409e9b8c

**Review by pravusjif — APPROVED** [review]
