### PR TITLE
fix: change saturation slider color on hue change

### LINKED ISSUE #2258: [QA] Saturation slider does not update with color change
### **Explorer Alpha build versions:**
0.29.0

### **Issue Description:**
Saturation slider does not update with color change.

### **STR:** 

  1. Open 0.29.0
  2. Go to the color change slider 
  3. Change the color 
  4. Verify that the saturation slider does not update with color change 

### **Expected behavior:**
The saturation slider should update with the color change 

### **Current behavior:**
Saturation slider does not update with color change.

#### **Evidence:**
Screenshot 2024-10-01 131904

#### **Additional Notes:**
This issue happens on Mac and Windows

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
## What does this PR change?

Fix #2258 

Colors the saturation slider based on which color is chosen through the hue slider

## How to test the changes?

1. Launch the explorer
2. Open the backpack
3. Select the body shape and click on color
4. Verify that the saturation slider color matches the avatar color
5. Verify that by changing the hue slider, the saturation slider color changes accordingly
6. Verify that by clicking on a color preset the saturation slider color changes accordingly

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by davidejensen — APPROVED** [review]

File: Explorer/Assets/DCL/UI/ColorPicker/ColorPickerController.cs [hunk 1]
```diff
@@ -38,6 +39,7 @@ public ColorPickerController(ColorPickerView view, ColorToggleView colorToggle,
                 actionOnRelease:(toggle) => toggle.gameObject.SetActive(false));
 
             view.SliderHue.Slider.onValueChanged.AddListener(_ => SetColor());
+            view.SliderHue.Slider.onValueChanged.AddListener(_ => SetSaturationColor());
```
Comment (m3taphysics) [inline Explorer/Assets/DCL/UI/ColorPicker/ColorPickerController.cs:42]: Can we check why these listeners arent removed?

**Review by m3taphysics — CHANGES_REQUESTED** [review]

File: Explorer/Assets/DCL/UI/ColorPicker/ColorPickerController.cs (hunk 1 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/UI/ColorPicker/ColorPickerController.cs:42]: It was a miss. I've added the IDisposable interfaces on all controllers that needed it and called the Dispose() function where needed

**Review by m3taphysics — APPROVED** [review]
