### PR TITLE
Fix: colliders visibility switch

### LINKED ISSUE #1190: [QA] Hidden events cards on Genesis Plaza can be clicked and seen as empty
### **Explorer Alpha build version:**
**0.3.463-gf5b67b0c-main**

### **Issue Description:**

When on Genesis Plaza, at the top of the clouds, if we turn around and hoover the mouse over the background, we can see that the option SELECT appears and we can click the hidden cards of the caroussels and they will pop up empty (no image).

### **Steps to reproduce:**

  1. On genesis plaza, go around the events billboards and hoover with the mouse
  2. When an empty space with SELECT appears, click on it

### **Current behaviour:**
The card pops up and it's the empty model.

#### **Evidence:**

https://github.com/decentraland/unity-explorer/assets/139157886/1700e367-8225-40e4-b321-60d9c94ccb7c

### PR DESCRIPTION
**Pull request by popuz**
## What does this PR change?
fix #1190 
Add colliders enabling switch based on visibility.

## How to test the changes?

1. Check the original bug report for testing. Basically you shouldn't be able to click on hidden plates of the carousel.
2. 
## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/PluginSystem/World/AssetsCollidersPlugin.cs [hunk 1]
```diff
@@ -17,6 +19,11 @@ public class AssetsCollidersPlugin : IDCLWorldPluginWithoutSettings
         private readonly IPhysicsTickProvider physicsTickProvider;
         private readonly IComponentPoolsRegistry componentPoolsRegistry;
 
+        static AssetsCollidersPlugin()
+        {
+            EntityEventBuffer<PrimitiveColliderComponent>.Register(500);
```
Comment (sandrade-dcl) [inline Explorer/Assets/DCL/PluginSystem/World/AssetsCollidersPlugin.cs:24]: I would extract this `500` value into a constant in order to have it more visible in case we want to change this param in the future.

**Review by sandrade-dcl — APPROVED** [review]
LGTM! Please take a look to the build, it seems the tests are failing.

File: Explorer/Assets/DCL/PluginSystem/World/AssetsCollidersPlugin.cs (hunk 1 above)
Comment (popuz) [reply Explorer/Assets/DCL/PluginSystem/World/AssetsCollidersPlugin.cs:24]: good idea. I just copy-pasted it from other examples

File: Explorer/Assets/Scripts/ECS/Unity/Visibility/Systems/VisibilitySystemBase.cs [hunk 2]
```diff
@@ -33,28 +33,28 @@ protected override void Update(float t)
         private void ProcessEvent(Entity entity, TComponent @event)
         {
             if (World.TryGet(entity, out PBVisibilityComponent? visibilityComponent))
-                UpdateVisibilityInternal(@event, visibilityComponent!.GetVisible());
+                UpdateVisibilityInternal(ref @event, visibilityComponent!.GetVisible());
```
Comment (mikhail-dcl) [inline Explorer/Assets/Scripts/ECS/Unity/Visibility/Systems/VisibilitySystemBase.cs:36]: it's wrong by design to use `event` by `ref` as it's written always as a copy. That's why it was `in` before. You can't change it.

**Review by mikhail-dcl — CHANGES_REQUESTED** [review]

**Review by anicalbano — COMMENTED** [review]
💚 Reviewed by QA

https://github.com/decentraland/unity-explorer/assets/139157886/a41d29f0-5c37-4f1f-8bf4-2c18e00c3b8f

**Review by mikhail-dcl — APPROVED** [review]
