### PR TITLE
fix: Added loop bool to emote props

### LINKED ISSUE #520: Emotes Loop is not functional
We relied on the Editor only code at runtime

```
// TODO move looping to the Asset Bundle Converter
                        // AnimationClipSettings? settings = AnimationUtility.GetAnimationClipSettings(animationClip);
                        // settings.loopTime = true;
                        // AnimationUtility.SetAnimationClipSettings(animationClip, settings);
```

it should be moved to the Asset Bundle Converter

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

Fixes #520 

Added loop parameter to emote prop animators.

## How to test the changes?

- All emotes should properly loop
- The last batch of fixes for emotes was done on Windows asset bundles, Mac asset bundles were enqueued today but the converter is busy so its going to take some time for them to be updated.
## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/Editor/AssetBundleCacheClearMenu.cs [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+using UnityEngine;
+
+namespace ECS.StreamableLoading.AssetBundles.Editor
+{
+    public static class AssetBundleCacheClearMenu
+    {
+        [MenuItem("Decentraland/Clear AssetBundle cache")]
+        public static void ClearAssetBundles()
+        {
+            Caching.ClearCache();
```
Comment (dalkia) [inline Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/Editor/AssetBundleCacheClearMenu.cs:11]: Nice

**Review by dalkia — APPROVED** [review]
