### PR TITLE
Fix: Avatar Rotation | Avatars not facing correct direction during streaming events

### LINKED ISSUE #3935: Users are seen facing the left hand side of the stream in MVFW
## Severity:
SEV-5 | Cosmetics issue
## Description:
Avatars are facing the streaming screen directly at 144,-78 but for some members they appear to be facing the runway
## Operating system:
WIN
## Error:
N/A
## Expected Behavior:
For every avatar to be facing the streaming screen
## Current Behavior:
Some are seeing avatars facing the runway
## Steps to reproduce:
Jump in and check from different devices
## Ticket number:
N/A

### PR DESCRIPTION
**Pull request by popuz**
# Pull Request Description
Fix #3935

Rotation wasn't taken into account when setting initial position of avatars, or teleporting it. 
I added rotation assignment in places where we assign position. 

### Test Steps
1. **GIVEN** there are some people/avatars already in the game (in some  scene or world) 
        **AND** they you are not moving they avatars (for example, watching the stream)
2. **WHEN** you logged in to this place
3. **THEN** you see avatars rotated correctly (in the direction they are actually looking and not blank North) 

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [x] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Multiplayer/Movement/Systems/RemotePlayersMovementSystem.cs [hunk 1]
```diff
@@ -208,12 +209,18 @@ private void StartInterpolation(float deltaTime, ref CharacterTransform transCom
...
+            SetPositionAndRotation(transComp.Transform, intComp.Start.position, intComp.Start.rotationY);
 
             // TODO (Vit): Restart in loop until (unusedTime <= 0) ?
             float unusedTime = Interpolate(deltaTime, ref transComp, ref remotePlayerMovement, ref intComp);
         }
 
+        private static void SetPositionAndRotation(Transform transform, Vector3 position, float rotationY)
+        {
+            var newRotation = Quaternion.Euler(transform.rotation.x, rotationY, transform.rotation.z);
+            transform.SetPositionAndRotation(position, newRotation);
```
Comment (fcolarich) [inline Explorer/Assets/DCL/Multiplayer/Movement/Systems/RemotePlayersMovementSystem.cs:221]: do we check anywhere if previous position/rotation are different than the new ones? 
not sure how much Unity optimizes transform updates and if it does it by itself, it didnt use to, but I dont know if they add it? 🤔

**Review by fcolarich — APPROVED** [review]
Nice!
