### PR TITLE
fix: Teleport to Genesis Plaza after a Sign Out

### LINKED ISSUE #2125: [QA] Metadynelabs: Avatar Stuck After Account Switch
### **Explorer Alpha build versions:**

- **v0.28.x**

### **Issue Description:**
an issue was encountered when switching accounts to access level 02 due to the levels carousel not functioning. Upon logging in with a different account, the avatar became stuck, displaying only the head. This problem occurs specifically after switching accounts, but it can be resolved by traveling to another location and then returning.

💡 Suggestion: I believe the issue stems from accounts having different progress in Metadynelabs. To resolve this, why not ensure that when a user logs out from a world and then logs in with a different account, they start in Genesis Plaza instead of returning to the world?

### **STR:** 

1. /goto metadynelabs
2. Log out of the current account.
3. Log in with a different account.
4. Observe the avatar upon logging in.

### **Expected behavior:**
The avatar should be fully visible and functional after switching accounts.

### **Current behavior:**

https://github.com/user-attachments/assets/645a1f9c-7939-41ef-ac9a-92bae61f10f3

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #2125 

This change ensures that when a user logs out and then logs in again, he will start in Genesis Plaza instead of returning to the current place where he was.

## How to test the changes?
Follow the steps to reproduce in the linked issue.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by DafGreco — COMMENTED** [review]
Fix implemented Properly on Windows !


https://github.com/user-attachments/assets/0a4537d2-ef42-4e81-bf51-effc1a7027f1

**Review by anicalbano — APPROVED** [review]
🟢 Tested on Mac and Windows and working as expected. Logging in/out/in with another account takes the correct avatar.

With this PR we also checked:
✔️ Teleport
✔️ Backpack
✔️ Emotes and Wearables
✔️ MetadyneLabs
✔️ Check navbar
✔️ Check navmap

https://github.com/user-attachments/assets/c49b024f-50c3-46e6-a599-302ac7cd5dee

File: Explorer/Assets/DCL/UserInAppInitializationFlow/IUserInAppInitializationFlow.cs [hunk 1]
```diff
@@ -10,6 +10,7 @@ UniTask ExecuteAsync(
             bool showAuthentication,
             bool showLoading,
             bool reloadRealm,
```
Comment (m3taphysics) [inline Explorer/Assets/DCL/UserInAppInitializationFlow/IUserInAppInitializationFlow.cs:12]: This function is getting unweildly I would suggest we introduce a parameter object to improve the readability and if its changed in future it will not require changes to many function calls

Comment (sandrade-dcl) [reply Explorer/Assets/DCL/UserInAppInitializationFlow/IUserInAppInitializationFlow.cs]: Good point! I have just applied your suggested change [here](https://github.com/decentraland/unity-explorer/pull/2295/commits/c18f3d7e8401d5169f0b8236bd7154a9946a68b1). Let me know wdyt!

**Review by m3taphysics — APPROVED** [review]
