### PR TITLE
fix: Mute world/avatar/chat sounds while we are in auth or loading screens

### LINKED ISSUE #746: [QA] World and avatar sounds can be heard in the loading screen
While the loading screen is active, you can hear the scene sounds, the avatar falling and stuff like that.

Loading screen should disable the 3D camera audiolistener.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #746 

- Creation of `AudioMixerVolumesController` for managing audio mixer volumes. It exposes the nest methods:
  - `MuteGroup(AudioMixerExposedParam groupParam)`
  - `UnmuteGroup(AudioMixerExposedParam groupParam)`

## How to test the changes?
1. Launch the explorer
2. While you're in the Authentication screen, check that you only only listen to the music and not the world, avatar or chat sounds.
3. While you're in any loading screen, check that you only only listen to the music and not the world, avatar or chat sounds.
4. Check that, once you're inside the world and controlling your avatar, all the sounds are recovered to the original volume.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs [hunk 1]
```diff
@@ -47,7 +46,8 @@ private enum ViewState
         private readonly Animator splashScreenAnimator;
         private readonly CharacterPreviewEventBus characterPreviewEventBus;
         private readonly FeatureFlagsCache featureFlagsCache;
-        private readonly AudioMixer generalAudioMixer;
+        private readonly AudioMixerVolumesController audioMixerVolumesController;
+        private float originalAvatarAudioVolume;
```
Comment (fcolarich) [inline Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs:50]: I think this is not used anywhere?

File: Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenController.cs [hunk 2]
```diff
@@ -16,20 +18,27 @@ public partial class SceneLoadingScreenController : ControllerBase<SceneLoadingS
...
+        private readonly AudioMixerGroup audioMixerGroupController;
 
         private int currentTip;
         private SceneTips tips;
         private CancellationTokenSource? tipsRotationCancellationToken;
         private CancellationTokenSource? tipsFadeCancellationToken;
         private IntVariable? progressLabel;
         private readonly List<UniTask> fadingTasks = new ();
+        private float originalWorldAudioVolume;
+        private float originalAvatarAudioVolume;
```
Comment (fcolarich) [inline Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenController.cs:32]: This two as well, I think they are not used anymore?

**Review by fcolarich — APPROVED** [review]
Looks great! Left 2 comments about apparently unused variables 💪
