### PR TITLE
fix: outdated avatar in-world

### LINKED ISSUE #3984: [QA] Emote Wheel | Triggered emotes don't match visuals after account switch
### 🛠️ **Build version:**
**v0.64.0**

### 📔 **Issue Description:**
After switching accounts, the emote wheel visually updates with the newly equipped emotes, but triggering them (via click or number key) plays the previously equipped ones instead.

**📝 LOGS:**  [Player.log](https://github.com/user-attachments/files/19778451/Player.log)

### **STR:** 
1. Enter the explorer with Account A
2. Log out from Account A
3. Log in with a different Account B
4. Open backpack [I] → Emote tab
5. Equip different emotes
6. Exit backpack
7. Open the emote wheel [B]
8. Trigger an emote by clicking or pressing a number
9. Repeat spet step 2-8 using a different account

### ✔️ **Expected Result:**
The emote triggered should match the one shown in the corresponding slot.

### ❌ **Actual Result with evidence:**
Visuals on the wheel update, but triggering an emote plays the old one from Account A.

https://github.com/user-attachments/assets/8d30c261-13c7-4355-96d3-6fd641c36b84

### ➗ **Repro Index:**
10/10 attempts 

### 🖥️ **Operative system and additional Notes:**
Windows and Mac

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #3984 

The issue was caused by a delay in saving the profile between closing the backpack and opening the emote wheel. During this gap, the profile data was outdated, resulting in outdated emotes being shown.
The solution updates the avatar’s in-world immediately, and performs a rollback if an error occurs, ensuring consistency with the catalyst.

## Test Instructions

Save the profile and open the wheel emote. You should always have your emotes updated.

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs [hunk 1]
```diff
@@ -142,9 +157,51 @@ private async UniTaskVoid UpdateProfileAsync(CancellationToken ct)
             bool publishProfileChange = !appArgs.HasFlag(AppArgsFlags.SELF_PREVIEW_BUILDER_COLLECTIONS)
                                         && !appArgs.HasFlag(AppArgsFlags.SELF_PREVIEW_WEARABLES);
 
-            var profile = await selfProfile.UpdateProfileAsync(publish: publishProfileChange, ct);
-            MultithreadingUtility.AssertMainThread(nameof(UpdateProfileAsync), true);
-            UpdateAvatarInWorld(profile!);
+            Profile? oldProfile = await selfProfile.ProfileAsync(ct);
```
Comment (dalkia) [inline Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs:160]: WDYT is we move the `oldProfile` logic to `SelfProfile`. 

I would name it something like `lastProfileSaved`. To me, makes sense that the logic is handled there:

- You can store which is the last profile that was successful so you don't have to rebuild it when a change is requested
- `ProfileBuilder` logic can exist only there and not here
- You can move the `if` conditions to that class, leaving this one a little bit more cleaner

File: Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs [hunk 2]
```diff
@@ -142,9 +157,51 @@ private async UniTaskVoid UpdateProfileAsync(CancellationToken ct)
...
+            profileCache.Set(newProfile.UserId, newProfile);
+            UpdateAvatarInWorld(newProfile);
+
+            if (!publishProfileChange) return;
+
+            try
+            {
+                var updatedProfile = await selfProfile.UpdateProfileAsync(newProfile, ct);
+                MultithreadingUtility.AssertMainThread(nameof(UpdateProfileAsync), true);
+                UpdateAvatarInWorld(updatedProfile!);
```
Comment (dalkia) [inline Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs:192]: I dont quite follow if you need this line. If it was successful, what are you updating here?

**Review by dalkia — CHANGES_REQUESTED** [review]
I been wanting this forever. Massive UX change experience 🔥 

Looks good, but leaving code clarity comments for discussion

File: Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs (hunk 1 above)
Comment (lorux0) [reply Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs:160]: Will move everything, including the update of the ECS avatar in `SelfProfile`, but will do it in a different pr as it will involve a bigger refactor

File: Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs (hunk 2 above)
Comment (lorux0) [reply Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs]: Removed!
