### PR TITLE
Fix: mention analytics

### LINKED ISSUE #4241: [DATA] `is_mention` flag always set to false in `chat_message_sent` event
### 📔 **Issue Description:**

In chat message sent event, `is_mention` property is always false and a `mentions` array with each wallet address mentioned should be included also in the properties to know who was mentioned in the message.

### Expected behaviour.
When a chat message has a mention, `is_mention` property should be true and `mentions` should contain an array with all the addresses mentioned in the message.

### PR DESCRIPTION
**Pull request by davidejensen**
# Pull Request Description

## What does this PR change?
Fix #4241
Adds a new analytic field for chat messages including the wallet id of mentioned people and ensures proper setting of isMention field

### Test Steps
1. Launch the client
2. Send some messages both with mentions and without mentions
3. Try to mention multiple people
4. Verify that everything works as normal

### Additional Testing Notes
- Note any edge cases to verify
- Mention specific areas that need careful testing
- List known limitations or potential issues

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs [hunk 1]
```diff
@@ -65,19 +66,30 @@ public void Send(ChatChannel channel, string message, ChatMessageOrigin origin,
             analytics.Track(AnalyticsEvents.UI.MESSAGE_SENT, jsonObject);
         }
 
-        private bool  CheckIfIsMention(string message)
+        private bool CheckIfIsMention(string message, out JsonArray mentions)
         {
+            mentions = new JsonArray();
```
Comment (popuz) [inline Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs]: does it make sense to cache it (create once in the constructor and then `.Clear())`?

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- [✔️ ] Log In/Log Out
- [✔️ ] Backpack and wearables in world
- [ ✔️] Emotes in world and in backpack
- [ ✔️] Teleport with map/coordinates/Jump In
- [✔️ ] Chat and multiplayer
- [✔️ ] Profile card
- [✔️ ] Skybox
- [✔️ ] Settings


No new issues were found during this sanity check ✅
