### PR TITLE
Fix: load profile thumbnail from ECS error spam

### LINKED ISSUE #3855: System.Exception: Exception occured on loading ECS.StreamableLoading.Textures.Texture2DData from Get Texture: https://profile-images-bucket-43d0c58.s3.us-east-1.amazonaws.com/v1/entities/bafkreid566fjfz4efc5mjqz7owao7tdq4opkfntwexifcewfordmy4ppya/face.png with url https:...
Sentry Issue: [UNITY-EXPLORER-AKS](https://decentraland.sentry.io/issues/6351085956/?referrer=github_integration)

```
Cysharp.Threading.Tasks.UnityWebRequestException: HTTP/1.1 404 Not Found
  Module "Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1", in GetResult
  Module "Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationConfiguredSource", in GetResult
  Module "DCL.WebRequests.Analytics.WebRequestsAnalyticsExtensions+<WithAnalyticsAsync>d__0`1", in MoveNext
  Module "Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1", in Run
  Module "Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1", in TrySetException
...
(201 additional frame(s) were not displayed)

System.Exception: Exception occured on loading ECS.StreamableLoading.Textures.Texture2DData from Get Texture: https://profile-images-bucket-43d0c58.s3.us-east-1.amazonaws.com/v1/entities/bafkreid566fjfz4efc5mjqz7owao7tdq4opkfntwexifcewfordmy4ppya/face.png with url https://profile-images-bucket-43d0c58.s3.us-east-1.amazonaws.com/v1/entities/bafkreid566fjfz4efc5mjqz7owao7tdq4opkfntwexifcewfordmy4ppya/face.png.
No more sources left.
```

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description

Fixes #3855 

Loading profile thumbnails in the SDK (see #3882) through the ECS `LoadTextureSystem` doesn't take into consideration that the picture could not be ready at the time of the request (the generation process could take several seconds after a profile update), returning a 404.
This leads to a big exception logging as seen in the MVFW logs, depending on the scene code.

## What does this PR change?

This PR introduces a retry system that is similar to the cached profile thumbnails we have in the UI with a retry policy spread across time in order to let the BE generate the requested picture.

It tries 5 times total with a delay of 5 seconds every try, but logging an error only if even the last attempt fails.
This prevents the spam we see in the log, highly increasing the chance of silently resolve the texture.

### Test Steps
1. Visit the MVFW scenes and check that you have very few, if any, errors related to profile-images
2. Verify that loading an avatar profile texture through the SDK still works by visiting the world `eax.dcl.eth` and clicking on the cube: the thumbnail of the wallet `0x31d4f4dd8615ec45bbb6330da69f60032aca219e` should appear 
image

### Additional Testing Notes
- If you are aware of other scenes that use this SDK feature, check there as well

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both paltforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- [✔️ ] Backpack and wearables in world
- [✔️ ] Emotes in world and in backpack
- [✔️ ] Teleport with map/coordinates/Jump In
- [✔️ ] Camera
- [✔️ ] Skybox
- [✔️ ] Settings

File: Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs [hunk 1]
```diff
@@ -38,28 +41,71 @@ protected override async UniTask<StreamableLoadingResult<Texture2DData>> FlowInt
...
+                    newCommonArgs,
+                    textureArguments,
+                    textureOp,
+                    ct,
+                    GetReportData(),
+                    suppressErrors: true,
+                    ignoreIrrecoverableErrors: true
+                );
+            }
+            catch (Exception)
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs:89]: there is a shortcut already - `SuppressAnyExceptionWithFallback`

File: Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs [hunk 2]
```diff
@@ -38,28 +41,71 @@ protected override async UniTask<StreamableLoadingResult<Texture2DData>> FlowInt
...
+                    ct,
+                    GetReportData()
+                );
+
+            return new StreamableLoadingResult<Texture2DData>(new Texture2DData(result.EnsureNotNull()));
+        }
+
+        private async UniTask<IOwnedTexture2D?> TryResolveAvatarTextureAsync(URLAddress url, GetTextureIntention intention, CancellationToken ct)
+        {
+            CommonArguments newCommonArgs = new CommonArguments(url, AVATAR_TEXTURE_MAX_ATTEMPTS, StreamableLoadingDefaults.TIMEOUT, AVATAR_TEXTURE_REQUEST_DELAY_MS);
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs:70]: So it will be `AVATAR_TEXTURE_MAX_ATTEMPTS + 1` in total, right?

File: Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs [hunk 3]
```diff
@@ -38,28 +41,71 @@ protected override async UniTask<StreamableLoadingResult<Texture2DData>> FlowInt
...
+                //Ignore exceptions AVATAR_TEXTURE_MAX_ATTEMPTS times so that we can try once more with exception logging enabled
+            }
+
+            if (result != null) return result;
+
+            CommonLoadingArguments newArgs = intention.CommonArguments;
+            newArgs.URL = url;
+            intention.CommonArguments = newArgs;
+
+            result = await webRequestController.GetTextureAsync(
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs:100]: The final request you will make straight away without waiting, so there is a high chance you will receive the  same result as the last iteration

File: Explorer/Assets/DCL/WebRequests/WebRequestController.cs [hunk 4]
```diff
@@ -77,7 +77,7 @@ public WebRequestController(IWebRequestsAnalyticsContainer analyticsContainer, I
                     if (envelope.CommonArguments.AttemptsDelayInMilliseconds() > 0)
                         await UniTask.Delay(TimeSpan.FromMilliseconds(envelope.CommonArguments.AttemptsDelayInMilliseconds()));
 
-                    if (exception.IsIrrecoverableError(attemptsLeft))
+                    if (exception.IsIrrecoverableError(attemptsLeft) && !envelope.IgnoreIrrecoverableErrors)
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/WebRequests/WebRequestController.cs:80]: It's kinda cheaty and it should not be part of the common framework: I'd propose to use `IGNORE_NOT_FOUND` that was already included for the similar (workaround) purpose

**Review by mikhail-dcl — CHANGES_REQUESTED** [review]
In general client-wise it's OK but just letting you know that in the ideal world it'd be great if the server could advertise http errors properly: e.g. via [503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/503)

File: Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs (hunk 2 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs:70]: Correct, that is the theoretical total amount

File: Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs (hunk 3 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadTextureSystem.cs:100]: Initially I put a `Delay` but then I realized that the `WebRequestController`, on exception, if a delay is specified, it executes it before failing [here](https://github.com/decentraland/unity-explorer/blob/4b8a10586333f9f0e28e215c53c913c66407dcbb/Explorer/Assets/DCL/WebRequests/WebRequestController.cs#L77). This means that I still get a delay before the very last attempt

File: Explorer/Assets/DCL/WebRequests/WebRequestController.cs (hunk 4 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/WebRequests/WebRequestController.cs:80]: Using the `ignoreErrorCodes` set would break the attempts logic though, since [it](https://github.com/decentraland/unity-explorer/blob/4b8a10586333f9f0e28e215c53c913c66407dcbb/Explorer/Assets/DCL/WebRequests/WebRequestController.cs#L57) directly returns the default value of the result 🤔

**Comment by lorenzo-ranciaffi** [comment]
> In general client-wise it's OK but just letting you know that in the ideal world it'd be great if the server could advertise http errors properly: e.g. via [503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/503)

I agree, in fact there is a conversation about this that I can link you where we discussed the problem. Unfortunately as of now, there is no practical way for the BE to return a different code

File: Explorer/Assets/DCL/WebRequests/WebRequestController.cs (hunk 4 above)
Comment (mikhail-dcl) [reply Explorer/Assets/DCL/WebRequests/WebRequestController.cs:80]: Fine, I will change it when Http2 is merged

**Review by anicalbano — APPROVED** [review]
✔️ Reviewed and approved by QA following the sanity checks mentioned by Dafne on re-testing.
