### PR TITLE
fix: nft stream videos with preview image

### LINKED ISSUE #1461: Goerli | Video screens in NFT-Museum (85, -8) produce audio but not video
### **Explorer Alpha build versions:**

- **v0.13.0**
- **v0.14.0**

### **Issue Description:**
In the NFT-Museum scene at coordinates (85, -8), approaching the video screen located on the ground floor results in audio playback without corresponding video.

### **STR:** 

1. Use the `/world goerli` command in the chat.
2. Navigate to coordinates (85, -8) in the NFT-Museum scene.
3. Walk up to the video screen located on the ground floor.
4. Observe the screen's behavior.

### **Expected behavior:**

https://github.com/user-attachments/assets/869ea035-eeb4-434d-b1c3-d9f1db9b01db

### **Current behavior:**

https://github.com/user-attachments/assets/8ab648f0-4086-4329-a1e5-0a29a12a0dbc

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #1461 

There was a problem when a single `PrimitiveMeshRenderer` has either set a regular texture (acting as a preview of the stream) and then changes into a video stream and viceversa. The material was not being updated properly neither re-assigned to the renderer. Also the material configuration was restored with a `y:-1` texture scale provoking an undesired result.
The solution involves:
- Restoring the texture scale (1,1) whenever the material is the creation process.
- Making a copy and re-applying into ecs the invalidated material while in the updating process.

## How to test the changes?

1. Follow issue steps
2. Also check that 3d models have their visual properties (including the texture) correctly applied, in any other scene

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs [hunk 1]
```diff
@@ -181,14 +181,26 @@ private bool TryCreateGetTexturePromise(in TextureComponent? textureComponent, r
...
-            promise = textureComponent.Value.IsVideoTexture
-                ? Promise.CreateFinalized(intention, GetOrAddVideoTextureResult(textureComponentValue))
-                : Promise.Create(World!, intention, partitionComponent);
+            if (textureComponent.Value.IsVideoTexture)
+                promise = Promise.CreateFinalized(intention, GetOrAddVideoTextureResult(textureComponentValue));
+            else
+            {
+                if (Equals(ref textureComponentValue, ref promise))
+                {
+                    promise = promise!.Value.TryGetResult(World!, out var texture)
```
Comment (AlejandroAlvarezMelucciDCL) [inline Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs:190]: Nitpick: You could consider adding the `TryGetResult` as an "and" condition to the `if` in line 188, thus removing the need of ternary operator's else statement, since it's the same as the `else` of the `if` in line 188:

```csharp
if (Equals(ref textureComponentValue, ref promise) && 
   promise!.Value.TryGetResult(World!, out var texture))
{
   promise = Promise.CreateFinalized(intention, texture);
}
else
{
   promise = Promise.Create(World!, intention, partitionComponet);
}
```

**Review by AlejandroAlvarezMelucciDCL — APPROVED** [review]
Looks good to me! 👍 I just left a small nitpick comment, feel free to discard it if you don't like it 💪

File: Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/CreateMaterialSystemBase.cs [hunk 2]
```diff
@@ -44,6 +44,13 @@ protected static void TrySetTexture(Material material, ref StreamableLoadingResu
 
             if (textureComponent is { IsVideoTexture: true })
                 material.SetTextureScale(propId, VIDEO_TEXTURE_VERTICAL_FLIP);
+
+            // When the material is re-used for another texture we need to restore the texture scale
+            // Otherwise in case it was previously a video texture it gets x:1,y:-1 scale which is undesired
+            // This case happens on nft-museum at sdk-goerli-plaza 85,-8. A plane exists which has a texture that acts as a "preview" of the stream.
+            // Whenever you get close or far, the texture is changed either to video stream or regular exposing this issue
+            else
+                material.SetTextureScale(propId, Vector2.one);
```
Comment (lorux0) [inline Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/CreateMaterialSystemBase.cs:53]: Not sure if this is the best place to restore the texture scale. This method is called either when the material is created from scratch or updated by invalidation. Also here is where the texture scale is flipped, but perhaps there is a better place, since this should only apply when the material is invalidated

File: Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs (hunk 1 above)
Comment (lorux0) [reply Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs]: True, thx for the input!
