### PR TITLE
Fix/6386 remove snapshot property from profiles

### LINKED ISSUE #6386: Remove snapshot property from profiles
### Description

Profile snapshots currently include the "snapshot" property that is being deprecated on the **8th Febrary 2026**.

We need to remove this property and no longer submit an image.

### PR DESCRIPTION
**Pull request by biotech77**
# Pull Request Description
Profile snapshots currently include the "snapshot" property that is being deprecated on the 8th Febrary 2026.
This PR removes them.
[Details](https://adr.decentraland.org/adr/ADR-290)

## What does this PR change?
Resolves #6386 

This PR only changes the data we send to the backend, functionality stays the same. Profile and body thumbnails are correctly updated.

### Test Steps
1. Open backpack and wear sunglasses, hat or something that will change your face thumbnail
2. Close backpack
3. Wait and check profile image to change
4. Observe that is correct

## Quality Checklist
- [X] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs [hunk 1]
```diff
@@ -333,7 +319,10 @@ private bool TryRemoveOngoingRequest(string userId, out UniTaskCompletionSource<
                 // Centralized endpoint doesn't support GET
                 if (useCentralizedProfiles)
                 {
-                    profile = await ProfilesRequest.PostSingleAsync(webRequestController, PostUrl(fromCatalyst, ProfileTier.Kind.Full), id, version,
+                    var url = PostUrl(fromCatalyst, ProfileTier.Kind.Full);
+                    ReportHub.Log(ReportCategory.PROFILE, $"Executing Single Get via Centralized: {useCentralizedProfiles}, URL: {url}");
```
Comment (lorux0) [inline Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs]: What is the purpose of this log?

**Review by Ludmilafantaniella — APPROVED** [review]
**QA Approved ✅** Tested on **Windows and macOS**.

**Verified:**
* Wearing/removing wearables updates the profile and body thumbnails correctly.
* Profile image updates as expected after closing the backpack.
* Cross-platform sync verified: thumbnail is displayed correctly across platforms.
This PR only affects backend payload structure; user-facing functionality remains intact.

Approving 👍

https://github.com/user-attachments/assets/be641736-24f0-49fd-89ba-d87d98d2b2e4

✅Smoke test:
- ✔️ Backpack and wearables in world
- ✔️ Emotes in world and in backpack
- ✔️ Teleport with map/coordinates/Jump In
- ✔️ Chat and multiplayer
- ✔️ Profile card
