### PR TITLE
fix: multiple chat user online status issues

### LINKED ISSUE #7947: [QA] Chat | DM shows user as offline while they are visibly online in-world
### 🛠️ **Build version:**
v0.136.0-alpha-dev-63afaba

Not reproduced in prod v0.136.0

### 📔 **Issue Description:**

When opening a DM with a user who is visibly standing nearby in-world and shown as online, the DM panel displays that user as offline.

### 👣 **STR:** 

1. Spot another user standing nearby in-world
2. Open a DM conversation with that user

This got solved by restarting the explorer; either more accurate STRs are needed, or this was a service hiccup.

### ✔️ **Expected Result:**
The DM panel should reflect the user's actual online status, showing them as online since they are visibly present in-world.

### ❌ **Actual Result with evidence:**
The DM panel displays the user as offline despite them being visible and active in the same location. 

[Player.log](https://github.com/user-attachments/files/26361150/Player.log)

https://github.com/user-attachments/assets/b5bb9523-4c34-4646-b08d-8cbb8334179d

[Player.log](https://github.com/user-attachments/files/26361150/Player.log)

**According to the analysis of the player.log**

**Authentication/Connection issues at startup:**

There was a `TimeoutException` when connecting to `auth-api.decentraland.org`, and a ConnectionException trying to reach the auth API via WebSocket. This suggests the session may have had some instability from the start.

**HTTP 522 errors (Connection Timed Out):**

Requests to `metamorph-api.decentraland.org` timed out repeatedly. This is a Cloudflare-level timeout meaning Decentraland's own server wasn't responding to Cloudflare at that moment.

**Multiple teleport retries:**

The log shows the game attempted to teleport to (`0, 0`) at least 3 times, which points to general connectivity instability during that session.

**What could explain the DM/offline display issue:**
The social/friends system relies on `rpc-social-service-ea.decentraland.org` (listed as ApiFriends in your config). If that service had any hiccup — which is plausible given the broader connectivity issues visible in the log — the client might have received stale or failed presence data, showing the user as offline even though they were physically visible to you in-world (since world presence and social presence are handled by different services).
The log doesn't contain a specific error for the DM/friends service, so this looks more like a transient server-side issue on Decentraland's end rather than something wrong with your setup. Restarting the client or trying again later would be the practical fix.

##### ❓ Unknown - (note)
Only one case reported so far. May be related to connectivity instability observed in the session logs (auth API timeout, HTTP 522 errors on metamorph-api.decentraland.org).

#### 🖥️ **Operative system and additional Notes:**

Windows 11 (10.0.26200) — MSI Katana 15 B12VFK
GPU: NVIDIA GeForce RTX 4060 Laptop GPU
RAM: 16 GB
Resolution: 1920x1080 @ 144Hz

### LINKED ISSUE #8104: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
Sentry Issue: [UNITY-EXPLORER-KM1](https://decentraland.sentry.io/issues/7214572342/)

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  File "il2cpp-codegen.h", line 633, in Values
  File "GenericMethods__6.cpp", line 24913, in Values
  File "il2cpp-codegen.h", line 67, in Values
  File "GenericMethods__6.cpp", line 24799, in Values
  File "DCL.Social__16.cpp", line 13685, in OnChannelUsersStatusUpdated
...
(17 additional frame(s) were not displayed)
```
This issue was automatically created by Sentry via [Explorer Alpha Github Issue Creation](https://sentry.io/organizations/decentraland/monitors/alerts/3130340/)

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #7947
Fixes #8104

## What does this PR change?

This PR fixes multiple things related to DMs and chat online status:
- Fixed incorrect online status in private chat conversations by making sure that lookups to participant lists are case-insensitive + added a new case of a user connected to island/scene room while not being connected to chat room (other clients)
- Added OTHER_CLIENT chat user state to handle the case where a user is connected from a non-DM-capable client, showing a specific message instead of incorrectly reporting them as offline
- Fixed concurrent modification crashes in participant lists (onlineParticipants) by adding lock synchronization and a snapshotBuffer for safe iteration (Sentry UNITY-EXPLORER-KM1)
- Removed unused `InitializeFriendshipCacheAsync` and the paginated friends fetch

### Test Steps
1. Test that DMs and chat overall works as before
2. Check that online statuses are reported correctly
3. Check that users connected with other clients are correctly identified

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Chat/_Refactor/ChatServices/UserStateService/PrivateConversationUserStateService.cs [hunk 1]
```diff
@@ -231,48 +186,69 @@ public async UniTask<UserState> GetChatUserStateAsync(string userId, Cancellatio
...
 
-            if (friendshipStatus == FriendshipStatus.BLOCKED_BY || !isUserConnected)
-                return new UserState(isUserConnected, ChatUserState.DISCONNECTED);
+            // If we are being blocked by them, show them as offline
+            if (friendshipStatus == FriendshipStatus.BLOCKED_BY)
+                return new UserState(false, ChatUserState.DISCONNECTED);
+
+            // This is done because other clients don't connect to chat livekit room, so they are not found in the participant list.
+            // If we are able to find them through either island or scene room, it means we cannot chat with them
+            if (!isUserConnected && (roomHub.TryGetUser(userId, out _, out _) || roomHub.TryGetUser(lowerUserId, out _, out _)))
```
Comment (Maurizio-dcl) [inline Explorer/Assets/DCL/Chat/_Refactor/ChatServices/UserStateService/PrivateConversationUserStateService.cs:195]: Small comment, in different places there's a need to check userId and then lowerUserId, there's no way of fixing this data inconsistency at the source? LGTM anyway!

**Review by Maurizio-dcl — APPROVED** [review]

File: Explorer/Assets/DCL/Chat/_Refactor/ChatServices/UserStateService/PrivateConversationUserStateService.cs (hunk 1 above)
Comment (lorenzo-ranciaffi) [reply Explorer/Assets/DCL/Chat/_Refactor/ChatServices/UserStateService/PrivateConversationUserStateService.cs:195]: not that I know of since the participant lists are case-sensitive and come from the Livekit SDK

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- [✔️ ] Backpack and wearables in world
- [ ✔️] Emotes in world and in backpack
- [ ✔️] Teleport with map/coordinates/Jump In
- [✔️ ] Chat and multiplayer
- [ ✔️] Profile card
- [✔️ ] Skybox

Made a comparisson between dev environment and this PR , it solves the main issue with the latest changes.

**Evidence:**

https://github.com/user-attachments/assets/5b6ca86b-a60e-43d8-bd18-a8680c8e44df

Image
