### PR TITLE
Fix: removed category filter when swapping from wearables to emotes

### LINKED ISSUE #1013: [QA] Common emotes disappear from backpack
### **Explorer Alpha build version:**
**0.3.335-g8f637032-main**

### **Issue Description:**

Sometimes the common emotes disappear from the backpack. 
The repro steps for this issue can be a little bit hard to get. Sometimes we get the 100% repro, sometimes we don't.

### **Steps to reproduce:**

  1. Go to the backpack and browse a little on the wearables
  2. Change the tab to emotes

### **Expected behaviour:**
Common emotes appear with no issues

### **Current behaviour:**
Common emotes are missing

#### **Evidence:**
image

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #1013 removed the category filter set in wearables when swapping to emotes

Additionally improved backpack stability by tackling various issues and crashes

...

## How to test the changes?

1. Launch the explorer
2. Go to backpack
3. Go to emotes
4. Check base emotes are visible
5. Go back to avatar
6. Set a filter for wearables
7. Go to emotes
8. Check base emotes are visible

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/Backpack/AvatarSection/AvatarController.cs [hunk 1]
```diff
@@ -47,7 +49,10 @@ public void RequestInitialWearablesPage()
 
         public void Activate() { }
 
-        public void Deactivate() { }
+        public void Deactivate()
+        {
+            backpackCommandBus.SendCommand(new BackpackFilterCategoryCommand(""));
```
Comment (lorux0) [inline Explorer/Assets/DCL/Backpack/AvatarSection/AvatarController.cs:54]: You should also handle the name filter and the sorting options

**Review by olavra — APPROVED** [review]

**Review by anicalbano — APPROVED** [review]
🟢 Second review by QA

Uploading 10.05.2024_14.13.11_REC.mp4…
