### PR TITLE
fix: movePlayerTo restricted action does not work

### LINKED ISSUE #677: dclexperience: beam does not work
### **Explorer Alpha build version:**
Main

### **Issue Description:**
image

### **Steps to reproduce:**

  1. Load dclexperience.dcl.eth

### LINKED ISSUE #1149: [QA] Beaming Up message stays on screen after using the teleporter
### **Explorer Alpha build version:**
**Current main at 16/05**

### **Issue Description:**

When getting inside the beam to go up on the caffee, the countdown and beam up modal appears on screen, but the teleport is not working. If we go to the top via `/goto` or via map, we see after teleporting that the modal is still on the screen.

### **Steps to reproduce:**

  1. Go to the caffee at Genesis Plaza
  2. Stand on the beam and wait for the countdown message
  3. Teleport by hand as mentioned on the description.

### **Expected behaviour:**
The message disappears from screen

### **Current behaviour:**
The message still can be seen

#### **Evidence:**
image

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #677 
Fix #1149 

image

## How to test the changes?
1. Launch the explorer
2. Go to the beam area in the cafe
3. Check that the countdown appears
4. Check that after the countdown your avatar is teleported to the upper place of the scene

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/RestrictedActionsAPIWrapper.cs [hunk 1]
```diff
@@ -24,21 +24,21 @@ public void Dispose()
...
-                new Vector3(newRelativePositionX, newRelativePositionY, newRelativePositionZ),
+                new Vector3((float)newRelativePositionX, (float)newRelativePositionY, (float)newRelativePositionZ),
                 null);
         }
 
         [UsedImplicitly]
         public void MovePlayerTo(
-            int newRelativePositionX, int newRelativePositionY, int newRelativePositionZ,
-            int cameraTargetX, int cameraTargetY, int cameraTargetZ)
+            double newRelativePositionX, double newRelativePositionY, double newRelativePositionZ,
```
Comment (dalkia) [inline Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/RestrictedActionsAPIWrapper.cs:36]: Leaving two questions!
1) Is it possible to put float here to avoid the casting below? 
2) If js call this method with ints, wouldnt you have the same issue?

**Review by dalkia — APPROVED** [review]
Approved, but Im curious about the approach. Leaving some questions

File: Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/RestrictedActionsAPIWrapper.cs (hunk 1 above)
Comment (mikhail-dcl) [reply Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/RestrictedActionsAPIWrapper.cs:36]: no, ClearScript marshals floating point numbers as `double`

**Review by mikhail-dcl — APPROVED** [review]

**Comment by olavra** [comment]
It's working

Previous behaviour

https://github.com/decentraland/unity-explorer/assets/41490935/6c367e70-3c4c-4350-8266-71ae17cb3125

Current Behaviour

https://github.com/decentraland/unity-explorer/assets/41490935/643800e6-8350-4e16-a98e-670a2f602286

**Review by olavra — APPROVED** [review]
Approved by QA (Quick Approver)
