### PR TITLE
fix: verify grassRenderer is not null before calling render

### LINKED ISSUE #1687: Jumping to a world and back sometimes throws an exception
### **Explorer Alpha build versions:**

Testing:

1. Jump to NicoE world
2. Jump back to Genesis
3. It should not freeze on loading screen

```
NullReferenceException: Object reference not set to an instance of an object
DCL.Landscape.TerrainGenerator.ShowAsync (DCL.AsyncLoadReporting.AsyncLoadProcessReport postRealmLoadReport) (at Assets/DCL/Landscape/TerrainGenerator.cs:124)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.Factory.cs:211)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:312)
Global.Dynamic.RealmNavigator.LoadTerrainAsync (DCL.AsyncLoadReporting.AsyncLoadProcessReport landscapeLoadReport, System.Threading.CancellationToken ct) (at Assets/Scripts/Global/Dynamic/RealmNavigator.cs:206)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.Factory.cs:211)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:312)
Global.Dynamic.RealmNavigator+<>c__DisplayClass23_0.<TryChangeRealmAsync>b__0 (DCL.AsyncLoadReporting.AsyncLoadProcessReport parentLoadReport) (at Assets/Scripts/Global/Dynamic/RealmNavigator.cs:122)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:312)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise.TryInvokeContinuation (Cysharp.Threading.Tasks.UniTask+WhenAllPromise self, Cysharp.Threading.Tasks.UniTask+Awaiter& awaiter) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.WhenAll.cs:200)
--- End of stack trace from previous location where exception was thrown ---
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise.GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.WhenAll.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:312)
DCL.SceneLoadingScreens.LoadingScreen.LoadingScreen.ShowWhileExecuteTaskAsync (System.Func`2[T,TResult] operation, System.Threading.CancellationToken ct) (at Assets/DCL/SceneLoadingScreens/LoadingScreen/LoadingScreen.cs:32)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:312)
Global.Dynamic.RealmNavigator.TryChangeRealmAsync (CommunicationData.URLHelpers.URLDomain realm, System.Threading.CancellationToken ct, UnityEngine.Vector2Int parcelToTeleport) (at Assets/Scripts/Global/Dynamic/RealmNavigator.cs:106)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:342)
Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:653)
Global.Dynamic.ChatCommands.ChangeRealmChatCommand.ExecuteAsync (System.Text.RegularExpressions.Match match, System.Threading.CancellationToken ct) (at Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs:69)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:342)
Cysharp.Threading.Tasks.UniTask`1+Awaiter[T].GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:653)
DCL.Chat.MessageBus.CommandsHandleChatMessageBus.ExecuteChatCommandAsync (DCL.Chat.Commands.IChatCommand command, System.Text.RegularExpressions.Match param) (at Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs:55)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:312)
Cysharp.Threading.Tasks.UniTaskExtensions+<>c.<Forget>b__16_0 (System.Object state) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskExtensions.cs:572)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
DCL.Diagnostics.DebugLogReportHandler:LogExceptionInternal(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:108)
DCL.Diagnostics.ReportHandlerBase:LogException(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/ReportHandlerBase.cs:49)
DCL.Diagnostics.ReportHubLogger:UnityEngine.ILogHandler.LogException(Exception, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHubLogger.cs:38)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.<>c:<Forget>b__16_0(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskExtensions.cs:576)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:210)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:59)
DCL.Chat.MessageBus.<ExecuteChatCommandAsync>d__10:MoveNext() (at Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs:58)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:334)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:186)
Global.Dynamic.ChatCommands.<ExecuteAsync>d__10:MoveNext() (at Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs:74)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:334)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:186)
Global.Dynamic.<TryChangeRealmAsync>d__23:MoveNext() (at Assets/Scripts/Global/Dynamic/RealmNavigator.cs:143)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:167)
```

### PR DESCRIPTION
**Pull request by m3taphysics**
## What does this PR change?

fixes #1687

### CODE REVIEW

**Review by sandrade-dcl — APPROVED** [review]

**Review by AlejandroAlvarezMelucciDCL — APPROVED** [review]
LGTM 👌

**Review by davidejensen — APPROVED** [review]

File: Explorer/Assets/DCL/Landscape/TerrainGenerator.cs [hunk 1]
```diff
@@ -121,7 +121,10 @@ public async UniTask ShowAsync(AsyncLoadProcessReport postRealmLoadReport)
             UniTask.Yield(PlayerLoopTiming.LastPostLateUpdate);
 
             ReEnableChunksDetails();
-            grassRenderer.Render();
+
+            if(grassRenderer)
+                grassRenderer.Render();
```
Comment (popuz) [inline Explorer/Assets/DCL/Landscape/TerrainGenerator.cs:126]: why not `grassRenderer?.Render();` ?

**Review by popuz — APPROVED** [review]
