### PR TITLE
fix: community name not updated in chat

### LINKED ISSUE #5118: [QA] Communities | name not updated in chat until client restart
### 🛠️ **Build version:**
v0.84.0  

### 📔 **Issue Description:**
When changing the name of a community, the update is correctly reflected in the **Communities screen** and in the **popup notification** sent to members.  
However, in the **community chat**, the old name is still displayed until the client is restarted.  

### 👣 **STR:**  
1. Create or join a community.  
2. Change the community name.  
3. Observe the update in the Communities screen.  
4. Observe the popup notification sent to members.  
5. Open the community chat and check the header name.  

### ✔️ **Expected Result:**  
The new community name should be reflected immediately across **all sections**, including the chat.  

### ❌ **Actual Result with evidence:**  
The chat still displays the old community name until the client is restarted.  

https://github.com/user-attachments/assets/5476be2b-9b90-49ba-ab63-673f5dbfa50d

### ➗ **Reproduction:**  
🔁 Always – happens consistently after renaming a community.  

### 🖥️ **Operative system and additional Notes:**  
Tested on Windows and Mac.

### PR DESCRIPTION
**Pull request by biotech77**
# Pull Request Description
## What does this PR change?
Fixes #5118

Community name update is not reflected in the chat title bar (if that is currently selected community) and when hovering over community channel/conversation in the channel/conversation toolbar

### Prerequisites
- [X] Existing community

### Test Steps
1. Go to the community which name needs to be updated
2. Update name
3. Observe that community name in the chat title bar and community name in the tooltip when hovering over community channel is properly updated

## Quality Checklist
- [X] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Chat/_Refactor/ChatChannels/ChatChannelsPresenter.cs [hunk 1]
```diff
@@ -67,6 +71,8 @@ public ChatChannelsPresenter(ChatChannelsView view,
             this.chatEventBus.OpenPrivateConversationRequested += OnOpenUserConversation;
             this.chatEventBus.OpenCommunityConversationRequested += OnOpenCommunityConversation;
 
+            this.communityDataService.OnCommunityMetadataUpdated += OnOnCommunityChannelMetadataUpdated;
```
Comment (popuz) [inline Explorer/Assets/DCL/Chat/_Refactor/ChatChannels/ChatChannelsPresenter.cs:74]: Can you please rename it to remove these `On` in names - one from event itself and another from function:
`communityDataService.CommunityMetadataUpdated  += OnCommunityChannelMetadataUpdated;`

File: Explorer/Assets/DCL/Communities/CommunityDataService/CommunityDataService.cs [hunk 2]
```diff
@@ -154,11 +205,14 @@ public bool TryGetCommunity(ChatChannel.ChannelId channelId, out GetUserCommunit
             return communities.TryGetValue(channelId, out communityData);
         }
 
+        public event Action<CommunityMetadataUpdatedEvent>? OnCommunityMetadataUpdated;
```
Comment (popuz) [inline Explorer/Assets/DCL/Communities/CommunityDataService/CommunityDataService.cs:208]: can you move it up before the constructor. Could be lost here in between of functions :)

File: Explorer/Assets/DCL/Communities/CommunityDataService/CommunityDataService.cs [hunk 3]
```diff
@@ -14,10 +15,21 @@
...
+        {
+            ChannelId = channelId;
+        }
+    }
+    
     public interface ICommunityDataService
     {
         void SetCommunities(IEnumerable<GetUserCommunitiesData.CommunityData> communities);
         bool TryGetCommunity(ChatChannel.ChannelId channelId, out GetUserCommunitiesData.CommunityData communityData);
+        event Action<CommunityMetadataUpdatedEvent> OnCommunityMetadataUpdated;
```
Comment (popuz) [inline Explorer/Assets/DCL/Communities/CommunityDataService/CommunityDataService.cs:32]: in our code style (similar to Microsoft) events don't have `On` prefix

File: Explorer/Assets/DCL/Communities/CommunityDataService/CommunityDataService.cs [hunk 4]
```diff
@@ -47,10 +60,48 @@ public CommunityDataService(IChatHistory chatHistory,
...
+
+            var data = result.Value.data;
+            var channelId = ChatChannel.NewCommunityChannelId(data.id);
+
+            // Update cache atomically
+            communities[channelId] = new GetUserCommunitiesData.CommunityData
+            {
+                id = data.id, thumbnails = data.thumbnails, name = data.name, description = data.description,
+                privacy = data.privacy, role = data.role, ownerAddress = data.ownerAddress, membersCount = data.membersCount
+            };
```
Comment (popuz) [inline Explorer/Assets/DCL/Communities/CommunityDataService/CommunityDataService.cs:98]: what do you think about making a constructor for `CommunityData ` to hide all these assignments inside the class itself?

**Review by popuz — APPROVED** [review]
Looks good. I left some cosmetical comments

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- [✔️  ] Backpack and wearables in world
- [✔️  ] Emotes in world and in backpack
- [✔️  ] Teleport with map/coordinates/Jump In
- [✔️  ] Chat and multiplayer
- [ ✔️ ] Profile card
- [ ✔️ ] Settings

Evidence:

https://github.com/user-attachments/assets/e9db2bfc-b03d-4252-bad3-7b2a6b69825a
