### PR TITLE
fix: debounce friends online status updates

### LINKED ISSUE #5936: [QA] Notifications | Online friend notification keeps appearing even if they are already on
### 🛠️ **Build version:**
N/A

### 📔 **Issue Description:**

When a friend goes online, we can see the first notification at the botton right of the screen, but after a couple of minutes the notification starts appearing and disappearing constantly, erven if the user is still online.

### 👣 **STR:** 

  1. Login and ask a friend to login with you
  2. Wait for the **{Name} is online** notification to appear
  3. Remain next to your friend and observe

### ✔️ **Expected Result:**
The online notification only appears when the user goes online 

### ❌ **Actual Result with evidence:**
The online notification keeps appearing, with pauses of a couple of seconds and then starts again

[Player.log](https://github.com/user-attachments/files/23096886/Player.log)

https://github.com/user-attachments/assets/e183a822-a0cd-4b41-b614-3e09407c9c62

### PR DESCRIPTION
**Pull request by lorenzo-ranciaffi**
# Pull Request Description
Fixes #5936 

## What does this PR change?

This PR introduces a simple time-based debouncing mechanism to the friends online status change in order to avoid multiple notifications for the same user (might happen with faulty connections).

### Test Steps
1. Follow the steps described in the linked issue and verify that it no longer happens
2. You can manually trigger online updates by:
   1. using two builds and two different accounts
   2. opening the debug panel
   3. toggling on and off (with like 1s delay) the island room connection of one user
   4. Verify that the online status change is shown only after the last toggle you did (all the others were "filtered")

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Friends/FriendsConnectivityStatusTracker.cs [hunk 1]
```diff
@@ -53,22 +74,84 @@ private bool FriendOnlineStatusChanged(FriendProfile friendProfile, OnlineStatus
...
+                    && currentInfo == info)
+                {
+                    debounceInfo.Remove(info.FriendProfile.Address);
+                    info.CancellationTokenSource.SafeCancelAndDispose();
+                }
+            }
         }
 
-        private void FriendBecameOffline(FriendProfile friendProfile)
+        private struct FriendStatusDebounceInfo : IEquatable<FriendStatusDebounceInfo>
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Friends/FriendsConnectivityStatusTracker.cs]: the struct can be made readonly

File: Explorer/Assets/DCL/Friends/FriendsConnectivityStatusTracker.cs [hunk 2]
```diff
@@ -53,22 +74,84 @@ private bool FriendOnlineStatusChanged(FriendProfile friendProfile, OnlineStatus
...
         {
-            if (FriendOnlineStatusChanged(friendProfile, OnlineStatus.OFFLINE))
-                OnFriendBecameOffline?.Invoke(friendProfile);
+            public FriendProfile FriendProfile;
+            public OnlineStatus NewStatus;
+            public CancellationTokenSource CancellationTokenSource;
+            public DateTime LastUpdateTime;
```
Comment (davidejensen) [inline Explorer/Assets/DCL/Friends/FriendsConnectivityStatusTracker.cs]: LastUpdateTime can be private

**Review by davidejensen — APPROVED** [review]
approved with minor suggestion
