### PR TITLE
fix: prevent notifications polling from stopping on transient server errors (UNITY-EXPLORER-N0Y)

### LINKED ISSUE #7618: Cysharp.Threading.Tasks.UnityWebRequestException: HTTP/1.1 502 Bad Gateway
Sentry Issue: [UNITY-EXPLORER-N0Y](https://decentraland.sentry.io/issues/7291213848/)

```
Cysharp.Threading.Tasks.UnityWebRequestException: HTTP/1.1 502 Bad Gateway
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>notifications.decentraland.org | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Bad gateway</span>
              <span class="code-label">Error code 502</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=notifications.decentraland.org" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2026-03-17 17:32:01 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=notifications.decentraland.org" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Seattle</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=notifications.decentraland.org" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">notifications.decentraland.org</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Host
    
  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9dddbc0c20f3c3d5</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">199.204.204.142</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=notifications.decentraland.org" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

  File "C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs", line 77, in MoveNext
  File "C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs", line 116, in MoveNext
  File "C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs", line 53, in MoveNext
  File "C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/DebugMetricsWebRequestController.cs", line 28, in MoveNext
  File "C:/workspace/workspace/p/Explorer/Assets/DCL/WebRequests/WebRequestController.cs", line 53, in MoveNext
...
(93 additional frame(s) were not displayed)
```
This issue was automatically created by Sentry via [Explorer Alpha Github Issue Creation](https://sentry.io/organizations/decentraland/monitors/alerts/3130340/)

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# Pull Request Description
Fix #7618 

## Summary
Fixes the notifications polling loop dying permanently when the server returns transient errors (500, 502, DNS failures, timeouts, etc.).

### Root cause
Two combined issues:

1. **Signed GET requests were never retried** — `signInfo` marks requests as non-idempotent, and the default `RetryPolicy` skips retries for non-idempotent requests. Even though 500/502/503/504 are classified as recoverable, the idempotency check short-circuits before reaching that logic.

2. **No exception handling in the polling loop** — `StartGettingNewNotificationsOverTimeAsync` had no try/catch, so any unhandled exception killed the loop permanently. `SuppressCancellationThrow()` at the call site only suppresses `OperationCanceledException`, not web request errors.

### Changes

- Use `RetryPolicy.Enforce()` for notification GET requests so they are retried on transient errors (up to 2 retries with exponential backoff)
- Wrap the polling loop body in try/catch to survive any exception after retries are exhausted, logging via `ReportHub` and continuing on the next 5s cycle

### Error breakdown from Sentry (all 220 events)

| Error | Count | Covered |
|---|---|---|
| 502 Bad Gateway | 75 | Retry + catch |
| Cannot resolve destination host | 34 | Retry + catch |
| Unknown Error | 32 | Catch |
| Failed to transmit data | 30 | Catch |
| 401 Unauthorized | 22 | Catch (loop survives, next cycle uses fresh signature) |
| Cannot connect to destination host | 9 | Retry + catch |
| Request timeout | 7 | Retry + catch |
| SSL connection errors | 7 | Retry + catch |
| 500 Internal Server Error | 1 | Retry + catch |
| Other (400, receive errors) | 3 | Catch |

### Test Steps
The notification system should keep working normally and recover automatically from any transient
server issues.

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs [hunk 1]
```diff
@@ -89,50 +89,57 @@ public async UniTask StartGettingNewNotificationsOverTimeAsync(CancellationToken
...
+                            list.Add(notification.Id);
+                        }
+                        catch (Exception e)
+                        {
+                            ReportHub.LogException(e, ReportCategory.UI);
+                        }
+
+                    await SetNotificationAsReadAsync(list, ct);
+                }
+                catch (OperationCanceledException) { throw; }
```
Comment (lorenzo-ranciaffi) [inline Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs]: As far as I see, the only way to cancel this token is logout/login. Do we need to throw here? It looks like it's just an unmanaged exception that triggers on account change

**Review by lorenzo-ranciaffi — CHANGES_REQUESTED** [review]

File: Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs (hunk 1 above)
Comment (sandrade-dcl) [reply Explorer/Assets/DCL/Notifications/NotificationsRequestController.cs]: Good point! You're right that the only cancellation source is in the logout/login, and `.SuppressCancellationThrow()` at the caller already handles it. I've changed it to `return` instead of `throw`, this way the loop exits cleanly without propagating an exception that would just be suppressed anyway.

Done here: https://github.com/decentraland/unity-explorer/pull/8116/commits/ac9665765aca0800d6a09b2a433dabad4b5af96a

**Review by lorenzo-ranciaffi — APPROVED** [review]

**Review by Ludmilafantaniella — APPROVED** [review]
**QA Result: ✅ Approved**
Tested on Windows and Mac.

**Notifications tested:**
- Friend request sent and received ✅
- Community invite notification ✅
- Badge notification ✅
- Event notification ✅
- Gift notification — received some, but there is a known existing issue

All notifications are received correctly and the polling system works as expected. No regressions found.

Image

Image

Image

Image

Image

Image

✅Smoke test perfomed:
- ✔️  Log In/Log Out
- ✔️ Backpack and wearables in world
- ✔️ Emotes in world and in backpack
- ✔️ Teleport with map/coordinates/Jump In
- ✔️ Chat and multiplayer
- ✔️ Profile card
- ✔️ Camera
- ✔️ Skybox
