### PR TITLE
fix: nametags cancellation token

### LINKED ISSUE #2270: Nametags exception
### **Explorer Alpha build versions:**
```
ObjectDisposedException: The CancellationTokenSource has been disposed.
System.Threading.CancellationTokenSource.ThrowObjectDisposedException () (at <606c2e0a56af495988c860a4ac613e74>:0)
System.Threading.CancellationTokenSource.ThrowIfDisposed () (at <606c2e0a56af495988c860a4ac613e74>:0)
System.Threading.CancellationTokenSource.get_Token () (at <606c2e0a56af495988c860a4ac613e74>:0)
DCL.Nametags.NametagView.StartChatBubbleFlowAsync (System.String chatMessage) (at Assets/DCL/NameTags/NametagView.cs:155)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
DCL.Diagnostics.DebugLogReportHandler:LogExceptionInternal(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:109)
DCL.Diagnostics.ReportHandlerBase:LogException(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/ReportHandlerBase.cs:49)
DCL.Diagnostics.ReportHubLogger:UnityEngine.ILogHandler.LogException(Exception, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHubLogger.cs:38)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:SetException(Exception) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:53)
DCL.Nametags.<StartChatBubbleFlowAsync>d__71:MoveNext() (at Assets/DCL/NameTags/NametagView.cs:158)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:204)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder:SetResult() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:70)
DCL.Nametags.<AnimateInAsync>d__74:MoveNext() (at Assets/DCL/NameTags/NametagView.cs:211)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/CompilerServices/StateMachineRunner.cs:189)
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.WhenAllPromise:TryInvokeContinuation(WhenAllPromise, Awaiter&) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.WhenAll.cs:210)
Cysharp.Threading.Tasks.<>c:<.ctor>b__3_0(Object) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTask.WhenAll.cs:189)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit) (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.TweenConfiguredSource:OnCompleteCallbackDelegate() (at ./Library/PackageCache/com.cysharp.unitask@73d86259ce/Runtime/External/DOTween/DOTweenAsyncExtensions.cs:254)
DG.Tweening.Tween:OnTweenCallback(TweenCallback, Tween)
DG.Tweening.Core.TweenManager:Despawn(Tween, Boolean)
DG.Tweening.Core.TweenManager:DespawnActiveTweens(List`1)
DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single)
DG.Tweening.Core.DOTweenComponent:Update()
```

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes #2270 

There was a miss-management of the cancellation token in the name tags animation process. The original `CancellationTokenSource.Token` was referenced on each case, instead of passing a `CancellationToken` through parameter. When the original source was disposed it provoked the described exception.
The solution consists on only referencing the `CancellationTokenSource` once, at the start of the process and pass the `CancellationToken` only to the pipeline. Additionally, when the `cts` is disposed a new instance is required, since it becomes unusable. A proper `OperationCancelledException` handling was implementer to reset the internal animation state.

## How to test the changes?

1. Launch the explorer
2. Group up with another peer in the same place
3. Write in the chat
4. The chat bubbles over the nametags should be working as expected

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/NameTags/NametagView.cs [hunk 1]
```diff
@@ -141,44 +132,70 @@ public void SetChatMessage(string chatMessage)
...
+            {
+                if (isAnimatingIn || isWaiting)
+                    await AnimateOutAsync(ct);
+
+                await AnimateInAsync(chatMessage, ct);
+
+                isAnimatingIn = false;
+                isWaiting = true;
+
+                await UniTask.Delay((chatBubbleConfiguration?.bubbleIdleTime ?? 5000) + AdditionalMessageVisibilityTimeMs(chatMessage), cancellationToken: ct);
```
Comment (mikhail-dcl) [inline Explorer/Assets/DCL/NameTags/NametagView.cs:163]: Can you introduce a named constant instead of `5000`?

**Review by mikhail-dcl — APPROVED** [review]

**Review by sandrade-dcl — APPROVED** [review]

File: Explorer/Assets/DCL/NameTags/NametagView.cs (hunk 1 above)
Comment (lorux0) [reply Explorer/Assets/DCL/NameTags/NametagView.cs]: Converted all default settings into constants
