### PR TITLE
Fix: avatar systems order atomization

### LINKED ISSUE #779: Exception when jumping to location with other avatars
### **Explorer Alpha build version:**
Main

### **Issue Description:**

We think the following exception is causing many seemingly unrelated issues.

```
InvalidOperationException: The previously scheduled job BoneMatrixCalculationJob writes to the Unity.Collections.NativeArray`1[Unity.Mathematics.float4x4] BoneMatrixCalculationJob.BonesMatricesResult. You are trying to schedule a new job BoneMatrixCalculationJob, which writes to the same Unity.Collections.NativeArray`1[Unity.Mathematics.float4x4] (via BoneMatrixCalculationJob.BonesMatricesResult). To guarantee safety, you must include BoneMatrixCalculationJob as a dependency of the newly scheduled job.
Unity.Jobs.LowLevel.Unsafe.JobsUtility.ScheduleParallelForTransform (Unity.Jobs.LowLevel.Unsafe.JobsUtility+JobScheduleParameters& parameters, System.IntPtr transfromAccesssArray) (at <c5ed782439084ef1bc2ad85eec89e9fe>:0)
UnityEngine.Jobs.IJobParallelForTransformExtensions.Schedule[T] (T jobData, UnityEngine.Jobs.TransformAccessArray transforms, Unity.Jobs.JobHandle dependsOn) (at <c5ed782439084ef1bc2ad85eec89e9fe>:0)
DCL.AvatarRendering.AvatarShape.Components.AvatarTransformMatrixComponent.ScheduleBoneMatrixCalculation (UnityEngine.Matrix4x4 avatarWorldToLocalMatrix) (at Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarTransformMatrixComponent.cs:20)
DCL.AvatarRendering.AvatarShape.GPUSkinning.StartAvatarMatricesCalculationSystem.Execute (DCL.AvatarRendering.AvatarShape.UnityInterface.AvatarBase& avatarBase, DCL.AvatarRendering.AvatarShape.Components.AvatarTransformMatrixComponent& transformMatrixComponent, DCL.AvatarRendering.AvatarShape.Components.AvatarShapeComponent& avatarShapeComponent) (at Assets/DCL/AvatarRendering/AvatarShape/Systems/StartAvatarMatricesCalculationSystem.cs:37)
DCL.AvatarRendering.AvatarShape.GPUSkinning.StartAvatarMatricesCalculationSystem.ExecuteQuery (Arch.Core.World world) (at Arch.System.SourceGenerator/Arch.System.SourceGenerator.QueryGenerator/StartAvatarMatricesCalculationSystem.Execute(ref AvatarBase, ref AvatarTransformMatrixComponent, ref AvatarShapeComponent).g.cs:37)
DCL.AvatarRendering.AvatarShape.GPUSkinning.StartAvatarMatricesCalculationSystem.Update (System.Single t) (at Assets/DCL/AvatarRendering/AvatarShape/Systems/StartAvatarMatricesCalculationSystem.cs:27)
ECS.Abstract.BaseUnityLoopSystem.Update (System.Single& t) (at Assets/Scripts/ECS/Abstract/BaseUnityLoopSystem.cs:29)
Rethrow as EcsSystemException: [ECS]: [StartAvatarMatricesCalculationSystem]
ECS.Abstract.BaseUnityLoopSystem.Update (System.Single& t) (at Assets/Scripts/ECS/Abstract/BaseUnityLoopSystem.cs:35)
Arch.SystemGroups.ExecutionNode`1[T].Update (T& t, System.Boolean throttle) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/ExecutionNode.cs:78)
Arch.SystemGroups.SystemGroup.Update (Arch.SystemGroups.UnityBridge.TimeProvider+Info& timeInfo) (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/SystemGroup.cs:118)
Arch.SystemGroups.DefaultSystemGroups.PresentationSystemGroup.Update () (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/DefaultSystemGroups/PresentationSystemGroup.cs:23)
Arch.SystemGroups.SystemGroupAggregate.TriggerUpdate () (at ./Library/PackageCache/com.arch.systemgroups@3d2186e909/PlayerLoopHelper/Aggregation/SystemGroupAggregate.cs:36)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
DCL.Diagnostics.DebugLogReportHandler:LogExceptionInternal(EcsSystemException) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:86)
DCL.Diagnostics.DebugLogReportHandler:LogExceptionInternal(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/DebugLogReportHandler.cs:97)
DCL.Diagnostics.ReportHandlerBase:LogException(Exception, ReportData, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Handlers/ReportHandlerBase.cs:49)
DCL.Diagnostics.ReportHubLogger:UnityEngine.ILogHandler.LogException(Exception, Object) (at Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHubLogger.cs:38)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

### **Steps to reproduce:**

  1. Have other players join and jump to 30,30
  2. Jump to their location
  3. Notice the exceptions

### LINKED ISSUE #829: Avatar instantiation is delayed by 1 frame
As we fixed the order of the systems https://github.com/decentraland/unity-explorer/pull/801/files we need to grasp the whole picture to comprehend the right order of the systems without skipping 1 frame.

### PR DESCRIPTION
**Pull request by mikhail-dcl**
**Streamline the order of the avatar-related system**

* Introduce individual groups that are executed as atoms (no foreign systems can squeeze in-between)
* Move Avatar cleaning up to `CleanUp` group to ensure that adding `DeleteEntityIntention` will lead to the actual disposal if it's added at any moment of the player loop
* Fix Random Avatars destruction
* Optimize the number of assemblies
* Introduce the debug system to check Avatar Transform leaks

**Fix CharacterTransform leak to the scene**

----
Fixes #829 
Fixes #779

### CODE REVIEW

File: Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs [hunk 1]
```diff
@@ -31,15 +33,19 @@ namespace DCL.CharacterPreview
...
-            CharacterPreviewCameraSettings cameraSettings)
+            CharacterPreviewCameraSettings cameraSettings, IComponentPool<Transform> transformPool)
         {
             globalWorld = world;
             characterPreviewAvatarContainer = avatarContainer;
             cameraController = new CharacterPreviewCameraController(inputEventBus, characterPreviewAvatarContainer, cameraSettings);
             this.characterPreviewContainerPool = characterPreviewContainerPool;
 
+            var parent = transformPool.Get();
+            parent.SetParent(avatarContainer.avatarParent, false);
```
Comment (m3taphysics) [inline Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs:44]: Does the transform need resetting?

**Review by m3taphysics — APPROVED** [review]

File: Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/TrackTransformMatrixSystem.cs [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+            TrackAbandonedTransformMatrixQuery(World);
+        }
+
+        [Query]
+        private void TrackAbandonedTransformMatrix(Entity entity, ref AvatarTransformMatrixComponent avatarTransformMatrixComponent, in DeleteEntityIntention deleteEntityIntention)
+        {
+            if (!deleteEntityIntention.DeferDeletion && !avatarTransformMatrixComponent.disposed)
+            {
+                ReportHub.LogError(ReportCategory.AVATAR, $"{nameof(AvatarTransformMatrixComponent)} was not disposed properly. Archetype:\n {World.GetArchetype(entity)}");
+                avatarTransformMatrixComponent.Dispose();
```
Comment (dalkia) [inline Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/TrackTransformMatrixSystem.cs:34]: Im not sure how we get to this scenario, butf its abandoned, should we delete the Entity here?

**Review by dalkia — APPROVED** [review]

File: Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs (hunk 1 above)
Comment (Kinerius) [reply Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs:44]: I guess that we don't move the avatars in the local position but I think an additional check wouldn't hurt

**Review by Kinerius — APPROVED** [review]

File: Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs (hunk 1 above)
Comment (mikhail-dcl) [reply Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs:44]: I did reset here just in case, but also in the pool itself `onRelease`

File: Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/TrackTransformMatrixSystem.cs (hunk 2 above)
Comment (mikhail-dcl) [reply Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/TrackTransformMatrixSystem.cs:34]: No, Entity will be deleted in the next system: `DestroyEntitySystem`

Comment (mikhail-dcl) [reply Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/TrackTransformMatrixSystem.cs:34]: It can be possible if the query was not executed due to the filter, but it's a theory
