### PR TITLE
Fix: footsteps and walked distance badge

### LINKED ISSUE #2189: [QA] User is not able to hear steps when jumping
### **Explorer Alpha build versions:**
0.29.31

### **Issue Description:**
When jumping or running , user is not able to hear their steps.

### **STR:** 

  1. Open 0.29.31
  2. Go to genesis plaza 
  3. Run or jump 
  4. Validate that the avatar is not making any sound when jumping or running 

### **Expected behavior:**
The sounds of steps should be heard when jumping or running all over the scene 

### **Current behavior:**
When jumping or running , user is not able to hear their steps.

#### **Evidence:**

https://github.com/user-attachments/assets/5556a945-9984-4b7b-814b-b07ef9385e73

#### **Additional Notes:**
Happens on both Mac and Windows

### PR DESCRIPTION
**Pull request by popuz**
## What does this PR change?
Fix #2189 

Fixed walked distance analytics. 
- added sending on intervals and on amount of steps reached. Accumulation will be done on the backend
- added steps count to the debug panel
- handle the case of re-login with the different account

## How to test the changes?

1. Launch the explorer
2. Open Debug panel for Badges
3. Check that step count is increasing for about 30 seconds and then become 0, and increase again. 
4. Accumulate some steps and re-login -> observe steps counter to be zero

Additionally steps sound is back. However, jumping on place is still not producing the sound

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by lorux0 — APPROVED** [review]

**Review by anicalbano — COMMENTED** [review]
🟢 Working as expected on Windows side! The test also included:
- Backpack / emotes / wearables
- Teleport
- Navigation Bar
- Map and map teleporting
- Metadynelabs teleport
- Chat and social interaction
- 
https://github.com/user-attachments/assets/91c04e9b-b1de-40ea-98be-397b60e1ae58

capture_240927_165107

Awaiting for Mac for fully approval

File: Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs [hunk 1]
```diff
@@ -37,31 +39,56 @@ public partial class BadgesHeightReachedSystem : BaseUnityLoopSystem
...
 
-            currentIdentity = identityCache.Identity;
+            currentIdentity = identityCache?.Identity;
 
-            totalElevationGainBinding = new ElementBinding<string>(string.Empty);
             debugContainerBuilder
                .TryAddWidget("Badges Tracking")?
-               .AddCustomMarker("Vertical Voyager: ", totalElevationGainBinding);
+               .AddCustomMarker("Vertical Voyager: ", totalElevationGainBinding)
+               .AddCustomMarker("Steps Count: ", stepsCountBinding);
```
Comment (sandrade-dcl) [inline Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs:62]: Maybe, as we did for the "Vertical Voyager" badge, we should put here the official name of the badge related to the steps count to know what specific badge we're tracking?

```suggestion
               .AddCustomMarker("Walkabout Wanderer: ", stepsCountBinding);
```

Not an important thing, but let's agree a format 👍

**Review by sandrade-dcl — APPROVED** [review]

File: Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs (hunk 1 above)
Comment (popuz) [reply Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs:62]: even for Voyager I would put what it is - "Elevation gain [m]". Since it is not clear what logic is applied to create badge out of this metric, its rules of calculation. For example, Walkabout Wanderer will perform on backend and sum all received "steps-count" analytics events. Moreover, since steps count sent each 30 sec and reset to zero, you will see "Walkabout Wanderer:" going 0... 15... 56.. 0.. 20... 70... 0..  Does it give any evidence about the badge? from my opinion - no. But it shows that the tracker works :)

Comment (popuz) [reply Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs]: added both :)
