### PR TITLE
fix: Colliders too close to the scene limits (but inside them) were being deactivated

### LINKED ISSUE #1737: [QA] Shuttle Pad loses colliders and stops moving in Metagamimall (145, 60)
### **Explorer Alpha build versions:**

- **v0.20.0**
- **v0.50.0**

### **Issue Description:**
In the Metagamimall scene at coordinates (145, 60), the Shuttle Pad stops moving midway through its path. After it stops, it loses its colliders, preventing players from jumping back onto it.

### **STR:** 

1. Launch the explorer
2. Navigate to coordinates (145, 60) in Metagamimall.
3. Board the Shuttle Pad and start the journey.
4. Observe the Shuttle Pad as it moves along its path.

### **Expected behavior:**
The Shuttle Pad should complete its journey without stopping and retain its colliders, allowing players to interact with it as intended.

https://github.com/user-attachments/assets/7aa1f55f-9e3d-49c3-87b0-d597955999c6

### **Current behavior:**

https://github.com/user-attachments/assets/3c35f895-3464-453d-a898-5a88ac5fc0fd

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX

There is another ticket created related to the jerky movement: https://github.com/decentraland/unity-explorer/issues/1487

### PR DESCRIPTION
**Pull request by sandrade-dcl**
# Pull Request Description

## What does this PR change?
Fix #1737 

In some scenes (like in "Meta GamiMall") the colliders that were too close to the scene bound limits (but inside them) were being deactivated.

image
image
image

This was happening due to the comparison between decimals that we were doing. Now, in order to apply a small margin to this comparison, we apply a rounding so we asure the we manage correctly these scenarios where a collider is too close to a bound limit.

### Prerequisites
None.

### Test Steps
1. Go to Meta GamiMall (`145, 60`)
2. Board the Shuttle Pad and start the journey.
3. Check that the platform never loses its collider.

## Quality Checklist
- [ ] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs [hunk 1]
```diff
@@ -149,8 +149,10 @@ public static bool Contains(this in SceneCircumscribedPlanes boundingPlanes, Bou
             Vector3 min = bounds.min;
             Vector3 max = bounds.max;
 
-            return boundingPlanes.MinX < min.x && boundingPlanes.MaxX > max.x
-                                               && boundingPlanes.MinZ < min.z && boundingPlanes.MaxZ > max.z;
+            return Mathf.Ceil(boundingPlanes.MinX) <= Mathf.Ceil(min.x) &&
+                   Mathf.Ceil(boundingPlanes.MaxX) >= Mathf.Ceil(max.x) &&
+                   Mathf.Ceil(boundingPlanes.MinZ) <= Mathf.Ceil(min.z) &&
+                   Mathf.Ceil(boundingPlanes.MaxZ) >= Mathf.Ceil(max.z);
```
Comment (AnsisMalins) [inline Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs:155]: Strange solution. Why not just `bounds.Expand(Vector3.kEpsilon)` before the comparison?

**Review by AnsisMalins — CHANGES_REQUESTED** [review]

File: Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs (hunk 1 above)
Comment (AnsisMalins) [reply Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs:155]: Or Expend by `-Vector3.kEpsilon`.

**Review by AnsisMalins — APPROVED** [review]
I guess it's fine, but it's strange.

File: Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs (hunk 1 above)
Comment (sandrade-dcl) [reply Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs:155]: The difference in this case is about `0,03223`, but I think `Vector3.kEpsilon` is much less than that, right?

image

Comment (sandrade-dcl) [reply Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs]: @AnsisMalins I finally decided to make use of the `bounds.Expand(...)` with a `BOUNDS_OFFSET_EPSILON` of `0.1f` 👍 I think this makes it much clearer and simpler. Thanks for the feedback!

Changes done [here](https://github.com/decentraland/unity-explorer/pull/3400/commits/9f967237195a598f2b15b783620e03e8a4064725).
