### PR TITLE
Fix: user can teleport while in loading screen

### LINKED ISSUE #3435: [QA] Teleport | User is able to teleport while teleporting to a location
### 🛠️ **Build version:**
0.55.0

### 📔 **Issue Description:**
User is able to teleport while teleporting to a certain location

### **STR:** 

  1. Open 0.55.0  
  2. Teleport manually to `/goto -149,64` by command (prepare a copy/paste action to teleport to another place like : `/goto -137,52` )
  3. Once the loading screen appears paste the command copied before
  4. Press enter 
  5. Check that the loading bar resets 
  6. Check that an error modal appears but when pressing the OK button does not seem to be responsive 

### ✔️ **Expected Result:**
User should not be able to teleport while teleporting to a certain location

### ❌ **Actual Result with evidence:**
User is able to teleport while teleporting to a certain location

Evidence:

https://github.com/user-attachments/assets/5b755b13-93a8-40f1-8385-bd70bc701ba5
[Player (2).log](https://github.com/user-attachments/files/18965279/Player.2.log)

### ➗ **Repro Index:**
10/10

### 🖥️ **Operative system and additional Notes:**
This issue happens on both platforms

### PR DESCRIPTION
**Pull request by popuz**
# Pull Request Description
Fix #3435

## What does this PR change?
- Add check for loading status to be completed when sending commands from the chat

## Test Instructions
See referenced bug ticket

STR:
Open 0.55.0
- Teleport manually to `/goto -149,64` by command (prepare a copy/paste action to teleport to another place like : `/goto -137,52` )
- Once the loading screen appears paste the command copied before
- Press enter
- Check that the loading bar resets
- Check that an error modal appears but when pressing the OK button does not seem to be responsive

## Quality Checklist
- [x] Changes have been tested locally
- [ ] Documentation has been updated (if required)
- [ ] Performance impact has been considered
- [ ] For SDK features: Test scene is included

## Code Review Reference
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before submitting.

### CODE REVIEW

File: Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs [hunk 1]
```diff
@@ -80,7 +80,7 @@ private async UniTaskVoid OnChatAsync(ReceivedMessage<Decentraland.Kernel.Comms.
             }
         }
 
-        private bool IsMention(string chatMessage, string userName)
+        private static bool IsMention(string chatMessage, string userName)
```
Comment (dalkia) [inline Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs:83]: Why this `static` addition?

**Review by dalkia — DISMISSED** [review]
Nice

**Review by DafGreco — APPROVED** [review]
✔️  PR reviewed and approved by QA on both platforms following instructions playing both happy and un-happy path

Regressions for this ticket had been performed in order to verify that the normal flow is working as expected:

- ✅ Backpack and wearables in world
- ✅ Emotes in world and in backpack
- ✅ Teleport with map/coordinates/Jump In
- ✅Profile card
- ✅ Camera
- ✅ Skybox
- ✅ Settings


_For copy on macos use : command key + C
For paste on macos use : command key + V_

**Evidence:**

https://github.com/user-attachments/assets/8c75f7ec-74e8-4196-aeef-f1924f156e96

File: Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs (hunk 1 above)
Comment (popuz) [reply Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs:83]: because why not :) just tiny optimization.

**Review by davidejensen — APPROVED** [review]
approving, but I think we should entirely disable the chat input when in loading screen

**Review by dalkia — APPROVED** [review]
Much better, thanks!

**Review by davidejensen — APPROVED** [review]

**Comment by DafGreco** [comment]
was able to trigger the operation cancelled 2 times attempting to teleport from one place to another :c  and the button seems to be unresponsive. User needs to quit and re-open the app.

@popuz 

https://github.com/user-attachments/assets/f3b71473-e262-4182-9c9a-ad9ec085805c

**Comment by popuz** [comment]
So new repro steps are

1. Past in chat `/goto -137,52`
2. Click on minimap and choose `dollhouse `-> jump there via JumpIn
3. While loading screen start to press enter so the chat command get executed

**Comment by DafGreco** [comment]
Hey team seems that there's another behavior regarding spaming the chat while teleporting 


https://github.com/user-attachments/assets/3fd493ac-1d12-45ab-906a-4adac9aeb631


[Player.log](https://github.com/user-attachments/files/19213688/Player.log)

**Comment by popuz** [comment]
> Hey team seems that there's another behavior regarding spaming the chat while teleporting
> 
>  12.03.2025_16.15.35_REC.mp4 
> [Player.log](https://github.com/user-attachments/files/19213688/Player.log)

This new issue is a bit different - it is when you past /goto very fast after teleporting. So loading screen is completed and teleportation is over, you paste new teleportation command and it start execution but without LoadingScreen (curtain). However, I consider it minor and not related to the current fixed bug. Let's extract it.

**Review by m3taphysics — APPROVED** [review]
