### PR TITLE
Fix: check for not reloading same realm

### LINKED ISSUE #889: Using /goto "anywhere" doesn't validate if its a real shortcut, and can get stuck
### **Explorer Alpha build version:**
Main

### **Issue Description:**
Join goerli plaza and then try jump elsewhere. I am unsure if this is related to goerli plaza specifically but we get stuck in a loop.

### **Steps to reproduce:**

1. /goto goerli
2. then try:
3.  /goto goerli
4. /world metadynelabs
5. /world dclexperience

### PR DESCRIPTION
**Pull request by popuz**
## What does this PR change?
fix #889

## How to test the changes?
Test steps are provided in the referenced issue [#889](https://github.com/decentraland/unity-explorer/issues/889)

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/Minimap/MinimapController.cs [hunk 1]
```diff
@@ -221,7 +221,7 @@ private void SetWorldMode(bool isWorldModeActivated)
         public override void Dispose()
         {
             cts.SafeCancelAndDispose();
-            realmNavigator.OnRealmChanged -= OnRealmChanged;
+            realmNavigator.RealmChangedToGenesis -= OnRealmChangedToGenesis;
```
Comment (dalkia) [inline Explorer/Assets/DCL/Minimap/MinimapController.cs:224]: I dont know if this name change is ideal. This action is called on any realm change, not only on realm change to genesis. And we have a boolean that indicates that (if its genesis or not).

**Review by dalkia — CHANGES_REQUESTED** [review]
Minor question regarding method naming

**Review by anicalbano — APPROVED** [review]
🟢 Reviewed by QA (unrelated issue on the video)


https://github.com/decentraland/unity-explorer/assets/139157886/441ddb1d-8699-4040-aede-9804f666d28d

**Review by dalkia — APPROVED** [review]
