### PR TITLE
fix: added bus for mac audio event for media player

### LINKED ISSUE #2294: [QA] Sound Settings Not Affecting Scene Audio
### **Explorer Alpha build versions:**

- **v0.29.0**
- **v0.76.0**
- **v0.90.0**

### **Issue Description:**
In certain scenes with their own audio, such as Casa Roustan (37,-114) or Doll House (-102,-97), the in-game sound settings do not control the scene's audio. The volume should be adjustable through the sound settings but currently remains unaffected.

📌 Notes
- The issue affects scenes with their own audio implementation, independent of global sound settings.

📝 LOGS:
[Player.log](https://github.com/user-attachments/files/20796422/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/20796421/Player-prev.log)

### **STR:** 
1. Launch the explorer.
2. Go to Casa Roustan (37,-114) or Doll House (-102,-97).
3. Open the settings menu and adjust the sound settings to lower the volume.
4. Observe the audio from the scene.

⚠ UPDATED STR:
1. Enter the Game Night Arena scene. (-8,88)
2. Walk from Game Night Arena into the Game Night General scene.
3. While in the General scene, adjust the volume using the in-scene settings (e.g., lower or mute it).
4. Walk back and forth between the Arena and the General scene.
5. Attempt to adjust the volume again from the settings panel in the General scene.

### ✅ Expected Result
The sound settings should adjust the audio for all in-scene sounds, allowing the user to lower or mute it.

#### ❌ Actual Result
The scene's audio remains unaffected by the sound settings, and the volume does not decrease.

https://github.com/user-attachments/assets/c8f31199-a80e-4ba7-9840-1b966dcdcd57

### ➗ **Repro Index:**
5/10

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #2294 
This PR adds a workaround to control directly the media stream audio instead of relying on the AudioMixer values.
This is needed on macos because mac os doesn’t allow to route audio from HLS through to Unity. This is a limitation of Apple’s AVFoundation framework.

...

## How to test the changes?

1. Launch the explorer
2. Go to dollhouse
3. Verify that changing the world volume in the settings affects the volume of the scene stream

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs [hunk 1]
```diff
@@ -148,5 +181,12 @@ private void UpdateStreamUrl(ref MediaPlayerComponent component, string url)
             component.URL = url;
             component.State = url.IsValidUrl() ? VideoState.VsNone : VideoState.VsError;
         }
+
+        public override void Dispose()
+        {
+            base.Dispose();
+
+            worldVolumeMacBus.OnWorldVolumeChanged -= OnWorldVolumeChanged;
```
Comment (fcolarich) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:189]: should this also be #if'ed?

File: Explorer/Assets/DCL/Settings/ModuleControllers/WorldSoundsVolumeSettingsController.cs [hunk 2]
```diff
@@ -28,6 +30,7 @@ private void SetWorldVolumeSettings(float volumePercentage)
         {
             generalAudioMixer.SetFloat(WORLD_VOLUME_EXPOSED_PARAM,  AudioUtils.PercentageVolumeToDecibel(volumePercentage));
             settingsDataStore.SetSliderValue(WORLD_VOLUME_DATA_STORE_KEY, volumePercentage, save: true);
+            worldVolumeMacBus.SetWorldVolume(volumePercentage / 100);
```
Comment (fcolarich) [inline Explorer/Assets/DCL/Settings/ModuleControllers/WorldSoundsVolumeSettingsController.cs:33]: idem here? should this be #if'ed as well? so we dont do any unnecessary calcs?

**Review by fcolarich — APPROVED** [review]
Nice hack! thanks Mac 🙄
Left a couple of comments :)

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs [hunk 3]
```diff
@@ -25,17 +26,43 @@ namespace DCL.SDKComponents.MediaStream
...
+        private const string WORLD_VOLUME_DATA_STORE_KEY = "Settings_WorldVolume";
+
         private readonly IWebRequestController webRequestController;
         private readonly ISceneData sceneData;
         private readonly ISceneStateProvider sceneStateProvider;
         private readonly IPerformanceBudget frameTimeBudget;
-
-        public UpdateMediaPlayerSystem(World world, IWebRequestController webRequestController, ISceneData sceneData, ISceneStateProvider sceneStateProvider, IPerformanceBudget frameTimeBudget) : base(world)
+        private readonly WorldVolumeMacBus worldVolumeMacBus;
+        private float volume = 1f;
```
Comment (dalkia) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:36]: I woudl rename this to `volumePercentage`. Just to make it clearer

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs [hunk 4]
```diff
@@ -25,17 +26,43 @@ namespace DCL.SDKComponents.MediaStream
...
             this.webRequestController = webRequestController;
             this.sceneData = sceneData;
             this.sceneStateProvider = sceneStateProvider;
             this.frameTimeBudget = frameTimeBudget;
+            this.worldVolumeMacBus = worldVolumeMacBus;
+
+            //This following part is a workaround applied for the MacOS platform, the reason
+            //is related to the video and audio streams, the MacOS environment does not support
+            //the volume control for the video and audio streams, as it doesn’t allow to route audio
+            //from HLS through to Unity. This is a limitation of Apple’s AVFoundation framework
```
Comment (dalkia) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:55]: I would add the link to the AVPro issue, maybe one day it will be fixed. And we can check it easily if we have the link

File: Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs [hunk 5]
```diff
@@ -25,17 +26,43 @@ namespace DCL.SDKComponents.MediaStream
...
+#if UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX
+            this.worldVolumeMacBus.OnWorldVolumeChanged += OnWorldVolumeChanged;
```
Comment (dalkia) [inline Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs:57]: I would try to keep all dirtyness contained in a single class, `WorldVolumeMacBus`. Put the compilation directives there, as well as adding a `GetVolumePercentage()` function

**Review by dalkia — APPROVED** [review]
Leaving some suggestions for consideration

**Review by DafGreco — APPROVED** [review]
Implementation done and verified on Windows and Mac !
